### PR TITLE
when an alarm is triggered by an announcement, show the message

### PR DESCRIPTION
**Pull request by jasoncalabrese**
screen shot 2015-09-01 at 6 43 37 pm

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
resolves #888

**Comment by oamyoamy** [comment]
Testing wip/announce-alarms -- alarm triggered by announcement is now showing both alert level (e.g., urgent) and announcement text. 

New issue: Announcement-triggered alarm is reappearing every 1 minute, even though snoozed via browser. (Tested at both red and yellow thresholds; same behavior.)

**Comment by jasoncalabrese** [comment]
So the pushover isn't getting cleared by the browser?

**Comment by oamyoamy** [comment]
Correct!

**Comment by oamyoamy** [comment]
The browser alarm itself keeps replaying. Every 1 minute. Despite snoozing it for 120 mins in browser. (I tried a 30 min snooze as well.)

**Comment by jasoncalabrese** [comment]
@oamyoamy, I looked over things that could cause that and the only possibility I see is that server lost the pushover receipts.  So when the web alarms was cleared the server wasn't able to tell pushover to cancel the alarms.  Before the receipts were only stored for 15mins, I extended that to an hour.  In any case I don't think it was related to this fix.

**Pull request merged**
