### PR TITLE
Fix entries api null dereference

### PR DESCRIPTION
**Pull request by jpcunningh**

### CODE REVIEW

**Comment by PieterGit** [comment]
@jpcunningh LGTM. Can you add information in what context / situation `lastEntryDate` got `null`?

**Comment by sulkaharo** [comment]
Is this related to https://github.com/nightscout/cgm-remote-monitor/issues/4053 ? Looks like data from Glimp is a bit broken and we need to add validation to prevent broken data from getting into the system in the first place.

**Comment by jpcunningh** [comment]
I don’t use Glimp, so I’m not sure if it is directly related. I noticed the
stack traces in my log file and put in a check to at least keep it from
crashing.

**Comment by sulkaharo** [comment]
Can you pull out what data entries are causing the issue? I'd love to know where this data is coming from, so we can fix the underlying problem.

**Comment by jpcunningh** [comment]
@sulkaharo, I think I found the entries that were causing the issue.

I was testing code in Lookout and accidentally uploaded a record that should have gone into the treatments collection into the entries collection instead. Treatments uses created_at instead of date and dateString for the time field.

You are right that this error could have been avoided by using data validation on insert.

**Comment by PieterGit** [comment]
@jpcunningh @sulkaharo what to do with this PR. I think we should add validation, but I think we must do that for the 0.12 release. Do want to merge this in the meantime for 0.11, or just skip it. Please let me know what to do.

**Comment by jpcunningh** [comment]
Let's close this PR and wait for the validation since I created my own problem by inserting invalid data. :smile:

**Pull request closed without merging**
