### PR TITLE
Use auth tokens in api-secret

### PR DESCRIPTION
**Pull request by sulkaharo**
This PR allow auth tokens to be passed in the api-secret header and used in the client in place of the API secret

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/api/verifyauth.js  1
- lib/api/status.js  1
- lib/hashauth.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgm-remote-monitor/cgm-remote-monitor/pullRequest?prid=4512659&bid=15205042)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/hashauth.js  3
- lib/api/status.js  1
- lib/api/verifyauth.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgm-remote-monitor/cgm-remote-monitor/pullRequest?prid=4512659&bid=15205042)

**Comment by sulkaharo** [comment]
The tests pass locally and in Travis, if someone can figure out why they break in Actions that'd be great

**Comment by PetrOndrusek** [comment]
That CI test error is really strange...
In my local environment everything passes, too. 
When comparing output from my local env I can see the first difference after `Application appears to be online` line.
This suspicious difference in Github CI is this line:
`Authentication failed. { message: 'OK' }`
I know this is far from the final solution, but maybe it can help you somehow..

**Comment by PetrOndrusek** [comment]
Maybe the problem is because the mock functions (`mockDone` ones) in admintools.test.js are not setting the `message.rolefound` field to `FOUND` and this issue is somehow exposed only when on Github CI...

**Comment by PetrOndrusek** [comment]
And I would carefully compare environment variables when running both on Travis and Github Actions. I would guess that there could be some slight differences, maybe creating a single test that simple logs all the env variables could help us identifying such weird issues.

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/api/status.js  1
- lib/hashauth.js  3
- lib/api/verifyauth.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgm-remote-monitor/cgm-remote-monitor/pullRequest?prid=4512659&bid=15205042)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/hashauth.js  2
- lib/api/status.js  1
- lib/api/verifyauth.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/cgm-remote-monitor/cgm-remote-monitor/pullRequest?prid=4512659&bid=15205042)

**Pull request merged**
