### PR TITLE
zero temp and rendering update to node 8.8.1

### PR DESCRIPTION
**Pull request by PieterGit**
update https://github.com/nightscout/cgm-remote-monitor/pull/2926 to node 8.8.1 and make tests work

### CODE REVIEW

**Comment by sulkaharo** [comment]
Merging soon

**Comment by PieterGit** [comment]
4 failing tests are probably fixed by my travis updates, but unfortunately there are three test cases of `client.renderer.test.js` still need to fixed:

```
not ok 67 renderer bubbleScale prevChartWidth < 400 scales correctly
  AssertionError: expected NaN to be approximately 3.5 ±0.0001
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value [as approximately] (node_modules/should/cjs/should.js:305:19)
      at Context.it (tests/client.renderer.test.js:24:60)
not ok 68 renderer bubbleScale prevChartWidth < 500 scales correctly
  AssertionError: expected NaN to be approximately 2.625 ±0.0001
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value [as approximately] (node_modules/should/cjs/should.js:305:19)
      at Context.it (tests/client.renderer.test.js:24:60)
not ok 69 renderer bubbleScale prevChartWidth < 900 scales correctly
  AssertionError: expected NaN to be approximately 1.75 ±0.0001
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value [as approximately] (node_modules/should/cjs/should.js:305:19)
      at Context.it (tests/client.renderer.test.js:24:60)
```

I will try to fix this tonight or this weekend.

**Comment by PieterGit** [comment]
I can't find the error in the unit test yet. Help is needed. I suspect two possible causes:

1. calcTreatmentRadius() and drawTreatment() now require carbratio as last argument
2. I made a merge error (I can blame SourceTree, but it's probably my lack of git knowledge 😃  )

**Comment by PieterGit** [comment]
@sulkaharo @scottleibrand : found and fixed the merge error. Travis CI and tests work fine as well. 
I also added some code to show the ` U`  suffix for non-SMB. Screenshot:

image

This is ready for review and if it's ok, please merge it to dev.

I can imagine, non SMB users might want some (minor) adjustments (e.g. increase the font size), but that need to be reviewed.

**Comment by PieterGit** [comment]
This PR has been merged to https://github.com/nightscout/cgm-remote-monitor/pull/2926 so this PR is closed. Please test/use PR 2926.

**Pull request merged**
