### PR TITLE
Show IOB from devicestatus when available (OpenAPS or MM Connect)

### PR DESCRIPTION
**Pull request by mddub**
* Pass `devicestatus` to `iob.calcTotal` and `cob.cobTotal`
* Let IOB be undefined sometimes (No treatments and no devicestatus in sandbox == haven't heard from device in a while == undefined IOB, displayed as "---U". Assuming/showing "0U" in this case would be misleading.)
* ...but always return a number on /pebble for backwards compatibility with the clients in the wild

### CODE REVIEW

**Comment by bewest** [comment]
Looking pretty good.

**Comment by jasoncalabrese** [comment]
Wish we merged this a little sooner, there's a conflict in `report.js`

@MilosKozak

**Comment by MilosKozak** [comment]
hmm i missed this. like your changes in loading ....

**Comment by MilosKozak** [comment]
it should be easy to put it together. the only conflict to be solved is i filter devicestatuses with openaps part ... you need all records

**Comment by mddub** [comment]
Merged dev. The conflict was pretty small.

The only difference is that for the reports page, I leave data.devicestatus sorted by mills descending. This is required for the IOB calculation, and if I sort or assert an ordering before that calculation, the rendering takes significantly longer. The only place outside of my changes where it's used is to map each SGV to a devicestatus within 5 minutes of it, and that doesn't need optimization.

**Comment by jasoncalabrese** [comment]
Was ready to merge this, but I think there's an issue when there are multiple rigs, since the latest devicestatus might not be the best, there could be another rig sending old info.

I think the fix for that isn't so bad and probably makes sense for me to do it, having OpenAPS IOB in the pill will be really nice, so I'm hoping to get to it tonight.

Also I'm wondering if we should have an option to pick the IOB source instead of doing the auto detect, maybe that's for later.

**Pull request merged**
