### PR TITLE
Loopalyzer enhanced

### PR DESCRIPTION
**Pull request by lixgbg**
A PR with an enhancement to Nightscout reports Loopalyzer. This PR displays the relevant profiles (basal, CR, ISF) for the days analyzed below the charts. Very convenient to have the profiles data when analyzing how to tweak various ratios.

This PR can replace #3629 which was the original one and this PR should be merged into #4169.

/Henrik Sjöstrand

### CODE REVIEW

**Comment by PieterGit** [comment]
Tried the branch, but did not see a new table popping up. Perhaps something goes wrong in the profile loading. Needs further investigation.

**Comment by PieterGit** [comment]
@lixgbg my bad, somehow I used the old branch. After update it still doesn't work, but it fails with

```
loopalyzer.js:676 Uncaught TypeError: Cannot read property 'basal' of undefined
    at loopalyzer.js:676
    at Array.forEach (<anonymous>)
    at Object.o.renderProfilesTable (loopalyzer.js:673)
    at Object.o.generateReport (loopalyzer.js:840)
    at Object.o.report (loopalyzer.js:803)
    at report.js?v=6k8rh3w99aqsggwf:533
    at Vt (lodash.js:516)
    at Function.Ua (lodash.js:9343)
    at Function.r.eachPlugin (index.js:39)
    at showreports (report.js?v=6k8rh3w99aqsggwf:517)
```

**Comment by PieterGit** [comment]
@lixgbg Retested, but I still get the same error:
image

I will try to debug my profile later, but I don't have other reports complain about problems with the profile (and wonder how my profile got bad).

I also noted you introduced some new `translate()` fields. Are these all available in `language.js`?

**Comment by PieterGit** [comment]
@lixgbg I think I fixed the profile loading stuff. Can you test and review https://github.com/nightscout/cgm-remote-monitor/pull/4235 or https://github.com/PieterGit/cgm-remote-monitor/tree/201901_loopalyzer-enhanced

**Comment by lixgbg** [comment]
Hello

I have fixed the remaining changes and it's now ready for final test. 

My version is at https://github.com/lixgbg/cgm-remote-monitor/tree/wip/report-loopalyzer-enhanced

**Pull request merged**
