### PR TITLE
Maker docs copyedit & cleanup

### PR DESCRIPTION
**Pull request by unsoluble**
Full edit for clarity and consistency.

### CODE REVIEW

**Comment by PieterGit** [comment]
@unsoluble is it ready to merge? 
@Dave9111 can you review these changes?

**Comment by unsoluble** [comment]
Ready from my end.

**Comment by Dave9111** [comment]
Oh.. I just realized that you already edited it.  I thought you were going to do it after the merge.
Let me look it over.

**Comment by Dave9111** [comment]
Looks good ! 
Dave

**Pull request merged**
