### PR TITLE
Fix "disaplyed" typo

### PR DESCRIPTION
**Pull request by dbeasy**
Fix typo for hover tip for "Raw BG" display in the static/index.html (settings drawer).

I'm new to git and can't find a branch/fork of mine to merge and to not include the  static/report/index.html changes too. Those don't have to be changed in dev or master. I didn't focus group test changing the sorting. I just use the "treatments" tab a lot to fix incomplete documentation from the pebble watch and I like "most recent" at the top.

Thanks

### CODE REVIEW

**Comment by sulkaharo** [comment]
Ha, nice catch! Can you include the fix for language.js as well, so the translation doesn't break?

**Comment by dbeasy** [comment]
I'll look for the language.js changes needed hopefully this weekend, I tried looking a couple weeks ago, but all the translations seemed daunting (assuming I was even in the right spot in code.)

**Comment by dbeasy** [comment]
Also, it looks like the travis make build failed because of my changes to the default sorting (newest at top) of the reporting screen. I should branch this typo fix into a new clean branch from dev so my changes to reporting don't get included in this pull request.

not ok 224 reports should produce some html
  AssertionError: expected -1 to be above -1
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value (node_modules/should/cjs/should.js:305:19)
      at afterInit (tests/reports.test.js:269:174)

**Comment by PieterGit** [comment]
Cherry picked the merges and merged to dev with https://github.com/nightscout/cgm-remote-monitor/pull/3369 . Closing this PR.  @dbeasy thanks for finding and fixing.

**Pull request closed without merging**
