### PR TITLE
Share

### PR DESCRIPTION
**Pull request by shgrady**
Merging to try out the Share features

### CODE REVIEW

**Comment by shgrady** [comment]
error, meant to merge my fork

**Comment by jasoncalabrese** [comment]
Think you're attempting to update your dev branch instead the main repo.

Try using the update tool to update your dev branch: http://nightscout.github.io/pages/update-fork/

**Comment by shgrady** [comment]
I understand I need the dev because I got the new DexCom G4 with Share?

I cannot get the app itself to pick up the data.

**Comment by jasoncalabrese** [comment]
With dev and with the beta releases for Funnel Cake, Nightscout can connect directly to Dexcom's servers.  First get Share working with the Dexcom apps, then hooking up your Nightscout site is easy.

**Pull request closed without merging**
