### PR TITLE
build: Adhere to conventionalcommits.org

### PR DESCRIPTION
**Pull request by PieterGit**
Creating changelog's for new releases is quite some work. 

Starting 0.12 I would like to propose that we adhere to https://www.conventionalcommits.org/ to create a detailled changelog. At least for the commits that squash PR's to the `dev` branch.

We can still create a more userfriendly summary for https://github.com/nightscout/cgm-remote-monitor/releases

This PR introduces the `standard-verion` library for development that is able to automatically generate CHANGELOGs

I propose not to introduce this with `0.11`, because:
- we should change a lot of previous commits
- we are already at `0.11.2-rc2-20190323` and this library will introduce a `0.11.2-rc.0` version.

### Changes:
- Developers should follow: one PR equals, at most, one feature or fix.
- Core commiters should adhere to conventionalcommits.org when squashing PR commits, see: 
https://github.com/conventional-changelog/standard-version#should-i-always-squash-commits-when-merging-prs
- We should stop using `YYYYMMDD` dates in the version meta data (e.g. `0.11.2-rc2-20190323`, and use `0.12.0-alpha.0` for future `dev` releases. The changelog will show the date released.

@sulkaharo @jpcunningh @jasoncalabrese @MilosKozak please 👍  or 👎

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
This feels like a bit of overkill to me, I do support squashing PRs with a bunch of intermediate commits, but I don’t think we always need to squash.

Normally the change log is based on merged PRs not commits, right?

**Comment by PieterGit** [comment]
@jasoncalabrese the changelog is created by hand by me or @sulkaharo by checking all the commits and changes and listing them manually. It's a lot of work (and errorprone) and since only a few core committers squash/merge commits I think it's easier to prefix those "squash and merge" commits with a noun like `fix` or `feature` (and perhaps differentiate `translation`). GitHub can only handle ~250 commits in a release, so @sulkaharo asked me to always use `squash and merge`. 

I agree that for us doing a lot of automatically parsing commits is overkill, but I think it's easier (and more accurate) for creating a detailled changelog. For most users I think it's a good idea for use to summarize the main changes for novice users, but that's still possible.

**Comment by jasoncalabrese** [comment]
You can quickly see the list of merged PRs https://github.com/nightscout/cgm-remote-monitor/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+ <https://github.com/nightscout/cgm-remote-monitor/pulls?utf8=%E2%9C%93&q=is:pr+is:merged+>

Then just find the first PR for the release, I don’t think release notes need to be at the commit level

**Comment by PieterGit** [comment]
Postponed to 0.13.0. 
@sulkaharo can you give your opinion on this one. If you also think this is overkill we will close it and not consider use conventionalcommits.org for Nightscout.

**Pull request closed without merging**
