### PR TITLE
new dev branch starting post 14.2.4 release

### PR DESCRIPTION
**Pull request by bewest**
Please target new developments for inclusion in the next release of Nightscout to the `dev` branch.

### CODE REVIEW

**Comment by IvanIkovlev** [comment]
помогите

**Comment by bewest** [comment]
Ideally we'd have several testers volunteer to help diagnose issues synchronizing with Dexcom Share.
* [ ] old-style usernames 
* [ ] email-based usernames
* [ ] EU or OUS testers
* [ ] US testers

**Comment by bewest** [comment]
Have also included features from https://github.com/nightscout/minimed-connect-to-nightscout/pull/24 to hopefully include fetching data from Medtronic Careportal accounts.

**Comment by bjornoleh** [comment]
> ## bridge feature testing
> Ideally we'd have several testers volunteer to help diagnose issues synchronizing with Dexcom Share.
> 
> * [ ]  old-style usernames
> * [ ]  email-based usernames
> * [ ]  EU or OUS testers
> * [ ]  US testers

@bewest I tested current dev. Unfortunately, this does not work currently. Nightscout dev deployed to Heroku, but my NS was then broken.

But then I reverted 513d155728952a3cb360de3434bc985f606ffc3d  minimed-connect-to-nightscout, and now the Dexcom arrows are working again. 

Curiously, when scrolling backwards in time, the undetermined arrow is still present, but new readings are good.

Details:
Old style account (username, not email)
Outside of US Dexcom server

**Comment by devonestes** [comment]
I tested `dev` and reverted the problematic commit referenced above, and I also see everything working with Dexcom again.

Details:
Old style account (username, not email)
Outside of US Dexcom server

**Comment by paulplant** [comment]
I can also confirm that the minimed-connect-to-nightscout commit breaks NS during start-up.

As mentioned by @bjornoleh and @devonestes, reverting this single commit allows it to start correctly and then corrects the Dexcom Bridge trend arrow problem (from deployment onwards).

EU Dex server

> @bewest I tested current dev. Unfortunately, this does not work currently. Nightscout dev deployed to Heroku, but my NS was then broken.
> 
> But then I reverted [513d155](https://github.com/nightscout/cgm-remote-monitor/commit/513d155728952a3cb360de3434bc985f606ffc3d) minimed-connect-to-nightscout, and now the Dexcom arrows are working again.
> 
> Curiously, when scrolling backwards in time, the undetermined arrow is still present, but new readings are good.
> 
> Details: Old style account (username, not email) Outside of US Dexcom server
> 
> Trend arrows seem to be ok now, have observed flat, 45 up and one arrow up.

**Comment by bewest** [comment]
## For Medtronic Carelink folks, we need the following scenarios tested:
* [ ] Carepartner account
* [ ] Patient account
* [ ] outside United States
* [ ] inside United States

**Comment by bjornoleh** [comment]
Can’t comment on Carelink functionality, but dev is working with Dexcom share now, and I had no issues deploying or opening my NS site.

Thanks for the fix, and also looking forward to having less differences in mmol/L BG values between apps with "MMOL_TO_MGDL": 18.018018018

**Comment by bjornoleh** [comment]
@bewest , did you find any evidence that the Share changes were not fully rolled out for OUS accounts? Someone mentioned an inconsistency for European users, where some allegedly were not affected. I am unsure if this was a misunderstanding, or if some may have been using US accounts. I’m just concerned a fix would break unaffected accounts, unless there is already a check that considers if the changes has taken place or not. Perhaps that is the case for the NS fix?

Thanks!

**Comment by bewest** [comment]
@bjornoleh unfortunately I only know what is reported on these threads.  Much more information is required.  The patches in question appear to apply to all glucose values, US and OUS.  It looks to me like there are guards and detection so ensure that so long as the shape of the data stays the same, we can handle trends described by an integer or by a string.  We don't have any  kind of logging for observability that gives us oversight of all Nightscout users.  Likewise Dexcom does not implement equitable data governance policies or have any relationship with us to communicate details about our constituents.

**Comment by bjornoleh** [comment]
> 

Thanks, as long as both ways are supported, I guess it will be fine. I will tag you in the LF FB post with the report I was thinking about from Switzerland.

**Comment by bewest** [comment]
I will say that Dexcom knows that there are different legal and regulatory requirements in different countries.  In addition it is not unusual for them or other medical device vendors to roll out changes in different geographical regions on different timelines.  Both reasons will cause slight differences among the global population.  Nightscout is a big tent.

**Comment by herzogmedia** [comment]
> ## bridge feature testing
> 
> Ideally we'd have several testers volunteer to help diagnose issues synchronizing with Dexcom Share.
> 
>     * [ ]  old-style usernames
> 
>     * [ ]  email-based usernames
> 
>     * [ ]  EU or OUS testers
> 
>     * [ ]  US testers

Hey @bewest,
I can confirm current dev `6cd15350` is working with dexcom share sync. Now shows direction arrows again. Configuration:
- EU Server
- Old-style username

**Pull request merged**
