### PR TITLE
show extended pump properties

### PR DESCRIPTION
**Pull request by MilosKozak**
image

```
{
    "_id": "57cc3fde9b79549412a0276a",
    "device": "openaps://ANC000XXXX",
    "pump": {
        "battery": {
            "percent": 100
        },
        "status": {
            "status": "normal",
            "timestamp": "2016-09-04T15:35:23Z"
        },
        "extended": {
            "TempBasalAbsoluteRate": 1.05,
            "TempBasalStart": "2016-09-04T15:34:53Z",
            "TempBasalRemaining": 27,
            "IsExtended": true,
            "PumpIOB": 0.2,
            "LastBolus": "2016-09-04T15:34:00Z",
            "LastBolusAmount": 0.2
        },
        "reservoir": 181,
        "clock": "2016-09-04T15:37:30Z"
    },
    "created_at": "2016-09-04T15:37:30Z",
}
```

### CODE REVIEW

**Comment by MilosKozak** [comment]
@jasoncalabrese not a problem for you?

**Comment by jasoncalabrese** [comment]
Serms OK, but most of the fields start with lowercase, but guess your using them as labels too.

I don't think we need isExtended, could just look for the existence of the extended field.

**Comment by MilosKozak** [comment]
Not sure if you are using `extended` on your pumps. Goal is to display any pump param that developer wants to upload

**Comment by jasoncalabrese** [comment]
I don't think we have been using extended anywhere, would rather keep it simple and not have the extra flag

**Pull request merged**
