### PR TITLE
Make failing tests fail

### PR DESCRIPTION
**Pull request by aredridel**
So this started as a bit of a saga — I was looking into what it'd take to update d3, since that's an issue for the project, and in so doing realized that the tests weren't actually working — `make test` fails, but the project CI does not. I thought it was something I'd done in the setup, but no, it is in fact [failing in CI but not being reported](https://travis-ci.org/nightscout/cgm-remote-monitor/jobs/598564107) — Search for `not ok` in those results and you'll find the tap output of failing tests.

I can go annotate tests as failing so the build can go green with them marked if that's useful, but I figured I could start the conversation here with this PR.

### CODE REVIEW

**Comment by PieterGit** [comment]
@aredridel Thanks for bringing this up. I wonder if we should use the `tap-set-exit`, or that we should upgrade `jsdom` and potential others to fix this problem. Adding new modules which have not been updated for 4 years might be risky. 

@jpcunningh already started on upgrading d3, see https://github.com/nightscout/cgm-remote-monitor/pull/5081 and join that effort.

I put this on the 0.13.x scope list

**Comment by PieterGit** [comment]
While upgrading to Node 10 and Node 12 found three tests that need to be fixed
https://travis-ci.org/PieterGit/cgm-remote-monitor/builds/599539433

Putting here for reference. My webstorm licence is expired so need to look into it later.

```

ok 1 utils format numbers
not ok 2 utils format numbers short
  AssertionError: expected 'NaN' to be '0'
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (tests/utils.test.js:31:40)
# tests 2

...

not ok 17 Entries REST api post an entry, query, delete, verify gone
  Error: expected 200 "OK", got 401 "Unauthorized"
      at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1618:8)
      at process._tickCallback (internal/process/next_tick.js:63:19)

...

Skipping  loopalyzer
not ok 1 reports should produce some html
  AssertionError: expected -1 to be above -1
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at afterInit (tests/reports.test.js:267:48)
      at /home/travis/build/PieterGit/cgm-remote-monitor/tmp/js/bundle.report.js:222:56140
      at Object.mockEmit [as emit] (tests/fixtures/headless.js:146:19)
      at /home/travis/build/PieterGit/cgm-remote-monitor/tmp/js/bundle.report.js:222:55817
      at Object.mockOn [as on] (tests/fixtures/headless.js:141:19)
      at Object.m.load (tmp/js/bundle.report.js:222:55748)
      at /home/travis/build/PieterGit/cgm-remote-monitor/tmp/js/bundle.report.js:222:41026
      at Object.mockDone [as done] (tests/fixtures/headless.js:71:19)
      at Object.m.init (tmp/js/bundle.report.js:222:40907)
      at Context.<anonymous> (tests/reports.test.js:228:12)
      at /home/travis/build/PieterGit/cgm-remote-monitor/tests/fixtures/headless.js:160:7
      at Object.done (node_modules/benv/index.js:32:21)
      at process.nextTick (node_modules/jsdom/lib/old-api.js:358:18)
      at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by aredridel** [comment]
`tap-set-exit` is one of those 'trends toward done' tiny modules, so I'd tend to use it — that said, your call.

**Comment by sulkaharo** [comment]
@PieterGit Just switch over to VSCode ;)

#5127 fixes the reporting and unit conversion tests. The REST test works for me, @PieterGit are you sure you're you got a fully functional test env if that test fails?

**Comment by sulkaharo** [comment]
LGTM. @PieterGit if you look at the code for tap-set-exit, you'll notice the actual logic is just a couple lines of code :)

**Pull request merged**
