### PR TITLE
ACTUALIZAR

### PR DESCRIPTION
**Pull request by JoanaBer**

### CODE REVIEW

**Comment by turtle6319** [comment]
Merge request

**Comment by JoanaBer** [comment]
Ok
Tanks
update complet

A domingo, 13 de set de 2020, 20:39, turtle6319 <notifications@github.com>
escreveu:

**Comment by sulkaharo** [comment]
Hi! Oops - it seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Don't worry, no harm done! Please try using the Nightscout update tool again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings. We'll close this pull request, as it's now in the Nightscout repository instead of the intended your personal copy.

**Comment by JoanaBer** [comment]
sorry for the synonyms

THANK YOU FOR YOUR HELP



Sulka Haro <notifications@github.com> escreveu no dia terça, 15/09/2020
à(s) 14:35:

**Pull request closed without merging**
