### PR TITLE
Remove forever and dependencies giving warnings on Windows

### PR DESCRIPTION
**Pull request by PieterGit**
First step: remove forever and Procfile 
Work in progress. Needs more testing.

### CODE REVIEW

**Comment by jaylagorio** [comment]
Just ran `npm install --msvs_version=2013` on Windows Server 2016 using this branch:

```
44180 silly gunzTarPerm modified mode [ 'webSocket/index.js.map', 420, 438 ]
44181 silly gunzTarPerm extractEntry webSocket/package.json
44182 silly gunzTarPerm modified mode [ 'webSocket/package.json', 420, 438 ]
44183 silly cache afterAdd rxjs@6.2.1
44184 verbose afterAdd C:\Users\user\AppData\Roaming\npm-cache\rxjs\6.2.1\package\package.json not in flight; writing
44185 verbose afterAdd C:\Users\user\AppData\Roaming\npm-cache\rxjs\6.2.1\package\package.json written
44186 verbose fstream_class Extract
44187 verbose stack Error: unexpected eof
44187 verbose stack     at decorate (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\abstract.js:67:36)
44187 verbose stack     at Extract.Abstract.error (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\abstract.js:61:12)
44187 verbose stack     at Extract._streamEnd (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
44187 verbose stack     at BlockStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
44187 verbose stack     at BlockStream.emit (events.js:104:17)
44187 verbose stack     at BlockStream._emitChunk (C:\Program Files\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:203:10)
44187 verbose stack     at BlockStream.resume (C:\Program Files\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:58:15)
44187 verbose stack     at Extract.Reader.resume (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\reader.js:249:34)
44187 verbose stack     at Entry.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:261:8)
44187 verbose stack     at Entry.emit (events.js:104:17)
44188 verbose fstream_stack Extract._streamEnd (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
44188 verbose fstream_stack BlockStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
44188 verbose fstream_stack BlockStream.emit (events.js:104:17)
44188 verbose fstream_stack BlockStream._emitChunk (C:\Program Files\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:203:10)
44188 verbose fstream_stack BlockStream.resume (C:\Program Files\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:58:15)
44188 verbose fstream_stack Extract.Reader.resume (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\reader.js:249:34)
44188 verbose fstream_stack Entry.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:261:8)
44188 verbose fstream_stack Entry.emit (events.js:104:17)
44189 verbose cwd C:\Nightscout
44190 error Windows_NT 10.0.14393
44191 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2013"
44192 error node v0.12.10
44193 error npm  v2.14.9
44194 error unexpected eof
44195 error If you need help, you may report this error at:
44195 error     <https://github.com/npm/npm/issues>
44196 verbose exit [ 1, true ]
```

**Comment by sulkaharo** [comment]
I recall Heroku refuses to run without forever?

**Comment by PieterGit** [comment]
@jaylagorio Thanks for testing. I will probably work on this PR this weekend.

@sulkaharo Running https://github.com/PieterGit/cgm-remote-monitor/commit/2d763c6f48bd46c19abb9698205077e46e17c3a1 without forever since Jun 24 (~10 days) without problems, so that does not seem to be a problem. According to https://www.toptal.com/nodejs/top-10-common-nodejs-developer-mistakes it's  Mistake #10: Not Using Supervisor Programs. I was hoping Heroku will be able to restart dynos by it selves.

Removing `help wanted` for now. First want to see if the downgrade of the packages fixes the memory ordering problems on dev.

**Comment by jaylagorio** [comment]
@PieterGit Just drop me a heads up here when you've added commits I can pull down! This weekend should work for me for testing.

**Comment by PieterGit** [comment]
@jaylagorio fixed this with https://github.com/nightscout/cgm-remote-monitor/pull/3675
Can you please confirm that Windows support is working for you? 
Note that I also added some documentation in the README

**Comment by PieterGit** [comment]
Removing `forever` is postponed until the 0.11 release

**Comment by jaylagorio** [comment]
Confirmed `npm install` works and Nightscout loads! Thank you!

**Comment by PieterGit** [comment]
Implemented removal of `forever` with https://github.com/nightscout/cgm-remote-monitor/pull/3721. Closing this PR

**Pull request closed without merging**
