### PR TITLE
Option to switch off bolus amount outputs

### PR DESCRIPTION
**Pull request by andrew-dixon**
Reference to #5514

Adds a new settings menu item "Render Bolus Amount" with 5 options:

- All
- All (without leading zero)
- All (just the number)
- 1 U and Over
- None

These options change how the bolus amount is output on the chart. 

Also removed code specifically for OpenAPS SMB as this would no longer be required as the user could select an option from the list.

Also removed an erroneous piece of code on line 573 in `renderer.js` that was setting a variable called `enteredBy` which is never used.

### CODE REVIEW

**Comment by sulkaharo** [comment]
Wonder if the 1U threshold should be configurable / is the right threshold. Nightscout is primarily used to monitor kids, for whom SMBs are all very small (I'd assume max 0.4 IU), so being able to set the threshold somewhere closer to the SMB limit could make sense?

**Comment by andrew-dixon** [comment]
@sulkaharo I set it to 1U and over because that was what it was in the hardcoded OpenAPS SMB code that was already there. I'll take a look at making it configurable. Is there a preference with this sort of thing to where the configuration option should be, e.g. in the interface or in the environment vars? Just thinking it might be easier in the environment vars and also not clutter up the interface more.

**Comment by andrew-dixon** [comment]
@sulkaharo I've added this as an environment variable, BOLUS_RENDER_OVER, with a default value of 1, to match the current OpenAPS SMB implementation but can be set to any value, e.g. 0.3, 1.5, 2, etc... Added description to the `README.md` file as well.

**Comment by sulkaharo** [comment]
Sorry took a while - was doing final comparison between this and release and realised none of the options here match the current behaviour in the master release. If we change behaviour and make it configurable, it'd probably be good to default to a config option that matches the current behaviour, or at least include such option. Second, what'd possibly improve this quite a lot is a small additional CSS change so the boluses under the threshold used a bit smaller font, as that'd reduce the likelyhood of messy rendering a lot.

**Comment by andrew-dixon** [comment]
@sulkaharo The "x U and Over" option, which defaults to 1 U if you don't set the environment variable, is the same as what it currently does for OpenAPS SMB, so that option is the same, except for it defaulting to that for OpenAPS SMB, which in the discussion on #5514 I thought you said you would like to see removed anyway, as having something hardcoded for a specific system isn't a particularly good idea.

With regards to the font size, I will look into that.

**Comment by andrew-dixon** [comment]
@sulkaharo I've made some changes for the font size depending on the bolus amount, so the smaller the bolus amount, the smaller the font. This applies to any bolus under 1U. I've also resolved the merge conflict that was previously showing.

**Comment by sulkaharo** [comment]
What I meant with the removal of OpenAPS code removal is, I'd prefer a solution that's not dependent on OpenAPS vs being generic.

When I enable "1U and over", the text labels below 1U are removed. This doesn't match the current behaviour - in master, the OpenAPS behaviour is that for <1U boluses the string is shortened to not have the leading zero and the U is dropped. With this PR, the options are to

1) Show everything,
2) Strip 0 but show the U,
3) Show the numbers without the U but with the 0,
4) Don't show the number / U at all for boluses under 1 IU,
5) Show nothing

The current Master strips the leading zero _and_ the U, so the dosing string is shortened as much as possible while still shown. I think the best way to have people not be surprised by the PR could be if we can merge the options 2 and 3 in the PR to behave like master (strip the leading 0 and the U), as neither of the options materially shorten the string.

Shot from current master:

Screenshot 2020-03-01 at 20 37 46

**Comment by andrew-dixon** [comment]
Ok, got it, I'll make the requested adjustments.

**Comment by sulkaharo** [comment]
@andrew-dixon if you have the time to finish this, I'd love to get this into the next release

**Comment by andrew-dixon** [comment]
@sulkaharo Sorry for the delay, work has been a little manic. Will hopefully look at this later today.

**Comment by andrew-dixon** [comment]
@sulkaharo I've made the requested change, it was actually a much smaller change to get it working than I expected.

**Pull request merged**
