### PR TITLE
Add Total daily pasal to profile editor.

### PR DESCRIPTION
**Pull request by alimhassam**
Small improvement to profile editor while getting familiar
about the code. Added a simple estimated total daily basal field.

Since this is my first contribution let me know if i'm following the right process and feel free to comment on anything.

### CODE REVIEW

**Comment by MilosKozak** [comment]
make it translatable please

**Comment by sulkaharo** [comment]
Yup looks pretty good, translation missing as Milos commented :)

**Comment by alimhassam** [comment]
I'm not sure what's the best practice for translation, but I tried to make it translatable as best as i could. The profile page doesn't seem to have translation for everything. let me know if it's okay

**Comment by alimhassam** [comment]
Was my update successful? Didn't get any response.

**Comment by alimhassam** [comment]
Is there anythingnything blocking this from being merged??

**Comment by alimhassam** [comment]
@sulkaharo @MilosKozak can you merge this?

**Comment by sulkaharo** [comment]
screen shot 2017-10-20 at 22 51 03

Noticed the displayed values are not rounded, resulting in strange values like in the included screenshot. :) Can you check the displayed values make sense for both mmol and mg/dl users?

Also sorry about unclear request earlier - it's enough to just add English reference to language.js and call that in the UI, we have volunteers to help with the rest.

**Comment by alimhassam** [comment]
Thanks @sulkaharo, good catch. 
I updated to add rounding to 3dp. 

I think the mmol - mg/dl distinction doesn't apply here because it's just an insulin unit.

**Comment by alimhassam** [comment]
@sulkaharo if there are no objections, could you merge that one? I don't want to keep it lingering and have the risk of getting conflicts with anyone's future work

**Pull request merged**
