### PR TITLE
merge branch

### PR DESCRIPTION
**Pull request by eirediabetes**
Update Nigthscout

### CODE REVIEW

**Comment by eirediabetes** [comment]
update Nightscout

**Comment by eirediabetes** [comment]
update ns please.

**Review by eirediabetes — COMMENTED** [review]
update nightscout please.

**Comment by jpcunningh** [comment]
Hi! This pull request was made in the wrong direction - you're trying to pull changes from your copy of Nightscout into the master version.  The correct direction is from master into your copy.

The correct direction for your update PR can be created by this link: https://github.com/eirediabetes/cgm-remote-monitor/compare/master...nightscout:master

**Pull request closed without merging**
