### PR TITLE
Hotfix/2020 06 28/carelink

### PR DESCRIPTION
**Pull request by bewest**
Hotfix for master.  Similar to https://github.com/nightscout/cgm-remote-monitor/pull/5721

### CODE REVIEW

**Comment by tudorfarcas2002** [comment]
@FredMK made a great job. Is working.
We wait to merge it in cgm-remote-monitor/master

**Comment by bewest** [comment]
https://github.com/nightscout/minimed-connect-to-nightscout/pull/3 - this hotfix is currently targeting `hotfix/2020-06-28-carelink`, a branch with patches for hotfix and version bump on the module.  Once known good version is tracked, we will version bump minimed-connect-nightscout and adjust this hotfix to match, and hotfix release.

**Comment by bewest** [comment]
This hotfix is now depending on an officially released version of `minimed-connect-to-nightscout@1.4.0`.

Process of accepting this pull request:
* multiple reviewers sign off that it is working when deployed as expected, bonus points for US and EU folks.
* Once confirmed, I'll run: `./prep_repo_release.sh patch; git checkout master ; git merge -; git push origin --tags master`
* Above should mark this pull request as closed.  I'll also push the new release branch.

We don't publish on npm, so I think that's it, IIRC.

**Comment by bewest** [comment]
I need some confirmation if this is working or not in order to release hotfix back to master.  At this point I want to get master fixed and then worry about dev.  As far as I know, this fixes, it just needs confirmation and reviewer sign off.

**Comment by FredMK** [comment]
In my branch I released some changes, and tests for EU and US connection.

**Comment by Grynn** [comment]
>  need some confirmation if this is working or not in order to release hotfix back to master. At this point I want to get master fixed and then worry about dev. As far as I know, this fixes, it just needs confirmation and reviewer sign off.

FWIW, this branch has been working reliably for me from Jul 3, 4.30pm (GMT +5.3) ...
(Deployed on Heroku)

I did change env, by adding MMCONNECT_VERBOSE and changing MMCONNECT_INTERVAL to 30s from 60s (but that should not have hurt anything).

**Comment by marchugelshofer1981** [comment]
Hi bewest
I just got this update (hotfix/2020-06-28-carelink branch) and finally everything is working again for me.

**Pull request merged**
