### PR TITLE
Some readme changes to prep for merging of #628

### PR DESCRIPTION
**Pull request by stavlor**
Some README.md adds in preparation for merging pull request #628

### CODE REVIEW

**Comment by stavlor** [comment]
Ok thats odd that just changing a read me would change coverage that much...

**Comment by Fokko** [comment]
I think it is possible to exclude .md files from code coverage.
Op 19 jun. 2015 19:17 schreef "Paul Andrel" <notifications@github.com>:

**Comment by stavlor** [comment]
heh, codecov says it dropped but coveralls says no change weird https://coveralls.io/builds/2859685 vs https://codecov.io/github/nightscout/cgm-remote-monitor?ref=ff32017717ac6c9ead79cad0663a896755190e75

**Comment by jasoncalabrese** [comment]
if I messed up the merge or you notice some typo just send another PR

**Pull request merged**
