### PR TITLE
Process multiple profile objects with start and end timestamps and pick ...

### PR DESCRIPTION
**Pull request by sulkaharo**
...the last that matches the time. Also preserves old functionality of using last non-timestamped profile object, if those are present.

### CODE REVIEW

**Comment by sulkaharo** [comment]
The last two commits are about improving the performance of this - looks like the amount of string parsing introduced by the change was a bit much for mobile browsers. The performance improvement impact of the changes is ~100ms on my laptop and took away the newly introduced lag when using Nightscout on the phone.

**Comment by jasoncalabrese** [comment]
looking good and I think this will help me, I plan to test tomorrow

there's a /iob-cob.html page that is probably broken by this.  It basily a debug page, but I'm sure it won't handle the a value containers.  Would be nice to share some code with it on `websocket.js`

**Comment by sulkaharo** [comment]
Yup, the entirety of DIYPS / profile data code needs to be pulled out from client.js in a manner that's usable across the codebase. I'll check what the job-cob.html looks like today.

**Comment by scottleibrand** [comment]
iob-cob.html is already broken in other ways too, and needs a rewrite to
use the same code as client.js.

**Pull request closed without merging**
