### PR TITLE
Wip/clean/complexity

### PR DESCRIPTION
**Pull request by ericmarkmartin**
Reduced cyclomatic complexity of functions in 5 files by factoring out extra functions.

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
sorry for not reviewing and merging this sooner @ericmarkmartin, looks like some of the recent merges created a conflict

**Comment by ericmarkmartin** [comment]
The only test that doesn't pass is the throttling one that I've heard is just a bug. If its something in my changeset, please let me know and I can get on that.

**Comment by jasoncalabrese** [comment]
They are some test fixes on dev that will help, would you mind merging dev into this.  In hoping it's a simple conflict.

**Comment by MilosKozak** [comment]
next time do smaller PRs please, it will be hard to test so much changes together

**Comment by jasoncalabrese** [comment]
sorry @ericmarkmartin I never got around to testing this and now it pretty far behind

**Pull request closed without merging**
