### PR TITLE
Ice Cream update

### PR DESCRIPTION
**Pull request by DillonRob**
nightscoutUpdate

### CODE REVIEW

**Comment by DillonRob** [comment]
updating to Ice Cream

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by DillonRob** [comment]
http://www.nightscout.info/wiki/welcome/how-to-update-to-latest-cgm-remote-monitor-aka-cookie

**Comment by unsoluble** [comment]
Interesting, thanks. In the future, just do a quick double-check of the direction the PR is facing — you want to have your own repository on the left (the "base"), and the nightscout repo on the right (the "head"). The [update tool](http://nightscout.github.io/pages/update-fork/) should do this automatically, but it seems to be failing in some cases.

**Comment by sulkaharo** [comment]
Hi! This PR was made to the "wrong direction", as in "to Nightscout from your fork", instead the wanted "from Nightscout to your fork". Closing this so the team can see the development-related PRs easier (but please come and comment to the question above).

**Pull request closed without merging**
