### PR TITLE
Merge pull request #1 from nightscout/master

### PR DESCRIPTION
**Pull request by payspump1**
pays pull request1

### CODE REVIEW

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by payspump1** [comment]
I got it from the cgm in the cloud facebook post from Terry W.

**Comment by unsoluble** [comment]
Okay, thanks. Looks like you managed to get the update merged okay, but just also created this (extra) pull request. You can close this one (with the button below).

**Comment by payspump1** [comment]
I had help, but yes they got it fixed for me.

**Comment by sulkaharo** [comment]
Hi! This PR was made to the "wrong direction", as in "to Nightscout from your fork", instead the wanted "from Nightscout to your fork". Closing this so the team can see the development-related PRs easier (but please come and comment to the question above).

**Pull request closed without merging**
