### PR TITLE
Russian language update

### PR DESCRIPTION
**Pull request by apanasef**

### CODE REVIEW

**Comment by PieterGit** [comment]
@apanasef can you resolve the conflicts?

**Comment by apanasef** [comment]
made corrections to conflicting entries

**Comment by apanasef** [comment]
Peter, I made some corrections, but cannot make more - they are marked in red. Don’t know how to proceed. Hope I haven’t screwed it all up completely
Fedor



От 29 сентября 2018 г. в 14:32:03, PieterGit (notifications@github.com) написал:

@apanasef can you resolve the conflicts?

**Comment by PieterGit** [comment]
@apanasef I think it's easier for you to start with a new PR based on current `dev` branch. Please check if the Russian translations are ok now. Please link the PR to this one by putting a comment with the hyperlink in it. Can you do that upcoming weeks? In that case we can merge it to the next 0.11 release.

**Comment by PieterGit** [comment]
@apanasef There is a typo. It makes the lanuage javascript invalid, error:

```
./lib/language.js 12269:12
  12269:12  error  Module parse failed: Unterminated string constant You may need an
                   appropriate loader to handle this file type. |       , ro: 'Extensia
                   loop pare a fi dezactivată' |       , pl: 'Plugin Loop prawdopodobnie
                   nie jest włączona' >       , ru: 'плагин ЗЦ Loop не активирован  |
                   ,'alexaLoopForecast': { |       bg: 'According to the loop forecast you
                   are expected to be %1 over the next %2'  @
                   ./lib/report_plugins/index.js 45:14-36  @ ./bundle/bundle.source.js
```

**Comment by apanasef** [comment]
ok, will start anew -- thanks -- make mistakes bs don't know much (to put it mildly) about coding -- will try to meet the deadline

**Comment by PieterGit** [comment]
@apanasef Closing this because you say https://github.com/nightscout/cgm-remote-monitor/pull/4030 is better.

**Pull request closed without merging**
