### PR TITLE
fixed HIGH/LOW dispay on phablets; moved time hide/show from js to css

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Fixes problems like this and similar with HIGH/LOW on iPhone6+ and Nexus6

### CODE REVIEW

**Comment by jimsiff** [comment]
@jasoncalabrese High and Low with an active BG button look good.  After acknowledging the alarm, LOW and flat trend goes to edge of the screen and HIGH and flat trend still stretches past the edge of the screen.

image1

image2

image3

image4

**Comment by jasoncalabrese** [comment]
Thanks for testing that, % scaling all the text like this makes the layout so unpredictable.  I'm going to try reducing the font size for HIGH/LOW.

**Comment by jasoncalabrese** [comment]
I pushed a fix for this, plus since refactoring the other night, it's been working good for me.

Most of thee other changes were to reuse more code between retro and current modes.

**Comment by jimsiff** [comment]
+1... just pulled in the changes earlier tonight.

**Comment by jasoncalabrese** [comment]
thanks for all your help testing @jimsiff, I'm going to merge this

**Pull request merged**
