### PR TITLE
next

### PR DESCRIPTION
**Pull request by borealisns**

### CODE REVIEW

**Comment by sulkaharo** [comment]
This goes the wrong direction, from your fork to Nightscout, should be the other way round.

**Comment by borealisns** [comment]
Sorry, I'll try again. Thanks for your help.

**Comment by borealisns** [comment]
Hi,

Sorry to bother you but how to I fix package.json so I can get a merge
option? Thanks

https://github.com/borealisns/cgm-remote-monitor/pull/5

**Comment by borealisns** [comment]
Hi,

Please can you help me resolve the pacakage.json conflict?  I cannot merge
new version of Nightscout. Thanks!

This branch has conflicts that must be resolvedUse the command line to
resolve conflicts before continuing.
Conflicting files
package.json
Merge pull request


You can also open this in GitHub Desktop <https://desktop.github.com/> or
view command line instructions.
Checkout via command line

If you cannot merge a pull request automatically here, you have the option
of checking it out via command line to resolve conflicts and perform a
manual merge.
HTTPS
GitPatch

Step 1: From your project repository, check out a new branch and test the
changes.

git checkout -b nightscout-master mastergit pull
https://github.com/nightscout/cgm-remote-monitor.git master

Step 2: Merge the changes and update on GitHub.

git checkout mastergit merge --no-ff nightscout-mastergit push origin master

**Comment by sulkaharo** [comment]
If you never really made any code changes you want to retain, the simplest thing you can do is delete your fork and create a new one (which by definition won’t have conflicts).

**Pull request closed without merging**
