### PR TITLE
Multiple CGM Sources using bucketed data

### PR DESCRIPTION
**Pull request by jasoncalabrese**

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Do we need to extend the pebble endpoint to use the buckets for more than delta?

**Comment by scottleibrand** [comment]
Just switched my main Nightscout to this branch.  Looks good so far.

**Comment by jasoncalabrese** [comment]
Great, it's been working good for me too.

I need to add some tests and also think I want to adjust the name/structure of the property.  Currently we have `/api/v2/properties/bgnow`, I might have 2 properties, one just for the delta.  When I first started on this I was going show the average of the last bucket, but after playing with it I think it makes more sense to show the last actual value.  So the BGNow name doesn't make sense anymore.

**Comment by PieterGit** [comment]
can't find any regression with one receiver, running for more than two weeks on this branch now

**Pull request merged**
