### PR TITLE
Add MiniMed Connect plugin

### PR DESCRIPTION
**Pull request by mddub**
# MiniMed Connect to Nightscout bridge

**Testers:** This is an experimental feature to bring MiniMed Connect data into Nightscout. Thanks for helping test it! Please follow the steps below to get set up.

**Reviewers:** @bewest has looked over this code, most of which lives in [minimed-connect-to-nightscout]. The biggest open question is what subset of the data to store in Nightscout and in what format (see [this sensor-disabled gist] and [this sensor-enabled gist] for sample data).

## Step 0: Prerequisites

You should already have:
* a MiniMed Connect and compatible pump
* an iPhone running the MiniMed Connect app
* a username and password for CareLink

You should already be able to:
* see real-time values from the Connect (sensor glucose, active insulin, etc.) in the iPhone app
* log into [CareLink] on your web browser using your username and password, go to the CareLink Connect section, and see the same values

If you haven’t achieved the above, read the online help or contact Medtronic support.

## Step 1: Set up Nightscout on Azure

**If you already have a Nightscout site and want to install this plugin to add data from the Connect to it, you MAY skip this step.** Note that this feature contains experimental code, including other new features in development, and there is a chance that your site will be less stable than it was before. You will always have the option to easily revert your Nightscout site to the old, stable version. If you would prefer to create a separate Nightscout site to test this feature while leaving your current Nightscout site as-is, then follow this step to create a new one.

Follow all the steps in the [Nightscout with iOS and Dexcom Share Bridge] setup guide **except step 4**. Set aside a decent amount of time to get through it. We can use this guide because the MiniMed Connect plugin works very similarly to the Dexcom Share Bridge plugin, except instead of reading data sent to Dexcom's servers by the Dexcom Share app, it reads data sent to Medtronic's servers by the MiniMed Connect app.

If you need more help or need to troubleshoot a step of this process, the main [Nightscout setup guide] walks through each of the steps in more detail. Just keep in mind this is an "alternate setup," so ignore any reference to a rig or an Android phone or app.

By the end of this, you should have a GitHub account, a MongoLab account, and an Azure account with a running Nightscout website. You should be able to access your website at https://YOURSITENAME.azurewebsites.net/.

## Step 2: Create a new branch on GitHub

Visit your cgm-remote-monitor fork on GitHub (the one you created in Step 1). It is probably at https://github.com/YOURGITHUBUSERNAME/cgm-remote-monitor. Near the top of the page you should see a button that shows your current branch. It should say "Branch: master". Click on it:

screenshot 2015-10-16 13 48 39

In this dropdown, there is a text box. Type "wip/minimed-connect" in the text box, and then click the option that says "Create branch":

screenshot 2015-10-16 13 52 41

You should see a blue "Branch created" message the top of the screen.

## Step 3: Change your Azure site to use the new branch

Go to your Azure dashboard. On the right side of the page, under "quick glance", click the link "Disconnect from GitHub":

screenshot 2015-10-16 13 58 21

Click "Yes" to confirm at the bottom of the screen. Now, in the same section, the "Disconnect from GitHub" link should be replaced with a "Set up deployment from source control" link. Click that:

screenshot 2015-10-16 14 00 41

Select GitHub. Authorize with GitHub if a window pops up asking you to do so. Select cgm-remote-monitor as the repository, and **for "branch to deploy", type "wip/minimed-connect"**.

screenshot 2015-10-16 14 02 46

Then save and wait for your site to deploy. Visit your site to confirm it's working.

*Note: you can use exactly this same procedure to revert your site to the stable version of Nightscout if you want to stop using the experimental version. Just follow this entire step, and at the end, type "master" for "branch to deploy".*

## Step 4: Enable the MiniMed Connect plugin

**4a.** In your Azure dashboard, go to "Configure", and scroll down to "Connection Strings". (This is the same place you just configured your Mongo database and API_SECRET in step 1.)

**4b.** Add four new connection strings:

* `ENABLE` - the value should be "mmconnect", type should be "Custom"
* `MMCONNECT_USER_NAME` - the value should be the username you use to log in to [CareLink], type should be "Custom"
* `MMCONNECT_PASSWORD` - the value should be the password you use to log in to [CareLink], type should be "Custom"
* `MMCONNECT_STORE_RAW_DATA` - the value should be "true", type should be "Custom". This is a temporary setting while testing this feature. Since we are still finalizing this plugin, we want to store all of the data that CareLink provides in Nightscout so that we can see which parts of the data we can use. For example, we want to see how Medtronic represents trend data (rising slowly, rising quickly, etc.). We anonymize this data so that there’s nothing personally identifiable in it.

Your connection strings section should look like this (sensitive information redacted):

connection-strings

*Note: If this is not your first time setting up Nightscout, there is a possibility that you already have an `ENABLE` connection string. That’s fine. Just add a space and "mmconnect" to the end. For example, if `ENABLE` already had the value "bridge", change it to "bridge mmconnect".*

**4c.** Now is a good time to triple-check the connection strings. Go to the [CareLink] website and log in by copying and pasting the values directly from your Azure dashboard into the login form. Confirm that (a) you are able to log in successfully, and (b) when you go to "CareLink Connect", you can see the real-time values from the Connect.

**4d.** At the bottom of the Azure dashboard, click "Save".

## Step 5: Leave a comment here and wait for a pull request

Leave a comment below so that I know your GitHub username, and then I’ll send you a pull request. This will enable you to pull the code for this feature into your new branch. It is the same procedure as Nightscout uses to help you upgrade your Nightscout install to the latest version.

## Step 6: Accept the pull request

I’ll do my best to respond with the pull request promptly. You’ll receive an email from GitHub to let you know that you have received a pull request from @mddub. Click the link in the email to view the pull request, scroll down, and you should see a section like this:

Click the green "Merge pull request" button, then the green "Confirm merge" button. You should see a purple "Merged" confirmation. Then wait 10-15 minutes and refresh Nightscout. If you are using an Enlite CGM, you should see the values from the MiniMed Connect app on your phone showing up in Nightscout. You should also be able to see data coming from the Connect if you visit https://YOURSITENAME.azurewebsites.net/api/v1/entries.json.

## Step 7: Pay it forward

I need your feedback. If you get it up and running, email me at mark@warkmilson.com with your website address so that I can check how it’s working. You can also leave a comment here to let others know how it's going. If you have trouble with these steps, leave a comment below and I’ll try to help.

[minimed-connect-to-nightscout]: https://github.com/mddub/minimed-connect-to-nightscout
[this sensor-disabled gist]: https://gist.github.com/mddub/b033ec0c800deec02471
[this sensor-enabled gist]: https://gist.github.com/mddub/dc1baf74eda772dcb164
[CareLink]: https://carelink.minimed.com/
[Nightscout with iOS and Dexcom Share Bridge]: http://www.nightscout.info/wiki/welcome/nightscout-with-ios-and-dexcom-share
[Nightscout setup guide]: http://www.nightscout.info/wiki/welcome

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Nice, thanks @mddub, need to recruit some testers for this

**Comment by lcmatoush** [comment]
my github username is lcmatoush

**Comment by mddub** [comment]
Thanks, @lcmatoush! Just sent you a pull request: https://github.com/lcmatoush/cgm-remote-monitor/pull/1

**Comment by lcmatoush** [comment]
I followed the directions and got my Nightscout server up and running. All the instructions seemed pretty straight forward.

It may be worth noting that after step 4 users should expect to see their database grow to about 16.5 MB. I initially took it as a sign that I had everything up and running, overlooking for a little while that it isn't until after step 6 that the server actually retrieves data from carelink.

Would have saved me some time checking and rechecking my connection strings. :)

I'll confirm the linking with my wife's Pebble watch in the morning.

**Comment by NorwoodNightscout** [comment]
Instructions seemed great. I'm reading for a pull request. Thank you! @NorwoodNightscout

**Comment by mddub** [comment]
Thanks, @NorwoodNightscout! Sent you a pull request: https://github.com/NorwoodNightscout/cgm-remote-monitor/pull/1

**Comment by NorwoodNightscout** [comment]
I seem to have done something wrong. I will look at this when I get back home tonight. His sensor ends this evening and we probably will wait to restart until tomorrow afternoon. Thank you!

**Comment by cassmode** [comment]
@cassmode here for github

**Comment by mddub** [comment]
Thanks, @cassmode! Pull request here: https://github.com/cassmode/cgm-remote-monitor/pull/1

**Comment by nsmom** [comment]
I just finished all the steps, I'm ready for a pull request. I can't thank you enough for making this possible!

**Comment by mddub** [comment]
Thanks, @nsmom! Pull request here: https://github.com/nsmom/cgm-remote-monitor/pull/1

**Comment by acerrone** [comment]
Excellent! Pull request please...

**Comment by bewest** [comment]
@acerrone, here's your pull request: https://github.com/acerrone/cgm-remote-monitor/pull/5

**Comment by acerrone** [comment]
Hi Mark,

Thanks so much for this, really looking forward to getting it working.
I think I have everything set properly but not receiving data on the
nightscout page. Screen looks good but no data from the Dexcom CGM
or Medtronic onboard.

https://jacobcgm.azurewebsites.net/#

I did check here and see data!
https://jacobcgm.azurewebsites.net/api/v1/entries.json
jacobcgm

Thanks for all your help and time!!

**Comment by mddub** [comment]
@acerrone excellent, thanks for helping! It looks like the MiniMed Connect data is being uploaded to your Nightscout site fine (although it looks like the most recent upload was from an hour ago). What you see on Nightscout is expected. As I mentioned on Facebook, if you use Medtronic CGM, you'll see CGM data from the Connect in Nightscout, but if you use a Dexcom for CGM and you plan to use Connect only for IOB etc. data, you won't see any Connect data in the Nightscout UI yet, only in the database. We'll work on showing the data in the UI as soon as we've finished this test to make sure we can store it in the database correctly.

The Dexcom CGM data not appearing must mean that your Share bridge is not configured right. I'd double check these instructions again:
http://www.nightscout.info/wiki/welcome/nightscout-with-ios-and-dexcom-share
Double check your bridge login information, and make sure your ENABLE connection string looks something like `bridge connect`. If it's enabled, you'll see `bridge` listed under `enable` in https://jacobcgm.azurewebsites.net/api/v1/status.json.

**Comment by mddub** [comment]
@bewest this is ready to merge. Adding trend data is a little more complex and is better off in a follow up PR.

**Comment by jasoncalabrese** [comment]
cool, 0.8.2 is turning into a really nice release

**Comment by acerrone** [comment]
I'm not sure what the deal was Mark but I started all over again by deleting the Azure site and now its okay. I'm pretty sure we are getting the data into the database for the IOB, ect and I have visual on the CGM data! So sweet, can't wait for the UI deploy.

**Comment by Thebassefamily** [comment]
TheBasseFamily here :) 

I am feeling kind of clueless but am really looking forward to this all being able to merge together.  Pumping Medtronic and Dexcom.  

I am so nervous about screwing this up!! 

Dont want to be without Dexcom ala Nightscout!

**Comment by T1D3903** [comment]
Hi Mark, We have our nightscout site up, but not seeing data from carelink. We'll review the instructions again. Pull request please.  Thank you!

**Comment by mddub** [comment]
@Thebassefamily @T1D3903 This is part of the 0.8.2 release now, so no need to participate in this beta test process. Set up a normal Nightscout site (or make sure your existing site is running your master branch -- see step 3 above) and use the update tool to upgrade your Nightscout site to 0.8.2: http://nightscout.github.io/pages/update-fork/

**Comment by Thebassefamily** [comment]
Will it pull in basal and insulin related info? We are using Dex for sensor and Medtronic for pump....

**Comment by mddub** [comment]
@Thebassefamily for now, if you don't use a Medtronic CGM, you won't see any difference.

It won't pull in basals, because basals aren't pulled in by the MiniMed Connect. Nightscout will be able to see all the same data that you can see in the MiniMed Connect app / CareLink Connect portal. That includes insulin on board and reservoir level, but nothing about basals or timing/amounts of boluses.

We're still working on how to display the IOB and reservoir data in Nightscout. For now they will be in your Nightscout database but not visible anywhere in the UI.

**Comment by Thebassefamily** [comment]
Ok! Thanks!  You guys are amazing. Thank you for all you do!

**Comment by mavster** [comment]
Hi @mddub, I'm ready to roll. Merry Xmas! Cheers, Linda

**Comment by mddub** [comment]
@mavster This beta test has concluded, and this feature is part of Nightscout now. Follow this guide: http://www.nightscout.info/wiki/welcome/website-features/funnel-cake-0-8-features/minimed-connect-and-nightscout

**Comment by mavster** [comment]
Thx @mddub! Have done the pull request. Cheers!

**Comment by fdelpozo** [comment]
My github username is fdelpozo. I use the european carelink portal https://carelink.minimed.eu

**Pull request merged**
