### PR TITLE
Fix Duration input type

### PR DESCRIPTION
**Pull request by unsoluble**
In the Treatment drawer, most number fields are properly set to type=“number”, except the Duration field (for Combo boluses). Fixed that.

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
I think we still want to be able to support mixed input.  We're using a module that can handle input such as "5h", and will be converted to 300 minutes.  I think there was another suggestion that would hint at using numbers and still allow a user to select a alpha keyboard.

**Comment by unsoluble** [comment]
This change doesn’t preclude or restrict mixed input — it merely suggests to the browser which keyboard to present by default. Can still switch to (and enter) alpha.

**Comment by jasoncalabrese** [comment]
I think it's going to vary a lot from browser to browser. With the other number inputs I'm not able to select a different keyboard.

**Comment by unsoluble** [comment]
Oh, okay, that’s interesting. Which browser/OS is that? (I’ve tested on Safari & Chrome on both iOS and Mac.)

**Comment by jasoncalabrese** [comment]
Maybe I'm doing it wrong, but I was trying it with safari on ios

**Comment by unsoluble** [comment]
I just tried it on iOS 6, 7, 10, and 11b, and all presented the full keyboard (with numbers/symbols up first on the type=“number” fields), and could switch to alpha. Not sure what’s happening on your end?

**Comment by unsoluble** [comment]
Right, so: Had a [bunch of people test this](https://www.facebook.com/groups/CGMITCOFFTOPIC/permalink/385349218528769/) on different phones, and it looks like it's Android 7 that does indeed pop the limited numeric keypad that doesn't let you swap back to alpha. So I concede, this tweak would be a regression in that case.

If nobody knows of a way to get the number keyboard to default without locking in it on Android, should probably close this one.

**Pull request closed without merging**
