### PR TITLE
Change formatting in OpenAPS pill

### PR DESCRIPTION
**Pull request by cjo20**
Change the formatting to make it slightly easier to read. New style looks like this:
image

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Just tried this out, with a bunch of rigs the extra lines add up, examples below.  Putting rssi and freq back on the same as the host would help.

screenshot 2016-07-12 22 39 35

vs

screenshot 2016-07-12 22 41 13

**Comment by cjo20** [comment]
image
Any better?

**Comment by jasoncalabrese** [comment]
did you mean to close this?  I haven't had a chance to try it again, but was planning on it

**Comment by cjo20** [comment]
Yeah, since I started closed-looping, I noticed that the "Enacted" stuff wasn't formatting correctly. I'm working on improving that too, then I'll put it up again.

**Pull request closed without merging**
