### PR TITLE
Updated German Translation

### PR DESCRIPTION
**Pull request by herzogmedia**
- added missing translations
- minor changes
- added me to translations list in contribution document

### CODE REVIEW

**Comment by PieterGit** [comment]
@herzogmedia this PR got merge errors because the turkish language was added. Can you resolve these?

**Comment by herzogmedia** [comment]
yeah, sure. I'm on it.

**Comment by herzogmedia** [comment]
should work now

**Comment by herzogmedia** [comment]
@PieterGit done. And sorry about that.

**Comment by herzogmedia** [comment]
corrected error referenced in #4016

**Pull request merged**
