### PR TITLE
Track last fetched sensor values, and attempt to backfill

### PR DESCRIPTION
**Pull request by ps2**

### CODE REVIEW

**Comment by ps2** [comment]
I believe the failing CI build is unrelated to my changes.

**Comment by MilosKozak** [comment]
It's in bridge code:
not ok 62 bridge store entries from share
  TypeError: Cannot read property 'length' of undefined
      at payload (lib/plugins/bridge.js:9:1104)
      at Context.<anonymous> (tests/bridge.test.js:39:32)

**Comment by ps2** [comment]
Ah, thanks for digging that out.  Seems like there are two failures then.  This is the other:

```
not ok 224 reports should produce some html
  AssertionError: expected -1 to be above -1
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value (node_modules/should/cjs/should.js:305:19)
      at afterInit (tests/reports.test.js:269:172)
      at authCallback (lib/client/index.js:9:56254)
      at Object.mockEmit [as emit] (tests/fixtures/headless.js:136:19)
      at lib/client/index.js:9:54851
      at Object.mockOn [as on] (tests/fixtures/headless.js:131:19)
      at Object.load (lib/client/index.js:9:54658)
      at success (lib/client/index.js:9:3181)
      at Object.mockDone [as done] (tests/fixtures/headless.js:64:19)
      at Object.init (lib/client/index.js:9:2992)
      at Context.<anonymous> (tests/reports.test.js:228:12)
      at tests/fixtures/headless.js:150:7
      at Object.module.exports.setup (node_modules/benv/index.js:24:56)
      at Function.init [as setup] (tests/fixtures/headless.js:16:10)
      at Context.<anonymous> (tests/reports.test.js:197:14)
```

**Comment by Chewwy420** [comment]
@ps2 Thanks for this Pete! I merged this code into my Dev build and it works great! Love I don't need to restart site to get it to back fill.

**Pull request merged**
