### PR TITLE
display oref1 UAM purple line

### PR DESCRIPTION
**Pull request by scottleibrand**
Per https://github.com/openaps/oref0/pull/424, the "oref1" features of openaps/oref0 now support unannounced meal predictions and dosing.  This PR displays those predictions in Nightscout (alongside the other three OpenAPS purple line predictions) if a rig is generating them.

### CODE REVIEW

**Comment by alternateal** [comment]
This works well for me 👍

**Comment by Kdisimone** [comment]
working well for me as well

**Comment by tim2000s** [comment]
Works for me 👍

**Comment by PieterGit** [comment]
Works well for me too. Perhaps making UAM line with filled dots will be even better. In most cases I've seen the UAM line is the most reliable BG estimate.

**Comment by scottleibrand** [comment]
We've found that different estimates are more accurate in different situations, so I wouldn't want to visually prefer one over the others (although distinguishing them might be useful in some cases).

Any objections to merging?

**Comment by scottleibrand** [comment]
Closing and reopening to force a new travis build.

**Comment by scottleibrand** [comment]
Looks like the failure is:

not ok 224 reports should produce some html
  AssertionError: expected -1 to be above -1
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value (node_modules/should/cjs/should.js:305:19)
      at afterInit (tests/reports.test.js:269:172)
      at authCallback (lib/client/index.js:9:56254)
      at Object.mockEmit [as emit] (tests/fixtures/headless.js:136:19)
      at lib/client/index.js:9:54851
      at Object.mockOn [as on] (tests/fixtures/headless.js:131:19)
      at Object.load (lib/client/index.js:9:54658)
      at success (lib/client/index.js:9:3181)
      at Object.mockDone [as done] (tests/fixtures/headless.js:64:19)
      at Object.init (lib/client/index.js:9:2992)
      at Context.<anonymous> (tests/reports.test.js:228:12)
      at tests/fixtures/headless.js:150:7
      at Object.module.exports.setup (node_modules/benv/index.js:24:56)
      at Function.init [as setup] (tests/fixtures/headless.js:16:10)
      at Context.<anonymous> (tests/reports.test.js:197:14)

Looks like that same failure is occurring on all other PRs as well, so it must've been caused by a recently merged commit, not anything we're doing here.

**Pull request merged**
