### PR TITLE
Workaround for re-loading bug in profile editor: don't show profile form during save

### PR DESCRIPTION
**Pull request by DigitalDan1**
This fixes a problem I noticed in the profile editor where it re-loads and re-draws every time there's an update from the server (due to socket.io emit calling the callback).

This was causing issues where the user could be making changes to their profile, then the data would re-load and re-draw, so they'd lose their changes and have to start again.

It was also causing the save button's event to be hooked up multiple times, which meant saving was taking longer and longer, and made it more likely that any further changes made by the user were lost.  Users would have seen the user interface update whilst editing, replacing their values with a previous version (from whichever save came back last).  This change (crudely) hides the form whilst the save is happening to make sure the user doesn't carry on making changes that will be lost when the re-draw happens.

This _should_ fix https://github.com/nightscout/cgm-remote-monitor/issues/4056.

### CODE REVIEW

**Comment by sulkaharo** [comment]
So hey - I've never seen this behavior, so I'm wondering what the root cause for the reload is? Or at least - in our instance, I can edit the profiles and the page doesn't reload and I've never lost edits. Which browser are you testing on?

**Comment by DigitalDan1** [comment]
Hey @sulkaharo, I've seen this on Windows 10 Chrome and Edge, and iPhone XS Max safari.  When it happens there are regular "Client connected to server" logs in the console.  I think it's more likely to happen when there's a lot of data being transferred, maybe a timeout is causing socket IO to reconnect?

Basically the 'connect' event is fired on the initial connection _and_ any subsequent re-connection, so there's always a chance the callback could be called more than once.

It's easy enough to reproduce: just switch your network connection off then on again.

**Comment by PieterGit** [comment]
@DigitalDan1 thanks for this PR.
I was able to reproduce the fact that `socket.io` updates can revert changes to the profile. 
I would classify hiding screen elements as a workaround and we should fix the root cause of this problem with Nightscout 0.12. I created https://github.com/nightscout/cgm-remote-monitor/issues/4252 for that.

Since this issue can cause problems for users I applied this, so that we can include it in Nightscout 0.11.

**Comment by DigitalDan1** [comment]
@PieterGit, sounds good, thanks.

Just want to capture a few comments here for anyone (including me) that may come back to work on a more elegant fix.

I agree the route cause should be fixed, but also think every page should gracefully handle a socket IO reconnect (I’m pretty sure the admin page has the same issue).

Hiding screen elements addresses a different problem; if the save takes a long time the user can carry on making changes that are lost when the save actually finishes. I’d usually show a dialog (like a Bootstrap Modal) whilst waiting for the save to return. Hiding the form is crude, but does the job for now.

**Pull request merged**
