### PR TITLE
Upgrade mongodb to 1.4.29

### PR DESCRIPTION
**Pull request by dduugg**
resolves https://github.com/nightscout/cgm-remote-monitor/issues/657

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Dev is at 2.0.34, but this would be a smaller change for a hot fix

**Comment by dduugg** [comment]
gah, meant to target dev. i leave it to your discretion if a hotfix is merited.

**Comment by jasoncalabrese** [comment]
wouldn't make sense to target dev with this, since we should be at a much more current version.  I'll ask around and see if there are other reports of this, but sounds like there will be more and that we should take care of it now.

**Comment by dduugg** [comment]
right. i meant your discretion in merging or closing this PR. i'm not advocating downgrading :smile:

**Comment by stavlor** [comment]
My guess is this isn't affecting dev will try a master deployment though but my dev has been running without issues on MongoLab will test in master

**Comment by jasoncalabrese** [comment]
This is currently only an issue with the experimental sandboxes that were upgraded to 3.0.  We need to get a patch release out before the normal sandbox upgrade cycle starts.

You'd need to select experimental when creating the sandbox

screen shot 2015-06-26 at 2 04 30 pm

screen shot 2015-06-26 at 2 04 36 pm

blob

**Comment by jasoncalabrese** [comment]
Based on some testing done by @stavlor it looks like by doing a re-deploy or a fresh deploy of master will pull in newer versions of the mongo module so we probably don't need to do a hotfix for this

**Comment by dduugg** [comment]
sg! closing out.

**Pull request closed without merging**
