### PR TITLE
prepare release 14.2.6, development area post 14.2.5 release

### PR DESCRIPTION
**Pull request by bewest**
There are several features in dev branch needed for expected operation.

* Data rights management - Obscuring the data source restores interoperability among data brokers choosing to discriminate. This has been in production use at T1Pal for 6 months.
* Next version of Loop (likely 3.0.0) - Verified @ps2 - required for Loop 3.0 remote real-time sharing features.
* Eliminate crash/NPE for AndroidAPS 3.*.* Verified @MilosKozak, @samihusseingit - required for 14.2.4+ compatibility with AAPS 3.0.
* Proper and formal support for LTS Node versions. (We are delaying removing support for older Node until the next version to create an easier upgrade pathway for some users.)

### CODE REVIEW

**Comment by bewest** [comment]
There are several features in dev branch needed for expected operation.
* Data rights management - Obscuring the data source restores interoperability among data brokers choosing to discriminate.  This has been in production use at T1Pal for 6 months.
* @ps2 - Will these changes be required for Loop 3.0 remote real-time sharing features?
* @MilosKozak, @samihusseingit - These changes are required for 14.2.4+ compatibility with AAPS 3.0.

Should we consider bumping the version to something other than 14.2.6?
In addition, I'd like to adopt https://www.npmjs.com/package/express-slow-down to replace the delay feature currently implemented order to handle the valid case where browsers send multiple concurrent requests.  The default delay breaks when behind a Nightscout-aware identity and access management router such as https://github.com/t1pal/nightscout-roles-gateway.

**Comment by bewest** [comment]
Here's an attempt at implementing `express-slow-down`: https://github.com/nightscout/cgm-remote-monitor/pull/7469

**Comment by ps2** [comment]
@bewest Yes, Loop 3.0 will require these features.

**Comment by ps2** [comment]
Actually, testing the dev branch again, I notice a significant bug, and filed a PR to fix it here: https://github.com/nightscout/cgm-remote-monitor/pull/7488

**Comment by bewest** [comment]
@sulkaharo Let's release this as `14.2.6`, the subsequent version will then target `15.0.0`.
https://github.com/nightscout/cgm-remote-monitor/pull/7514

**Pull request merged**
