### PR TITLE
feat: Override mode plugin

### PR DESCRIPTION
**Pull request by jasoncalabrese**
image

This is a simple plugin that displays a pill with any overrides.  To test add `override` to the `ENABLE` setting and show the plugin from the client.

### CODE REVIEW

**Comment by Kdisimone** [comment]
This is great stuff! very helpful!!

**Comment by Kdisimone** [comment]
tested this with a couple different Loop builds, and both MDT and Pod pumps, works great. With or without the override enabled in Heroku settings. seems smooth. Thanks!

**Comment by PieterGit** [comment]
@jasoncalabrese LGTM. Can you add it in the `README` as well. Please let me know if it's ready to merge.

**Comment by sulkaharo** [comment]
Hmm, wonder what's happened to the automated builds - the Loop plugin test broke here

**Pull request merged**
