### PR TITLE
Merge pull request #1 from nightscout/master

### PR DESCRIPTION
**Pull request by fanni-nightscout**
fanni-nightscout

### CODE REVIEW

**Comment by fanni-nightscout** [comment]
Paivitys

**Comment by fanni-nightscout** [comment]
Testi

**Comment by sulkaharo** [comment]
Hi! Oops - it seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Don't worry, no harm done! Please try using the Nightscout update tool again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings. We'll close this pull request, as it's now in the Nightscout repository instead of the intended your personal copy.

**Comment by fanni-nightscout** [comment]
Kiitos ilmoituksesta.

Pahoittelen sekoiluani.

Sain tehtyä päivityksen (14.0.6) toisella tavalla.


-Kari



su 18.10.2020 klo 20.55 Sulka Haro <notifications@github.com> kirjoitti:

**Pull request closed without merging**
