### PR TITLE
Update Nightscout version

### PR DESCRIPTION
**Pull request by fbrunstein**

### CODE REVIEW

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by fbrunstein** [comment]
I used the page where I can fill in my name and then it displas if I need an update or everything is fine (then a star appears). Thats the page that is described in the guideline to update. I think what I could have made wrong is that I pulled a request first and then I created a request. Before pulling a request the other option was not available.. Can you help me out or do you need more information?

**Comment by unsoluble** [comment]
Okay, that's interesting, thanks. When you run through the update tool like that, it _should_ create the Pull Request for you, which you then confim by hitting the green "Create Pull Request" button. If you're starting the PR manually, it'll be created "backwards", which is how we ended up here.

You could try using the update tool again, see if it takes you to a place where you can just hit that one button to finalize the PR — that'll be the easiest way forward. If that doesn't work, I can walk you through creating it manually.

**Comment by fbrunstein** [comment]
Thanks for the very fast and accurate help!!
I started the tool again but now I directly see the star as if I already updated succesfully. I would be pleased if you could wrote me some hints on how I can do it now manually

**Comment by unsoluble-test** [comment]
It actually looks like you successfully did the update in the right direction — just I guess _also_ managed to make this other PR. I think you're good to go, assuming your site is working okay at this point.

**Comment by fbrunstein** [comment]
Ok, but I could not press the Merge button. That one is locked due to the missing review..

**Comment by unsoluble** [comment]
Yeah, you won't be able to merge this one; it's attempting to push changes up into the original fork, which you're not allowed to do. You can close this one.

**Comment by fbrunstein** [comment]
Ok, but how can I then use.the new version of Nightscout? Do I only have to deploy it or do I have to try it another way?

**Comment by unsoluble** [comment]
If you don't have automatic deploys enabled on your Heroku site, you'll need to manually deploy each time you do an update. From your Heroku dashboard, go to your app's Deploy page, connect it to GitHub if you haven't already, connect your cgm-remote-monitor repo if it isn't already, then manually deploy the `master` branch at the bottom of that page.

**Pull request closed without merging**
