### PR TITLE
German language update

### PR DESCRIPTION
**Pull request by CHR15714N**

### CODE REVIEW

**Comment by PieterGit** [comment]
@CHR15714N Please use `dev` branch version for language updates. Please change branch or retarget with a new PR.

**Comment by CHR15714N** [comment]
Sorry, I just wanted to modify my version. Did I modify the general one?
I only use Github for nightscout and I am no Developer so sorry for my ignorance...

**Comment by PieterGit** [comment]
@CHR15714N You didn't modify anything, you proposed a change, but others have made translations in the same file. Please check https://openaps.readthedocs.io/en/latest/docs/Resources/my-first-pr.html and use the `dev` branch. Please retry with another PR and close this PR when your done. If you need help hop on https://gitter.im/nightscout/public

**Comment by MilosKozak** [comment]
simply change base is not possible now. closing. please reopen for dev branch if needed

**Pull request closed without merging**
