### PR TITLE
Upgrade to 0.10.3

### PR DESCRIPTION
**Pull request by Alamo04**

### CODE REVIEW

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by sulkaharo** [comment]
Hi! This PR was made to the "wrong direction", as in "to Nightscout from your fork", instead the wanted "from Nightscout to your fork". Closing this so the team can see the development-related PRs easier (but please come and comment to the question above).

**Comment by Alamo04** [comment]
Hi unsoluble,
sorry, was a long week on work.

You have to activate the careportal in the settings of your NightScout page. 
After that you have an icon at the top (right), where also the settings-, alarm- and edit icon is shown.

Sorry for my bad english, think thats my problem to do the right way to upgrade to the actual version.

**Comment by Alamo04** [comment]
unsoluble
I use this guide:
http://www.nightscout.info/wiki/welcome/how-to-update-to-latest-cgm-remote-monitor-aka-cookie

**Comment by unsoluble** [comment]
Gotcha, thanks. Next time, just make sure you're logged into GitHub _before_ clicking through the update process — will avoid creating the extra pull request.

**Comment by Alamo04** [comment]
Got it, finaly the site was updated. :)
Many thanks all.

**Comment by Alamo04** [comment]
OK, now it works.

After merging I must make a new deploy and then the version was updated.

puhhh. I'm happy now. :)

**Pull request closed without merging**
