### PR TITLE
Second update 2/13/19

### PR DESCRIPTION
**Pull request by kosherrunner**

### CODE REVIEW

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by kosherrunner** [comment]
It was my fault I didn’t update Azure before the pull. Azure is now updated

**Comment by unsoluble** [comment]
But when you actually created the PR — did you use the [update tool](http://nightscout.github.io/pages/update-fork/), or did you create the PR manually?

**Comment by kosherrunner** [comment]
I used the update tool, I followed the instructions on the Nightscout site

**Comment by unsoluble** [comment]
Interesting, thanks. In the future, just do a quick double-check of the direction the PR is facing — you want to have your own repository on the left (the "base"), and the nightscout repo on the right (the "head").

**Comment by sulkaharo** [comment]
Hi! This PR was made to the "wrong direction", as in "to Nightscout from your fork", instead the wanted "from Nightscout to your fork". Please retry. :)

**Pull request closed without merging**
