### PR TITLE
Log error on device status insert & don't crash

### PR DESCRIPTION
**Pull request by sulkaharo**
(Don't merge yet!)

### CODE REVIEW

**Comment by sulkaharo** [comment]
Is there a good way to surface this to users?

**Comment by jasoncalabrese** [comment]
I think we should still return a 500 so the client deal with it.  Is this mostly for device status? I was wondering it we should rename the old collection on startup if it's too big, then start using a new collection and ignore the old.

**Comment by sulkaharo** [comment]
At least for mLab, looks like all inserts to all collections start failing at the same time, so it’s not specific to the device status collection, other than it being the collection that seems to get the most data.

**Comment by sulkaharo** [comment]
@jasoncalabrese so, instead of just returning, throw the error?

**Comment by PieterGit** [comment]
@jasoncalabrese @sulkaharo 
I think logging  an error for 0.10.3 in the console is better than crashing Heroku. We can do the 500 server error stuff in 0.11. Thoughts?

**Comment by jasoncalabrese** [comment]
What's the behavior when the db is full "crashing heroku" sounds extreme...

I think to return a 500, we just need to call the callback passing an error something like `fn(new Error('insert failed'), null)` instead of the `fn(null, doc.ops)` that gets call on success

**Comment by PieterGit** [comment]
@jpcunningh I don't mind if we PR this with this PR or with https://github.com/nightscout/cgm-remote-monitor/pull/3989 . I assume @jasoncalabrese and @sulkaharo are quite busy at this moment, because I haven't seen them a lot the last few weeks.  I will accept any tested PR that will log an error and return 500 to the client 😄

**Comment by jpcunningh** [comment]
@PieterGit, I created a new PR #4004 that returns 500 to the client.

**Comment by PieterGit** [comment]
Merged https://github.com/nightscout/cgm-remote-monitor/pull/4004 instead. Closing this PR

**Pull request closed without merging**
