### PR TITLE
French Update from 6463 to 7533

### PR DESCRIPTION
**Pull request by Loxam61**

### CODE REVIEW

**Comment by sulkaharo** [comment]
Can you double-check if this PR is needed? There was another update to French by @lsandini, which I believe also touched the same parts

**Comment by PieterGit** [comment]
@Loxam61 or @lsandini can you check if this PR is still needed?

**Comment by Loxam61** [comment]
Hi, not needed. Seems translation had been done entirely.

On Feb 18, 2018 07:12, PieterGit <notifications@github.com> wrote:

@Loxam61<https://github.com/loxam61> or @lsandini<https://github.com/lsandini> can you check if this PR is still needed?

**Comment by PieterGit** [comment]
Closing pull request without merging as @Loxam61 suggests. Thanks.

**Pull request closed without merging**
