### PR TITLE
Rewording of the "wrong profile" dialog

### PR DESCRIPTION
**Pull request by unsoluble**
This dialog as originally worded often confuses/worries people when it pops on fresh installs. Reworded to be clearer about what's happening.

### CODE REVIEW

**Comment by unsoluble** [comment]
Screen Shot 2019-07-31 at 10 55 42 AM

**Comment by sulkaharo** [comment]
@unsoluble Can you also remove the old text from language.js and update this in?

**Comment by unsoluble** [comment]
Ah right, will do.

**Comment by unsoluble** [comment]
Done. How do we flag that passage as needing tweaks in the translated languages?

**Pull request merged**
