### PR TITLE
update

### PR DESCRIPTION
**Pull request by obok7777**
update

### CODE REVIEW

**Comment by obok7777** [comment]
update

**Comment by obok7777** [comment]
update

**Comment by obok7777** [comment]
update

**Comment by sulkaharo** [comment]
Hi! It seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Please try again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings.

**Comment by Lukevos** [comment]
Thanks, just realized that lol. Been sitting here trying to figure it what I did wrong. My website is still on 0.8.5 lmao. Time for an update!

**Pull request closed without merging**
