### PR TITLE
Token/Role based access controls

### PR DESCRIPTION
**Pull request by jasoncalabrese**
create some `Subject`s

```
curl -H 'Content-Type: application/json' -H "api-secret: $SECRET" -X POST 'http://localhost:1337/api/v2/authorization/subjects' -d '{
  "name": "Phone",
  "roles": ["admin"]
}'

curl -H 'Content-Type: application/json' -H "api-secret: $SECRET" -X POST 'http://localhost:1337/api/v2/authorization/subjects' -d '{
  "name": "Health Office",
  "roles": ["careportal"]
}'

```

list `Subject`s
```
curl -H "api-secret: $SECRET" http://localhost:1337/api/v2/authorization/subjects
```
or
```
curl http://localhost:1337/api/v2/authorization/subjects?secret=$SECRET
```

create authorization tokens from access tokens

```
curl 'http://localhost:1337/api/v2/authorization/request/mac-mdYvgKOTce'
```

result will be something like: 
```
{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NUb2tlbiI6Im1vbXBob25lLXdvS3NtUkdLUUIiLCJpYXQiOjE0NzAxMTgxNjUsImV4cCI6MTQ3MDEyMTc2NX0.NBynYhHTK2BUaP5a0_pIcLcHk8J7eE0T-IGoVCg8FDM","sub":"Mac","permissions":["*"],"iat":1470118165,"exp":1470121765}
```

decode and verify (debug endpoint)
```
curl \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NUb2tlbiI6Im1vbXBob25lLXdvS3NtUkdLUUIiLCJpYXQiOjE0NzAxMTgxNjUsImV4cCI6MTQ3MDEyMTc2NX0.NBynYhHTK2BUaP5a0_pIcLcHk8J7eE0T-IGoVCg8FDM'\
  -X GET 'http://localhost:1337/api/v2/authorization/debug/check/data:treatments:create'

```

result will be 200 or 401, with decoded logged on the server console

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
screenshot 2016-08-02 22 26 03

**Comment by bewest** [comment]
Willing to help test/develop.  Wasn't quite clear on what creation needs, but was getting oriented to the plugin stuff at same time.

**Comment by jasoncalabrese** [comment]
Some of the next steps are to add a PUT `authorization/subjects/:_id` and update storage function, add crud storage and api for roles to replace hardcoded roles, checking permissions on client to enable/hide things, hook up edit subject dialog to put/post.

**Comment by jasoncalabrese** [comment]
Admin UI can now create, edit, and delete Subjects, need to do the same for roles

**Comment by jasoncalabrese** [comment]
admin UI working for roles

screenshot 2016-08-04 01 06 52

**Comment by jasoncalabrese** [comment]
api-secret based login now working, maybe also ask for a token and do a redirect

screenshot 2016-08-06 01 26 36

**Comment by jasoncalabrese** [comment]
@MilosKozak I got this hooked up to the websocket api, I think it covers almost all the uses I can think of.  Could use more review and testing.

**Comment by jasoncalabrese** [comment]
nice, I like the headless fixture

**Comment by jasoncalabrese** [comment]
There's still some issues when loading with `AUTH_DEFAULT_ROLES=denied`, such as not knowing what plugins are enabled.  We'll need to load settings again after auth, that will be needed later anyway since I want to be able to have custom settings for each subject.

**Pull request merged**
