### PR TITLE
context range fix

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Fixes a bug reported by @sulkaharo

### CODE REVIEW

**Comment by jimsiff** [comment]
:+1: Fixed it for me.

**Comment by francescaneri** [comment]
image
Hi Jason , if it were so for the parts in red and yellow ?

**Comment by francescaneri** [comment]
img_1699 1
...so as regards the vertical is possible to divide it in this way?

**Comment by francescaneri** [comment]
img_0448 1
.. so, you can align them?

**Pull request merged**
