### PR TITLE
update nightscout

### PR DESCRIPTION
**Pull request by Air69**
update nightscout

### CODE REVIEW

**Comment by Air69** [comment]
update nightscout

**Comment by Air69** [comment]
update nightscout

**Comment by unsoluble** [comment]
Check your merge direction when setting up the PR — your repo needs to be on the left/base side.

**Comment by sulkaharo** [comment]
Hi! It seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Please try again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings.

**Pull request closed without merging**
