### PR TITLE
update language.js

### PR DESCRIPTION
**Pull request by apanasef**
update Russian translation

### CODE REVIEW

**Comment by sulkaharo** [comment]
Looks good, thanks!

**Comment by apanasef** [comment]
Thanks Silks Haro


24 авг. 2017 г. 17:38 пользователь "Sulka Haro" <notifications@github.com>
написал:

**Comment by apanasef** [comment]
Auto corrected sorry Silka :)

24 авг. 2017 г. 5:38 PM пользователь "Sulka Haro" <notifications@github.com>
написал:

Looks good, thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nightscout/cgm-remote-monitor/pull/2762#issuecomment-324654854>,
or mute the thread

**Comment by apanasef** [comment]
Unbelievable - it keeps correcting your name

24 авг. 2017 г. 5:41 PM пользователь "Fedor Apanasenko" <apanasef@gmail.com>
написал:

**Pull request merged**
