### PR TITLE
upgrade minimed-connect-to-nightscout to fix GuardianConnect for US servers (and update npm dependencies)

### PR DESCRIPTION
**Pull request by PieterGit**
needs to be tested by minimed-connect-to-nightscout  users for EU and US Medtronic servers
this fix GuardianConnect for US servers by upgrading minimed-connect-to-nightscout 

Also the Nightscout dependencies are upgraded, to fix a Nightscout security issue, so this PR must be tested more broadly,

### CODE REVIEW

**Comment by PieterGit** [comment]
Can minimed users test this for EU and US Medtronic servers and confirm it works?
Merging to Nightscout is blocked because of https://github.com/mddub/minimed-connect-to-nightscout/issues/14

**Comment by unsoluble** [comment]
For what it's worth, I don't know if there's a single mmconnect user out there who will know how to deploy from a PR (aside from perhaps @szymjaw, who has already tested this).

**Comment by PieterGit** [comment]
@unsoluble As a service, also pushed as `wip/mmconnect_us` branch, see
https://github.com/nightscout/cgm-remote-monitor/tree/wip/mmconnect_us

Please test this branch and confirm it works for US and EU users. I upgraded Nightscout dependencies in this PR as well because there was a small security issue that needed to be fixed.

**Comment by unsoluble** [comment]
Ah nice, that'll help. I'll pass it on to the folks I know of who use this.

**Comment by PieterGit** [comment]
@unsoluble or @szymjaw . Upgraded the `wip/mmconnect_us` branch and this PR to include `minimed-connect-to-nightscout` version 1.3.1. This has no known security issues (thanks @mddub for the quick fix). 

@unsoluble or @szymjaw Can you make sure we get positive test reports from EU and US users who use `minimed-connect-to-nightscout?  I can't test this (except that it won't have regressions for non `minimed-connect-to-nightscout` users).

**Comment by PieterGit** [comment]
Success of this PR has been reported by 
@unsoluble https://gitter.im/nightscout/public?at=5d601069a498b6723782bf0a
@szymjaw reports succes: https://gitter.im/nightscout/public?at=5d6016b049ac0519239b0c7c and https://github.com/nightscout/cgm-remote-monitor/issues/4753#issuecomment-524381292
@flutelynne_twitter reports succes: https://gitter.im/nightscout/public?at=5d6030944b1189084e514532

Merging to dev

**Pull request merged**
