### PR TITLE
Added indexes to 'entries' and 'treatments' along with other updates

### PR DESCRIPTION
**Pull request by a-harrison**
Hi, 

I'm a database administrator from mLab. I wanted to share some of the index recommendations we've been making for Nightscout users. These recommendations use the equality->sort->range  methodology described here:
https://docs.mlab.com/indexing/#sorting-efficiently

Specifically: 

* treatments - { "key600" : 1, "created_at" : 1}
* treatments - { "eventType" : 1, "duration" : 1, "created_at" : 1 }
* entries - { "type" : 1, "date" : -1, "dateString" : 1 }
* entries - { "key600" : 1, "type" : 1, "date" : -1, "dateString" : 1 }

I also made a few minor updates elsewhere, such as specifying `createIndex` instead of `ensureIndex` and adding some fixes to `testing/populate.js`.

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4828956&bid=16045193)

**Comment by sulkaharo** [comment]
Wow, great! The Mongo documentation says ensureIndex() is now a synonym of createIndex() - is this change purely cosmetic or is there something else happening here?

**Comment by a-harrison** [comment]
Pretty much just cosmetic, but it should also protect against any issues if a future version of the driver were to remove the alias.

**Comment by a-harrison** [comment]
Looks like there was an issue; I'll fix and re-submit. Is there a preference on the `ensureIndex` vs  `createIndex` thing?

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 9
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4828956&bid=16045193)

**Comment by a-harrison** [comment]
Checks are now passing. 

Let me know if you'd like me to address the things mentioned in the Codacy report. I haven't taken action yet because the recommendations seem to conflict with the style guide ('Strings must use double quote' vs. 'Only use single quotes'). 

Please let us know if there is anything else I should do. 

Best regards

**Comment by sulkaharo** [comment]
Hi! Changed Codacy config to require single quotes - I just recently re-enabled the scans fully and the config still needs tuning. Apologies for that. If ensureIndex and createIndex are synonyms and former is deprecated, sounds like we should go with createIndex

**Comment by sulkaharo** [comment]
Just to confirm what's the best action for the key600 index (which is a field we don't really support), can you post what the queries in your end look like? I think I know what's issuing those queries and can probably get those removed without having to add another index

**Comment by a-harrison** [comment]
> If ensureIndex and createIndex are synonyms and former is deprecated, sounds like we should go with createIndex

Great. The PR should still be using `createIndexes` for the driver function call. This is still [wrapped in a function named 'ensureIndexes'](https://github.com/nightscout/cgm-remote-monitor/blob/f57ccb8ed4a5ab098e63432e64303a6f77857163/lib/storage/mongo-storage.js#L66), which I avoided changing to minimize the chances of breaking something.

Regarding `key600`, we were seeing queries similar the following: 

```
db.entries.find({
  "date" : { "$gte" : ... }, 
  "key600" : "somevalue",
  "type" : ..., 
}).sort({ "date" : -1 })

db.treatments.find({
  "created_at" : { "$gte" : ... },
  "key600" : "somevalue"
}).sort({ "created_at" : -1 })
```

I wasn't able to find any references to `key600` in the repo, but I did see [this](https://gitter.im/nightscout/public/archives/2018/07/18) old conversation.

**Comment by sulkaharo** [comment]
Couple additional notes - I'm actually talking with the devs of the software that's making the key600 queries and we're looking into whether it'd be possible to restructure the queries to not use the variable at all and constrain the queries in Nightscout to only allow indexed fields. Related - @a-harrison do you have any estimate how much load the the current indexes cause on data inserts? Based on experience with other databases, index updates can be quite costly and we already have a ton of indexes in place, so I'm wondering where we're at with the balance of compute cost of making inserts even heavier vs speeding up queries?

**Comment by a-harrison** [comment]
Sorry the delay.

> do you have any estimate how much load the the current indexes cause on data inserts?

Indexes do slow down the speed of inserts and updates but they allow queries to run significantly more efficiently. While it is possible to over-index, the impact of unindexed queries on both reads and writes is almost always more detrimental than having too many indexes.

Generally speaking, we haven't seen any issues arising from the write activity of a Nightscout app; the most frequent performance issues we see are associated with the load from unindexed reads.

**Comment by sulkaharo** [comment]
Ok discussed this with the devs - can you remove the key600 index from here? We're looking into whitelisting the indexed fields for the queries and would prefer to not index fields that aren't "officially" part of the Nightscout data model.

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4828956&bid=16045193)

**Comment by a-harrison** [comment]
Pull request should now be updated to remove the indexes referencing `key600`.

**Pull request merged**
