### PR TITLE
feat: disable pump battery alarms at night option

### PR DESCRIPTION
**Pull request by jpcunningh**
This does not change behavior unless the new `PUMP_WARN_BATT_QUIET_NIGHT` option is enabled.

If `PUMP_WARN_BATT_QUIET_NIGHT` is enabled, the pump battery alarms will be suppressed outside of the `DAY_START` and `DAY_END` times.

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/plugins/pump.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4726178&bid=15777485)

**Comment by jpcunningh** [comment]
The server side isn't working, yet, due to lack of timezone handling on the server side.

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/plugins/pump.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4726178&bid=15777485)

**Comment by jpcunningh** [comment]
The time zones are being handled correctly now.

**Comment by sulkaharo** [comment]
I agree with the sentiment that alarms during the night are irritating, but doesn't this option make the system less safe?

**Comment by jpcunningh** [comment]
I had a couple of thoughts on that question:

1.  The pump battery warning threshold recommended in the setup instructions provides about 8 hours of usable pump battery life warning to the user; however, the first part of the pump to fail is the radio communications. The pump will continue to deliver insulin for several more hours. The pump will continue to work until the next morning when the alarms are re-enabled.
2. After the pump radio communications fail, urgent warnings will be generated for the pump data age and if using an APS additional urgent warnings will be generated for being unable to complete the loop.

In either scenario, I don't believe the system safety is degraded, but the user will generally have fewer nights interrupted by alarms by delaying the pump battery alarm until normal waking hours.  If the pump battery fails faster than expected, other alarms will be generated to wake the user up.

**Comment by sulkaharo** [comment]
The amount of time left after warning depends on the battery type. With lithium batteries, the battery can deplete fully in less than 2 hours after the initial alarm, depending of course on how the voltages are set.

**Pull request merged**
