### PR TITLE
WIP: Other Keys

### PR DESCRIPTION
**Pull request by jasoncalabrese**
@MilosKozak an idea for a different way to handle multiple keys without the magic single letter permission you were looking at.

For example:
`OTHER_KEYS="school family"`
`OTHER_KEYS_SCHOOL="careportal"`
`OTHER_KEYS_FAMILY="careportal edit"`

Will create a mapping like this:

```javascript
{
  careportal: [
    '655f83be7512e5b5b3ba4c9976c043ece4b3ce51'
    , 'c33f059b0ca7725fbfd6c9ea4f2f012cc7ac5a74' 
  ]
  , edit: [
    'c33f059b0ca7725fbfd6c9ea4f2f012cc7ac5a74'
  ] 
}
```

### CODE REVIEW

**Comment by MilosKozak** [comment]
will think about impact and implementation ...
does it mean we keep the config in env? setting of rights could be clickable in some config editor ...

**Comment by jasoncalabrese** [comment]
I was thinking about an editor, if we do that we'd need a new collection, etc, it would be nice.  Also with this we'd never send unhashed over the network.  With an editor we'd need to keep the unhashed keys.

I'm thinking that at some point we'll want special permissions for a specific plugins features.

**Comment by MilosKozak** [comment]
well if you think the rights could became even more complicated it wouldn't continue on env ... it's even harder to maintain anyway.
storing unhashed secret in mongo is not necessary. it would not be only possible to see secret. just reset to another

**Comment by jasoncalabrese** [comment]
Maybe a display label and key, and not allow them to match

**Comment by MilosKozak** [comment]
yeah with editor it can be easy username + password

**Comment by jasoncalabrese** [comment]
The computer in the health office at my son's school clears local storage and cookies every night, think I'll need to be able to have a token as a url param.

**Pull request closed without merging**
