### PR TITLE
Dreamsicle (Release 0.6.0)

### PR DESCRIPTION
**Pull request by jasoncalabrese**
### Custom BG Thresholds and Alarm Settings

c142d12a-87dd-11e4-8e67-b858ec2f3f55

### BG Delta like the Pebble
screen shot 2015-01-12 at 12 29 20 am

### New Care Portal treatment rendering
8414e9c8-89ea-11e4-8017-414740ed4558

### Care Portal backdating and pre-bolus support
screen shot 2015-01-12 at 12 32 32 am

### Hover Tooltips for all dots in the context view (SGVs, MBGs, treatments)
screen shot 2015-01-12 at 12 40 45 am

screen shot 2015-01-12 at 12 42 14 am

## Bug Fixes

  * Auto Acking - alarms will be auto canceled when the condition causing the alarm isn't present
  * Fading trend line - after a period of time the trend line would fade in the middle the the prediction cone would not display

10866128_10153079387666458_1990945968238773741_o

### CODE REVIEW

**Comment by jimsiff** [comment]
+1.  I say ship it.

**Comment by oamyoamy** [comment]
+1

**Comment by ELUTE** [comment]
+1

**Comment by denvergail** [comment]
_1

**Comment by oamyoamy** [comment]
Confirming.
ac

**Comment by audiefile** [comment]
+1

**Comment by GrantKY** [comment]
+1

**Comment by bewest** [comment]
Also, setting `DISPLAY_UNITS=mmol` now causes clock mode to respect mmol.

**Comment by bewest** [comment]
:+1: , would still prefer setting type of alarm as class on some element somewhere, and customizing labels.

**Pull request merged**
