### PR TITLE
daytoday reports are always in the profile's time zone

### PR DESCRIPTION
**Pull request by bewest**
Midnight for the profile should always be at the start of the day (midnight) for the chart.  There's logic for this in `lib/report/reportclient.js`, but believe it needs to be here as well.

### CODE REVIEW

**Comment by marionbarker** [comment]
Been a little busy with Loop 3 docs. I appreciate this and I will try it soon.

**Comment by bewest** [comment]
Thanks for the updates!
https://github.com/nightscout/cgm-remote-monitor/issues/4901#issuecomment-1386536027

I expected there to be a kind of "off by one" error, so the right column second row actually makes sense to me.  This is progress.

As for the date being wrong, can you be a bit more explicit.  There seems to be a date rollover effect with respect to midnight.  Did you pull up these reports at a time when the -2, +3 would have resulting in rolling over midnight?  Is the date correct in the other timezone for one of those cases?  We're close.  If possible, I'd like to peek at your NS instance to poke at it, we can discuss that in a private channel.

**Comment by bewest** [comment]
Tests do not pass, but I suspect it's something with the tests themselves.  This is worth trying, as it should handle both remaining issues:
* title of the day is incorrect (always the previous day?)
* midnight wrapping around to next day when crossing the datetime line.

**Comment by sulkaharo** [comment]
Yea if you've changed the date logic, it's likely the report outputs different values. Check reports.test.js starting line 273

**Comment by marionbarker** [comment]
I tried the changes through 8764b84 alone and with 7833 patched into master. Did not fix the problem.
I'm installing straight dev now. When I have time, I'll try the patches for dev.

**Comment by bewest** [comment]
Strange tests... on my machine, many tests fail (careportal, hashauth) because loading the html into `self.$('body').html(indexHTML)` in `tests/fixtures/headless.js` takes more than 60 seconds allowed by the test.  If I adjust it to 65 seconds some tests work, but I still get an error in "hashauth should store hash and the remove authentication:"`[

```
not ok 298 hashauth should store hash and the remove authentication
  Cannot read property 'should' of null
  TypeError: Cannot read property 'should' of null
      at Context.<anonymous> (tests/hashauth.test.js:126:49)
      at benv.setup.url (tests/fixtures/headless.js:174:7)
      at Object.module.exports.setup (node_modules/benv/index.js:24:56)
      at Function.init [as setup] (tests/fixtures/headless.js:24:10)
      at Context.<anonymous> (tests/hashauth.test.js:28:14)
      at processImmediate (internal/timers.js:464:21)

```
This is puzzling as these changes don't interact with any of that code.

Notably, this is different from the failures seen in github actions, which fails the report test, which does not occur on my machine.  In theory just widening the date range for the query should in theory should allow the test to pass, but given the other oddities here, it's a little odd.

**Comment by bewest** [comment]
closing in favor of https://github.com/nightscout/cgm-remote-monitor/pull/7857

**Pull request closed without merging**
