### PR TITLE
Finnish localization

### PR DESCRIPTION
**Pull request by sulkaharo**
First pass Finnish localization. I assume the reporting side needs work. ;) Seems to fit the UI after some tweaking.

### CODE REVIEW

**Comment by MilosKozak** [comment]
reporting should be already covered by current language.js

**Comment by sulkaharo** [comment]
Yeah I meant the actual content I put in will probably need polish.

**Comment by jasoncalabrese** [comment]
Wonder if we should add country names name next to the language, maybe for some of the others too?

**Comment by MilosKozak** [comment]
we can do it if people will ask for it. i think everyone know his country code. or not?

**Comment by jasoncalabrese** [comment]
was thinking more for everyone else that doesn't know the languages, just to be able to look at the list

**Comment by MilosKozak** [comment]
hmmm don't know. never seen it . either english list or only national

**Comment by MilosKozak** [comment]
@jasoncalabrese maybe we could add a flag. this would be pretty clear. but there could be an issue language vs country
or something like this 
image

**Pull request merged**
