### PR TITLE
1

### PR DESCRIPTION
**Pull request by wshand80**

### CODE REVIEW

**Comment by sulkaharo** [comment]
Hi! Oops - it seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Don't worry, no harm done! Please try using the Nightscout update tool again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings. We'll close this pull request, as it's now in the Nightscout repository instead of the intended your personal copy.

**Comment by wshand80** [comment]
Thank you! Although a little concerned I haven't accessed this today ?!
Admittedly I may have inadvertently done something a few weeks ago when I
migrated mlab to Atlas and ended up having to rebuild nightscout!
Can you confirm this pull request was just done today ?

Thanks

Wendy

**Comment by sulkaharo** [comment]
Hi! I'm just cleaning up older pull requests. If Nightscout is working, no worries! :)

**Comment by wshand80** [comment]
Ah I see it in Github 19 days ago now - thank you for closing! - Rookie
mistake 😬

**Pull request closed without merging**
