### PR TITLE
if there isn't a battery value, don't set the field

### PR DESCRIPTION
**Pull request by jasoncalabrese**
trying to fix an issue with share and pebble with @oamyoamy

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
If this works need to add a test before merging

**Comment by oamyoamy** [comment]
Tested with site using Share variables and Pebble watchfaces: Nightscout 7.3 and CGM in the Cloud 7.2. Both loaded successfully. The battery variable is now gone from the pebble string:

{"status":[{"now":1440120370989}],"bgs":[{"sgv":"173","trend":5,"direction":"FortyFiveDown","datetime":1440119678000,"bgdelta":0,"iob":"0"}],"cals":[]}

**Comment by jasoncalabrese** [comment]
Great, I'll get this merged tonight

**Comment by oamyoamy** [comment]
May need to ignore my prior test. My site with Share bridge variables is
failing... xDrip may have grabbed my Share and pushed data to the Share
server rather than the Share app. The above test I ran may, in fact, not
have been with Share app upload.

**Comment by jasoncalabrese** [comment]
@oamyoamy, if this doesn't fix your issue I'll try something different, but there wasn't any reason to send `battery: false` so I wanted to get this in even if it's not that full fix.

**Comment by oamyoamy** [comment]
This change (on dev) seems to have fixed it. The user who reported the issue was running the 0.8-beta1 branch. She deployed a copy of dev with the update, and it is working.

**Comment by jasoncalabrese** [comment]
Great

Wish the interface between the server and pebble want so sloppy.  So many assumptions.  This is why I want a new endpoint.

**Pull request merged**
