### PR TITLE
Upgrade to node 8.9.0 LTS

### PR DESCRIPTION
**Pull request by PieterGit**
First Node 8 LTS release. Recommended version for Nightscout will be the latest Node 8 LTS release.
We also run Travis with Node 9.0.0 to ensure Nightscout remains compatible with the future Node release.
(update:  we won't run NodeJS 9.x on Travis for now)

### CODE REVIEW

**Comment by PieterGit** [comment]
Note on windows when I do

```
$ npm update
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ uglify-js@3.1.6
+ moment-timezone@0.5.14
+ git-rev@0.2.1
+ sgvdata@0.0.2
+ minimed-connect-to-nightscout@1.1.0
+ share2nightscout-bridge@0.1.4
added 115 packages and updated 6 packages in 22.681s
```

Therefore on Windows my `npm-shrinkwrap.json` will add `ascli` and remove all the `fsevents` dependencies. 
Is that a problem or should a Mac user do a npm update to make sure `npm-shrinkwrap.json` is complete?

**Comment by PieterGit** [comment]
Failing Travis. @sulkaharo can you explain these errors?

Node 8.9.0 errors
``` 
not ok 161 Notifications API ack notifications
  AssertionError: expected -1 to be above -1
      at Assertion.fail (node_modules/should/cjs/should.js:231:17)
      at Assertion.value (node_modules/should/cjs/should.js:305:19)
      at containsLine (tests/hashauth.test.js:163:41)
      at Window.mockConfirm [as alert] (tests/hashauth.test.js:165:7)
      at Object._.addBasals (tmp/js/bundle.js:9:4468177)
      at Object.d.scroll (tmp/js/bundle.js:9:4535342)
      at L (tmp/js/bundle.js:9:3886936)
      at Timeout.C [as _onTimeout] (tmp/js/bundle.js:9:3894953)

not ok 183 Pebble Endpoint /pebble default(1) count
  AssertionError: expected 113984 to not exist
      at Test.<anonymous> (tests/pebble.test.js:116:20)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1655:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

Node 9.0.0 error
```
not ok 30 authed REST api "before each" hook
  ReferenceError: $ is not defined
      at findOrCreatePill (lib/plugins/pluginbase.js:9:1731)
      at Object.updatePillText (lib/plugins/pluginbase.js:9:2725)
      at Object.updateVisualisation (lib/plugins/rawbg.js:9:2562)
      at eachPlugin (lib/plugins/index.js:9:6571)
      at arrayEach (node_modules/lodash/lodash.js:537:11)
      at Function.forEach (node_modules/lodash/lodash.js:9359:14)
      at Function.eachShownPlugins (lib/plugins/index.js:9:4678)
      at Function.updateVisualisations (lib/plugins/index.js:9:6326)
      at updatePlugins (lib/client/index.js:9:25861)
      at updateHeader (lib/client/index.js:9:29648)
      at brushed (lib/client/index.js:9:29892)
      at Timeout.updateClock [as _onTimeout] (lib/client/index.js:9:42375)
```

**Comment by sulkaharo** [comment]
I would actually consider not running the Node 9 tests as we have no reason to adopt 9 and any fails there are node likely to be Node issues than our code, so we’d get to a constant upgrade cycle with bumping Travis to newer Node versions.

**Comment by PieterGit** [comment]
Dropped travis build for nodejs 9.0.0. Still need to investigate why the unit tests fail.

**Comment by PieterGit** [comment]
Running for two days, I found no regressions. 
@sulkaharo : can you merge to dev?

**Comment by PieterGit** [comment]
Thanks for merging

**Pull request merged**
