### PR TITLE
Updated Day to Day report for Loop Overrides

### PR DESCRIPTION
**Pull request by jonfawcett**
Added displaying the loop temporary override name in the grey bar of the report

Screenshot 2020-01-03 12 22 28

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/report_plugins/daytoday.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4761766&bid=15877431)

**Comment by sulkaharo** [comment]
We always merge changes through dev - can you update the PR to be based on DEV so we don't have the merge conficts?

**Comment by sulkaharo** [comment]
Can you please re-submit the PR without the unrelated changes?

**Comment by jonfawcett** [comment]
I've been out of town the past week. Will resubmit to Dev next week.

**Pull request closed without merging**
