### PR TITLE
dream

### PR DESCRIPTION
**Pull request by bettecgm**

### CODE REVIEW

**Comment by bettecgm** [comment]
i want to update to latest version

**Comment by francescaneri** [comment]
http://www.nightscout.info/wiki/welcome/how-to-update-to-latest-cgm-remote-monitor-aka-cookie

**Comment by francescaneri** [comment]
saw you wanted IOB-COB:http://www.nightscout.info/wiki/labs/the-nightscout-iob-cob-website

**Comment by jasoncalabrese** [comment]
@bettecgm, I'm going to close this, but I sent you a PR that you can merge to get current: https://github.com/bettecgm/cgm-remote-monitor-1/pull/3

I think you're having some trouble since you have 2 cgm-remote-monitor repos, do you use both still?

**Comment by bettecgm** [comment]
I only use the one ,I was trying to get the raw data to show and not really
techy.

On Fri, Mar 6, 2015 at 8:34 PM, Jason Calabrese <notifications@github.com>
wrote:

> @bettecgm <https://github.com/bettecgm>, I'm going to close this, but I
> sent you a PR that you can merge to get current: bettecgm#3
> <https://github.com/bettecgm/cgm-remote-monitor-1/pull/3>
>
> I think you're having some trouble since you have 2 cgm-remote-monitor
> repos, do you use both still?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/pull/461#issuecomment-77665851>
> .
>



-- 
Bette Branch

**Comment by jasoncalabrese** [comment]
I see you merged that pull request, do you have your site working again?  Do you see 0.6.4 in the settings panel?  To enable raw look at http://www.nightscout.info/wiki/labs/interpreting-raw-dexcom-data

**Comment by jennifercnightscout** [comment]
Yes! It's working great, it now says 0.6.4 instead of 0.6.1 and options for raw data are available in the settings section. Thank you!

**Comment by bettecgm** [comment]
its working fine and I now can see the raw data .Thank you so much

On Fri, Mar 6, 2015 at 10:41 PM, Jason Calabrese <notifications@github.com>
wrote:

> I see you merged that pull request, do you have your site working again?
> Do you see 0.6.4 in the settings panel? To enable raw look at
> http://www.nightscout.info/wiki/labs/interpreting-raw-dexcom-data
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/pull/461#issuecomment-77671430>
> .
>



-- 
Bette Branch

**Pull request closed without merging**
