### PR TITLE
Update xdripjs plugin to support virtual assistants

### PR DESCRIPTION
**Pull request by inventor96**
Allows querying CGM details via virtual assistants.

### CODE REVIEW

**Comment by inventor96** [comment]
Note that the template file for Google Assistant includes the changes from https://github.com/nightscout/cgm-remote-monitor/pull/5376 (since it's a binary file, and can't be merged automatically). So this PR would need to be merged after https://github.com/nightscout/cgm-remote-monitor/pull/5376, and the `docs/plugins/google-home-templates/en-us.zip` file here would take precedence over the one from that PR.

**Comment by sulkaharo** [comment]
@inventor96 the Google Home template has merge conflicts - not sure which version is the correct one?

**Comment by inventor96** [comment]
@sulkaharo Keep the version from this PR, because it includes the changes from #5376 

Hopefully the merge conflicts in `/lib/language.js` are self-explanatory, but feel free to check out my personal dev version if you need a reference point: https://github.com/inventor96/cgm-remote-monitor/blob/dev-personal/lib/language.js#L13592

**Comment by sulkaharo** [comment]
Merged through another branch

**Pull request closed without merging**
