### PR TITLE
Adjust node version to fix Azure deploy issues

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Hopefully this simple change will be a real solution for #1412

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
@amazaheri @stavlor, can you confirm that @davidebbo's fix solves the issue and that this branch now deploys cleanly?

**Comment by amazaheri** [comment]
:+1:

**Comment by amazaheri** [comment]
Now that this is over, Per @davidebbo suggestion it would be great to implement Deploy To feature as it will ease up deployment for non techie folks. @jeffhollan added it to LogicApp repos and it works great as an example: https://github.com/logicappsio/EventHubAPI

**Comment by davidebbo** [comment]
I opened #1433 to track Deploy To Azure.

**Pull request merged**
