### PR TITLE
Funnel Cake .8.2

### PR DESCRIPTION
**Pull request by webwiztn**

### CODE REVIEW

**Comment by webwiztn** [comment]
I am lost. I was following the steps to update to 0.8.2. All seemed fine
but I never got the purple "Merged" button. What do I need to do?

Thanks!
Arlene

On Sun, Nov 1, 2015 at 6:33 PM, Codecov <notifications@github.com> wrote:

> Current coverage
> <https://codecov.io/github/nightscout/cgm-remote-monitor?ref=0d01ea109fced4bb3cfc0c9734d2c47718a6acf4>
> is 84.45%
>
> Merging *#1310
> <https://github.com/nightscout/cgm-remote-monitor/pull/1310>* into
> *master* will not affect coverage as of 0d01ea1
> <https://codecov.io/github/nightscout/cgm-remote-monitor/commit/0d01ea109fced4bb3cfc0c9734d2c47718a6acf4>
>
> @@            master   #1310   diff @@
> ======================================
>   Files           79      79
>   Stmts         6106    6106
>   Branches         0       0
>   Methods          0       0
> ======================================
>   Hit           5157    5157
>   Partial          0       0
>   Missed         949     949
>
> Review entire Coverage Diff
> <https://codecov.io/github/nightscout/cgm-remote-monitor/compare/24b674e8346d5a692fa0ba4e2f061f5affbb566f...0d01ea109fced4bb3cfc0c9734d2c47718a6acf4>
> as of 0d01ea1
> <https://codecov.io/github/nightscout/cgm-remote-monitor/commit/0d01ea109fced4bb3cfc0c9734d2c47718a6acf4>
>
> ------------------------------
> Uncovered Suggestions
> <https://codecov.io/github/nightscout/cgm-remote-monitor/features/suggestions?ref=0d01ea109fced4bb3cfc0c9734d2c47718a6acf4>
>
>    1. +0.20% via .../js/profileeditor.js#324...335
>    <https://codecov.io/github/nightscout/cgm-remote-monitor/static/profile/js/profileeditor.js?ref=0d01ea109fced4bb3cfc0c9734d2c47718a6acf4#324>
>    2. +0.18% via .../js/profileeditor.js#269...279
>    <https://codecov.io/github/nightscout/cgm-remote-monitor/static/profile/js/profileeditor.js?ref=0d01ea109fced4bb3cfc0c9734d2c47718a6acf4#269>
>    3. +0.17% via .../report/js/report.js#259...268
>    <https://codecov.io/github/nightscout/cgm-remote-monitor/static/report/js/report.js?ref=0d01ea109fced4bb3cfc0c9734d2c47718a6acf4#259>
>    4. *See 7 more...
>    <https://codecov.io/github/nightscout/cgm-remote-monitor/features/suggestions?ref=0d01ea109fced4bb3cfc0c9734d2c47718a6acf4>*
>
> Powered by Codecov <https://codecov.io>. Updated on successful CI builds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/pull/1310#issuecomment-152882021>
> .
>



-- 
Cheers,
Arlene

**Comment by jasoncalabrese** [comment]
I created pull request for you, https://github.com/webwiztn/cgm-remote-monitor/pull/4

Just click the merge button at the bottom of the page and give your site 5 or 10 minutes to update.

**Comment by webwiztn** [comment]
Jason -

I am not seeing a Merge button at the bottom of the page. Please see
attached.

Thanks for your help!

Arlene

On Sun, Nov 1, 2015 at 9:09 PM, Jason Calabrese <notifications@github.com>
wrote:

> I created pull request for you, webwiztn#4
> <https://github.com/webwiztn/cgm-remote-monitor/pull/4>
>
> Just click the merge button at the bottom of the page and give your site 5
> or 10 minutes to update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nightscout/cgm-remote-monitor/pull/1310#issuecomment-152899517>
> .
>



-- 
Cheers,
Arlene

**Comment by jasoncalabrese** [comment]
There should be a merge button some of https://github.com/webwiztn/cgm-remote-monitor/pull/4

**Comment by webwiztn** [comment]
Clicking on the link was not enough - I had to sign in again!

Thanks again for your help and all you have done for us Type 1s!

Best regards,
Arlene

**Comment by jasoncalabrese** [comment]
Great, glad it worked.  That's the main issue people are running into with the update tool, maybe there's something we can do to make it more clear.

**Comment by webwiztn** [comment]
Maybe by adding a step to sign-in again will help. I discovered the solution serendipitously!

Best regards,
Arlene

**Pull request closed without merging**
