### PR TITLE
use dev branch for coveralls

### PR DESCRIPTION
**Pull request by dduugg**

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Not sure about the change to the Make file, I want to get 0.6.1 out, think I'll just set coverage to use master

**Comment by jasoncalabrese** [comment]
oh that was already done

**Comment by jasoncalabrese** [comment]
Using the master branch seems to be ok, should we close this or is the `Makefile` change still important?

**Comment by dduugg** [comment]
Let's close this. If you start seeing flaky builds with inscrutable Travis failure messages, lemme know (that's what happened in this PR until I made the change to `Makefile`).

**Pull request closed without merging**
