### PR TITLE
Brazilian Portuguese Translation update

### PR DESCRIPTION
**Pull request by dougtakeuti**

### CODE REVIEW

**Comment by MilosKozak** [comment]
close this PR and target dev please. PM me if you need help.
Milos

**Comment by jasoncalabrese** [comment]
github added a way to change the target branch for a PR, I'll reopen and target dev

**Comment by jasoncalabrese** [comment]
I was too late new pR was already created, but for next time
 
screenshot 2016-11-07 15 47 03

**Comment by dougtakeuti** [comment]
Sorry... Already closed and created a new one. Hope I get it right this
time.

Em 7 de nov de 2016 9:46 PM, "Jason Calabrese" <notifications@github.com>
escreveu:

**Comment by jasoncalabrese** [comment]
no problem, the ability to change the target branch for a PR is new

**Pull request closed without merging**
