### PR TITLE
dev - candidate for release 15.0.0

### PR DESCRIPTION
**Pull request by bewest**
# Draft Release notes
# Nightscout version 15.0.0
Current dev branch preparing release for `15.0.0`.  This is a major version bump because we changed node version requirements to support only `lts` versions, removing older versions.

## Breaking changes:
* Node 12 no longer supported, modern versions of node and npm.
* AAPS Compatibility - AAPS 3.2.0 need at least NS 15.0.0.
* 

## Fixes
* fix security issue where part of v2 API was unsecured.
* Viewing reports from another timezone now aligns treatment and glucose data, at the trade of framing the query in UTC.  This may result in wrapping to tomorrow or yesterday's date depending on the timezones involved, and time of day.

## Improvements
* tweak viewport for iphone
* new "easy state" in v2 API to help enable reproducible, easy to consume statistics and usage information.
### Loop
* Make Loop overrides more convenient by removing unused OTP field.
* Introduce Nightsout Connect, a plugin to unify importing external cloud provider diabetes data into Nightscout.
### Android APS
* Prevent gaps from appearing in some cases.
* Upgrades to data consistency and auth
While using websockets in NS v3 plugin treatments entered through NS UI (plus button) and other applications using v1 API are not sent to AAPS. This will be fixed in future release of NS. Always use the same client (v1 or v3) in AAPS and AAPSClient until NS fully switch to v3 internaly. The same is valid for AAPS and AAPSClient itself.
See the [full release notes for AAPS 3.2.0](https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Releasenotes.html#version-3-2-0) for more details.

## Maintenance
* update or pin many dependencies to keep Nightscout up to date
* changed build system to trivially support more cloud providers, notably Digital Ocean.
* updating mongo uri parser and providing indices expected to improve Azure + CosmoDB compatibility
* More translations and language updates.
* Update mongodb dependencies and poll the database 15 seconds instead of 5 seconds.
*

### CODE REVIEW

**Comment by bewest** [comment]
If we can get reviewers to sign off, we can quickly release with confidence.

**Comment by sulkaharo** [comment]
There's something off with fsevents in the package-lock again. Heroku and Digital Ocean are trying to deploy it, despite this being an optional devdependency

**Comment by skyclad83** [comment]
Update

**Review by cgms0403 — CHANGES_REQUESTED** [review]
I'm trying to Update 15.0.0

**Comment by bewest** [comment]
Let's get this ready for release.  I've drafted some release notes in the pull request description, please suggest corrections and amendments to help describe your contributions to the pending release of Nightscout.

**Review by carolinadesouza — APPROVED** [review]

**Review by carolinadesouza — APPROVED** [review]

**Review by carolinadesouza — APPROVED** [review]
APROVAR

**Comment by carolinadesouza** [comment]
tentando atualizar para o 15

**Review by carolinadesouza — APPROVED** [review]

**Review by carolinadesouza — APPROVED** [review]

**Review by carolinadesouza — APPROVED** [review]

**Review by carolinadesouza — APPROVED** [review]

**Comment by MilosKozak** [comment]
👍

**Comment by bewest** [comment]
@MilosKozak This completes all the high priority items.  I've updated the draft release notes in the description.  Please attach any additional feedback and I will release accordingly.  :shipit: 

Did we pick an `M` theme?

**Comment by MilosKozak** [comment]
@bewest no issues 👍

**Pull request merged**
