### PR TITLE
Nightscout Release 13.0.0

### PR DESCRIPTION
**Pull request by PieterGit**
Preparing for Nightscout 0.13.0 release

New features (already merged to `dev`)
- feat: Remote Loop overrides  https://github.com/nightscout/cgm-remote-monitor/pull/5043 @ps2 
- feat: API v3 https://github.com/nightscout/cgm-remote-monitor/pull/4250 @PetrOndrusek 

Candidates PR's to merge (not merged to `dev` yet)
- https://github.com/nightscout/cgm-remote-monitor/pull/5081 @jpcunningh 
- https://github.com/nightscout/cgm-remote-monitor/pull/5111 @PieterGit 
- https://github.com/nightscout/cgm-remote-monitor/pull/4980 Update Alexa integration and add Google Home support @inventor96 

These candidates are available as https://github.com/nightscout/cgm-remote-monitor/tree/wip/013alpha  . Please help testing that branch and give feedback to the PR owners.

- ... See https://github.com/nightscout/cgm-remote-monitor/milestone/15 for overview of open issues/PR's set to milestone. I think we will postpone stuff that will not be finished in short term

### CODE REVIEW

**Comment by obok7777** [comment]
update

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/api3/generic/search/operation.js  1
- lib/server/loop.js  22
- lib/api3/generic/update/operation.js  1
- lib/api3/generic/create/validate.js  3
- lib/api3/index.js  11
- lib/plugins/xdripjs.js  37
- lib/api3/shared/dateTools.js  16
- lib/api3/swagger.js  2
- lib/api3/generic/history/operation.js  6
- lib/api3/generic/search/input.js  13
- lib/api3/generic/create/operation.js  1
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/specific/status.js  5
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/generic/setup.js  13
- lib/api3/generic/collection.js  8
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/storageSocket.js  8
- lib/api/notifications-v2.js  2
- lib/api3/generic/patch/validate.js  1
- lib/api3/generic/patch/operation.js  1
- lib/api3/specific/lastModified.js  1
- lib/api3/specific/version.js  1
- lib/api3/generic/read/operation.js  1
- lib/api3/shared/operationTools.js  15
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/update/validate.js  8
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/shared/stringTools.js  3
- lib/api3/security.js  5
- lib/api3/shared/storageTools.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/api3/swagger.js  2
- lib/api3/generic/read/operation.js  1
- lib/api3/generic/history/operation.js  6
- lib/api3/security.js  5
- lib/api3/shared/dateTools.js  16
- lib/api3/index.js  11
- lib/api3/generic/collection.js  8
- lib/api3/generic/setup.js  13
- lib/api3/generic/create/validate.js  3
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/generic/update/operation.js  1
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/search/input.js  13
- lib/server/loop.js  22
- lib/api3/storageSocket.js  8
- lib/api/notifications-v2.js  2
- lib/api3/specific/lastModified.js  1
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/patch/validate.js  1
- lib/plugins/xdripjs.js  37
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/patch/operation.js  1
- lib/api3/generic/create/operation.js  1
- lib/api3/specific/version.js  1
- lib/api3/specific/status.js  5
- lib/api3/shared/storageTools.js  3
- lib/api3/shared/stringTools.js  3
- lib/api3/shared/operationTools.js  15
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/generic/update/validate.js  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/api3/specific/version.js  1
- lib/api3/generic/read/operation.js  1
- lib/api3/specific/lastModified.js  1
- lib/plugins/xdripjs.js  37
- lib/api3/generic/history/operation.js  6
- lib/server/loop.js  22
- lib/api3/specific/status.js  5
- lib/api3/security.js  5
- lib/api3/swagger.js  2
- lib/api3/generic/patch/operation.js  1
- lib/api3/shared/operationTools.js  15
- lib/api/notifications-v2.js  2
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/generic/collection.js  8
- lib/api3/generic/setup.js  13
- lib/api3/generic/create/validate.js  3
- lib/api3/generic/search/operation.js  1
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/patch/validate.js  1
- lib/api3/shared/stringTools.js  3
- lib/api3/index.js  11
- lib/api3/shared/dateTools.js  16
- lib/api3/generic/delete/operation.js  1
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/update/operation.js  1
- lib/api3/storageSocket.js  8
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/search/input.js  13
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/update/validate.js  8
- lib/api3/shared/fieldsProjector.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- lib/api3/generic/update/validate.js  8
- lib/api3/generic/create/validate.js  3
- lib/api3/storageSocket.js  8
- lib/api3/swagger.js  2
- lib/api3/generic/history/operation.js  6
- lib/api3/specific/status.js  5
- lib/api3/generic/patch/validate.js  1
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/update/operation.js  1
- lib/api3/generic/create/operation.js  1
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/shared/storageTools.js  3
- lib/api3/specific/lastModified.js  1
- lib/api/notifications-v2.js  2
- lib/api3/generic/patch/operation.js  1
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/security.js  5
- lib/api3/generic/read/operation.js  1
- lib/api3/generic/delete/operation.js  1
- lib/api3/shared/operationTools.js  15
- lib/server/loop.js  22
- lib/api3/shared/stringTools.js  3
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/setup.js  13
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/generic/collection.js  8
- lib/api3/shared/dateTools.js  16
- lib/api3/storage/mongoCollection/find.js  2
- lib/plugins/xdripjs.js  37
- lib/api3/generic/search/input.js  13
- lib/api3/index.js  11
- lib/api3/specific/version.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/generic/create/validate.js  3
- lib/api3/swagger.js  2
- lib/api3/generic/history/operation.js  6
- lib/api/root.js  1
- lib/api3/generic/read/operation.js  1
- lib/api3/shared/dateTools.js  16
- lib/api3/generic/delete/operation.js  1
- lib/api3/index.js  11
- lib/plugins/xdripjs.js  37
- lib/api/notifications-v2.js  2
- lib/api3/generic/patch/operation.js  1
- lib/server/loop.js  22
- lib/api3/shared/operationTools.js  15
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/update/validate.js  11
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/collection.js  8
- lib/plugins/googlehome.js  6
- lib/api3/security.js  5
- lib/api3/generic/search/input.js  13
- lib/api3/generic/setup.js  13
- lib/api3/generic/patch/validate.js  1
- lib/api/googlehome/index.js  4
- lib/api3/specific/version.js  1
- lib/api3/specific/lastModified.js  1
- lib/api3/storageSocket.js  8
- lib/api3/shared/storageTools.js  3
- lib/api3/specific/status.js  5
- lib/api3/shared/stringTools.js  3
- lib/api3/generic/update/operation.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/generic/patch/operation.js  1
- lib/api3/index.js  11
- lib/api/googlehome/index.js  4
- lib/api3/generic/delete/operation.js  1
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/create/validate.js  3
- lib/api3/generic/update/validate.js  11
- lib/api3/generic/collection.js  8
- lib/api3/shared/stringTools.js  3
- lib/plugins/xdripjs.js  37
- lib/api3/generic/setup.js  13
- lib/api3/shared/dateTools.js  16
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/generic/read/operation.js  1
- lib/api3/swagger.js  2
- lib/server/loop.js  22
- lib/api/notifications-v2.js  2
- lib/api3/shared/operationTools.js  15
- lib/plugins/googlehome.js  6
- lib/api/root.js  1
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/search/input.js  13
- lib/api3/generic/update/operation.js  1
- lib/api3/security.js  5
- lib/api3/storageSocket.js  8
- lib/api3/specific/lastModified.js  1
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/specific/status.js  5
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/history/operation.js  6
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/patch/validate.js  1
- lib/api3/specific/version.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/shared/storageTools.js  3
- lib/api3/index.js  11
- lib/api3/storageSocket.js  8
- lib/api3/generic/read/operation.js  1
- lib/api/googlehome/index.js  4
- lib/api/notifications-v2.js  2
- lib/api3/generic/update/operation.js  1
- lib/api/root.js  1
- lib/api3/specific/version.js  1
- lib/plugins/xdripjs.js  37
- lib/api3/shared/operationTools.js  15
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/swagger.js  2
- lib/server/loop.js  22
- lib/api3/generic/search/operation.js  1
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/security.js  5
- lib/plugins/googlehome.js  6
- lib/api3/shared/dateTools.js  16
- lib/api3/shared/stringTools.js  3
- lib/api3/generic/patch/operation.js  1
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/history/operation.js  6
- lib/api3/specific/status.js  5
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/update/validate.js  11
- lib/api3/generic/search/input.js  13
- lib/api3/specific/lastModified.js  1
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/collection.js  8
- lib/api3/generic/create/validate.js  3
- lib/api3/generic/patch/validate.js  1
- lib/api3/generic/setup.js  13
- lib/api3/shared/fieldsProjector.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api/root.js  1
- lib/api3/generic/read/operation.js  1
- lib/api3/shared/stringTools.js  3
- lib/api3/specific/version.js  1
- lib/api3/shared/operationTools.js  15
- lib/server/loop.js  22
- lib/api3/specific/status.js  5
- lib/api3/generic/create/validate.js  3
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/swagger.js  2
- lib/api3/specific/lastModified.js  1
- lib/api3/security.js  5
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/update/operation.js  1
- lib/api3/index.js  11
- lib/api3/generic/collection.js  8
- lib/api3/generic/create/operation.js  1
- lib/api3/shared/dateTools.js  16
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/generic/search/input.js  13
- lib/api/googlehome/index.js  4
- lib/api/notifications-v2.js  2
- lib/api3/storageSocket.js  8
- lib/api3/generic/setup.js  13
- lib/plugins/googlehome.js  6
- lib/api3/generic/update/validate.js  11
- lib/api3/generic/patch/validate.js  1
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/patch/operation.js  1
- lib/api3/generic/history/operation.js  6
- lib/api3/shared/storageTools.js  3
- lib/api3/storage/mongoCollection/modify.js  3
- lib/plugins/xdripjs.js  37
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/generic/create/operation.js  1
- lib/api3/shared/dateTools.js  16
- lib/api/root.js  1
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/generic/search/input.js  13
- lib/api/notifications-v2.js  2
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/update/operation.js  1
- lib/api3/specific/status.js  5
- lib/server/loop.js  22
- lib/api/googlehome/index.js  4
- lib/api3/generic/history/operation.js  6
- lib/api3/generic/create/validate.js  3
- lib/api3/generic/patch/operation.js  1
- lib/api3/generic/update/validate.js  11
- lib/api3/shared/stringTools.js  3
- lib/api3/shared/operationTools.js  15
- lib/api3/index.js  11
- lib/api3/generic/setup.js  13
- lib/api3/generic/patch/validate.js  1
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/specific/version.js  1
- lib/api3/generic/collection.js  8
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/storageSocket.js  8
- lib/plugins/googlehome.js  6
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/read/operation.js  1
- lib/plugins/xdripjs.js  37
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/delete/operation.js  1
- lib/api3/specific/lastModified.js  1
- lib/api3/swagger.js  2
- lib/api3/security.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/plugins/xdripjs.js  37
- lib/api3/storage/mongoCollection/index.js  2
- lib/api/notifications-v2.js  2
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/create/operation.js  1
- lib/api/root.js  1
- lib/api3/shared/stringTools.js  3
- lib/api3/specific/version.js  1
- lib/api3/generic/read/operation.js  1
- lib/api/googlehome/index.js  4
- lib/api3/generic/patch/operation.js  1
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/search/input.js  13
- lib/api3/generic/update/operation.js  1
- lib/api3/shared/operationTools.js  15
- lib/api3/storageSocket.js  8
- lib/api3/shared/storageTools.js  3
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/specific/status.js  5
- lib/api3/generic/patch/validate.js  1
- lib/api3/shared/dateTools.js  16
- lib/api3/index.js  11
- lib/api3/generic/setup.js  13
- lib/api3/swagger.js  2
- lib/server/loop.js  22
- lib/api3/specific/lastModified.js  1
- lib/plugins/googlehome.js  6
- lib/api3/generic/collection.js  8
- lib/api3/security.js  5
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/update/validate.js  11
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/history/operation.js  6
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/generic/create/validate.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api/root.js  1
- lib/api3/generic/setup.js  13
- lib/api/notifications-v2.js  2
- lib/plugins/xdripjs.js  37
- lib/api3/index.js  11
- lib/api3/specific/status.js  5
- lib/api3/generic/patch/operation.js  1
- lib/api/googlehome/index.js  4
- lib/api3/generic/read/operation.js  1
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/swagger.js  2
- lib/api3/shared/operationTools.js  15
- lib/api3/generic/update/operation.js  1
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/shared/stringTools.js  3
- lib/api3/generic/patch/validate.js  1
- lib/api3/specific/lastModified.js  1
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/storageSocket.js  8
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/history/operation.js  6
- lib/api3/generic/search/input.js  13
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/create/validate.js  3
- lib/api3/security.js  5
- lib/server/loop.js  22
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/update/validate.js  11
- lib/api3/specific/version.js  1
- lib/api3/generic/collection.js  8
- lib/api3/storage/mongoCollection/modify.js  3
- lib/plugins/googlehome.js  6
- lib/api3/shared/dateTools.js  16
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/generic/search/operation.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/generic/update/validate.js  11
- lib/plugins/xdripjs.js  37
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/shared/dateTools.js  16
- lib/api3/generic/search/operation.js  1
- lib/api3/swagger.js  2
- lib/api3/generic/create/validate.js  3
- lib/api3/generic/patch/operation.js  1
- lib/api3/generic/create/operation.js  1
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/generic/collection.js  8
- lib/api3/security.js  5
- lib/api3/shared/operationTools.js  15
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/setup.js  13
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/storageSocket.js  8
- lib/server/loop.js  22
- lib/api3/generic/update/operation.js  1
- lib/api3/specific/lastModified.js  1
- lib/api3/generic/search/input.js  13
- lib/api3/specific/status.js  5
- lib/api/googlehome/index.js  4
- lib/api3/shared/stringTools.js  3
- lib/api/notifications-v2.js  2
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/history/operation.js  6
- lib/api/root.js  1
- lib/api3/index.js  11
- lib/api3/generic/read/operation.js  1
- lib/api3/generic/delete/operation.js  1
- lib/plugins/googlehome.js  6
- lib/api3/specific/version.js  1
- lib/api3/generic/patch/validate.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/generic/search/input.js  13
- lib/api3/storage/mongoCollection/find.js  2
- lib/server/loop.js  22
- lib/api3/index.js  11
- lib/api3/generic/history/operation.js  6
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/update/validate.js  11
- lib/api/root.js  1
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/shared/storageTools.js  3
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/storageSocket.js  8
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/generic/patch/validate.js  1
- lib/api3/specific/version.js  1
- lib/plugins/xdripjs.js  37
- lib/api3/specific/status.js  5
- lib/api3/shared/dateTools.js  16
- lib/api3/generic/search/operation.js  1
- lib/api3/specific/lastModified.js  1
- lib/api/notifications-v2.js  2
- lib/api3/swagger.js  2
- lib/api3/generic/setup.js  13
- lib/api3/shared/operationTools.js  15
- lib/api3/security.js  5
- lib/plugins/googlehome.js  6
- lib/api/googlehome/index.js  4
- lib/api3/generic/update/operation.js  1
- lib/api3/generic/create/validate.js  3
- lib/api3/shared/stringTools.js  3
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/read/operation.js  1
- lib/api3/generic/patch/operation.js  1
- lib/api3/generic/collection.js  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/generic/search/operation.js  1
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/shared/stringTools.js  3
- lib/api3/specific/status.js  5
- lib/api3/generic/patch/operation.js  1
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/update/validate.js  11
- lib/api/googlehome/index.js  4
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/specific/lastModified.js  1
- lib/api3/shared/operationTools.js  15
- lib/api3/generic/history/operation.js  6
- lib/api3/security.js  5
- lib/api3/generic/patch/validate.js  1
- lib/api3/shared/dateTools.js  16
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/storageSocket.js  8
- lib/api3/generic/update/operation.js  1
- lib/api3/shared/storageTools.js  3
- lib/server/loop.js  22
- lib/api3/index.js  11
- lib/api3/generic/collection.js  8
- lib/api/notifications-v2.js  2
- lib/api3/generic/setup.js  13
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/delete/operation.js  1
- lib/api/root.js  1
- lib/api3/generic/create/validate.js  3
- lib/api3/generic/search/input.js  13
- lib/plugins/xdripjs.js  37
- lib/api3/storage/mongoCollection/index.js  2
- lib/plugins/googlehome.js  6
- lib/api3/specific/version.js  1
- lib/api3/generic/read/operation.js  1
- lib/api3/swagger.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/generic/setup.js  13
- lib/api3/specific/status.js  5
- lib/api3/generic/create/operation.js  1
- lib/plugins/xdripjs.js  37
- lib/api3/shared/stringTools.js  3
- lib/api3/shared/operationTools.js  15
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/delete/operation.js  1
- lib/api3/generic/update/operation.js  1
- lib/api3/specific/lastModified.js  1
- lib/api3/generic/search/input.js  13
- lib/api3/generic/search/operation.js  1
- lib/api3/generic/update/validate.js  11
- lib/api/notifications-v2.js  2
- lib/api3/generic/patch/validate.js  1
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/read/operation.js  1
- lib/api3/security.js  5
- lib/plugins/googlehome.js  6
- lib/api3/generic/history/operation.js  6
- lib/api/root.js  1
- lib/api3/shared/dateTools.js  16
- lib/api3/storageSocket.js  8
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/index.js  11
- lib/server/loop.js  22
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/collection.js  8
- lib/api/googlehome/index.js  4
- lib/api3/generic/create/validate.js  3
- lib/api3/swagger.js  2
- lib/api3/generic/patch/operation.js  1
- lib/api3/specific/version.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/shared/fieldsProjector.js  4
- lib/api3/generic/delete/operation.js  1
- lib/api3/specific/status.js  5
- lib/api3/specific/version.js  1
- lib/api3/generic/patch/validate.js  1
- lib/api3/swagger.js  2
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/setup.js  13
- lib/api3/storageSocket.js  8
- lib/api3/generic/patch/operation.js  1
- lib/api/googlehome/index.js  4
- lib/api3/shared/dateTools.js  16
- lib/plugins/googlehome.js  6
- lib/api3/generic/search/input.js  13
- lib/api3/specific/lastModified.js  1
- lib/api3/generic/read/operation.js  1
- lib/api3/shared/operationTools.js  15
- lib/server/loop.js  22
- lib/api3/generic/history/operation.js  6
- lib/api3/generic/search/operation.js  1
- lib/api/notifications-v2.js  2
- lib/api3/shared/stringTools.js  3
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/security.js  5
- lib/api3/generic/create/validate.js  3
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api3/index.js  11
- lib/api/root.js  1
- lib/api3/generic/update/operation.js  1
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/storage/mongoCollection/find.js  2
- lib/plugins/xdripjs.js  37
- lib/api3/generic/update/validate.js  11
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/collection.js  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- lib/api3/shared/storageTools.js  3
- lib/api3/generic/read/operation.js  1
- lib/plugins/googlehome.js  6
- lib/api3/specific/status.js  5
- lib/api3/storage/mongoCollection/index.js  2
- lib/api3/shared/fieldsProjector.js  4
- lib/plugins/xdripjs.js  37
- lib/api3/index.js  11
- lib/api3/storage/mongoCollection/modify.js  3
- lib/api/root.js  1
- lib/api3/generic/patch/validate.js  1
- lib/api3/generic/update/validate.js  11
- lib/api3/generic/collection.js  8
- lib/api3/storage/mongoCollection/utils.js  16
- lib/api3/generic/create/operation.js  1
- lib/api3/generic/search/operation.js  1
- lib/api3/specific/version.js  1
- lib/api3/shared/dateTools.js  16
- lib/api3/generic/history/operation.js  6
- lib/api3/generic/update/operation.js  1
- lib/api/notifications-v2.js  2
- lib/api3/specific/lastModified.js  1
- lib/api3/shared/operationTools.js  15
- lib/server/loop.js  22
- lib/api3/shared/stringTools.js  3
- lib/api3/storage/mongoCollection/find.js  2
- lib/api3/generic/search/input.js  13
- lib/api/googlehome/index.js  4
- lib/api3/swagger.js  2
- lib/api3/generic/patch/operation.js  1
- lib/api3/security.js  5
- lib/api3/generic/setup.js  13
- lib/api3/storageSocket.js  8
- lib/api3/generic/create/validate.js  3
- lib/api3/generic/delete/operation.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Nightscout/cgm-remote-monitor/pullRequest?prid=4343643&bid=14765112)

**Pull request merged**
