### PR TITLE
Funnel Cake (0.8.0)

### PR DESCRIPTION
**Pull request by jasoncalabrese**

### CODE REVIEW

**Comment by bewest** [comment]
:heart: it, LGTM. :sunglasses:

**Comment by ELUTE** [comment]
Looks good.

**Comment by LynneRB** [comment]
Working great!

**Comment by clousefamily** [comment]
Good from here

**Comment by stavlor** [comment]
:+1:  looks good to me

**Comment by oamyoamy** [comment]
+1

**Comment by MilosKozak** [comment]
+1

**Pull request closed without merging**
