### PR TITLE
Check devicestatus for COB from OpenAPS and Loop

### PR DESCRIPTION
**Pull request by jasoncalabrese**
screenshot 2016-12-01 01 05 20

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
@ELUTE you might like this, I haven't done much testing yet.  Also do you have an example devicestatus from Loop with cob?

**Comment by ELUTE** [comment]
Thanks!

 "cob": {
            "timestamp": "2016-12-01T13:10:00Z",
            "cob": 19.87592511101802
        },

**Comment by ELUTE** [comment]
{
    "_id": {
        "$oid": "584021c3d2acb5c8b18ee240"
    },
    "device": "loop://Sydney's iPhone",
    "loop": {
        "predicted": {
            "values": [
                102,
                100,
                99,
                99,
                100,
                102,
                105,
                110,
                115,
                122,
                130,
                139,
                149,
                159,
                168,
                175,
                182,
                188,
                192,
                196,
                199,
                201,
                201,
                201,
                200,
                199,
                198,
                197,
                196,
                195,
                194,
                193,
                192,
                191,
                190,
                189,
                189,
                188,
                187,
                187,
                186,
                186,
                185,
                185,
                185,
                185,
                185
            ],
            "startDate": "2016-12-01T13:09:34Z"
        },
        "name": "Loop",
        "cob": {
            "timestamp": "2016-12-01T13:10:00Z",
            "cob": 19.87592511101802
        },
        "timestamp": "2016-12-01T13:12:33Z",
        "iob": {
            "timestamp": "2016-12-01T13:10:00Z",
            "iob": 0.871013412265003
        },
        "version": "1.1",
        "recommendedBolus": 1.425
    },
    "created_at": "2016-12-01T13:12:33Z"
}

**Comment by jasoncalabrese** [comment]
Thanks, that confirms structure I was expecting, I think what I have now will work just need to test it more

**Pull request merged**
