### PR TITLE
Merge pull request #1 from nightscout/master

### PR DESCRIPTION
**Pull request by alvarego**
Update 2018-06-09

### CODE REVIEW

**Comment by unsoluble** [comment]
(Make sure you're logged into your GitHub account *before* you go to the update-checking page for Nightscout.)

**Comment by sulkaharo** [comment]
Hi! It seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Please try again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings.

**Comment by alvarego** [comment]
Hello Sulka,

I am really sorry to bother you with this, I am a developer and know some
repository tools but I am really unfamiliar with Git, I was simply trying
to update my fork to create a new heroku site 😩

Finally all worked just fine, please ignore everything about the request, I
will try to read some more documentation before trying anything, thanks for
your patience :-)

Best regards

**Comment by sulkaharo** [comment]
Heh, no problem. :) Glad you have Nightscout working, hope you're finding it useful! <3

**Pull request closed without merging**
