### PR TITLE
Szpaku80 patch 1

### PR DESCRIPTION
**Pull request by szpaku80**
Add Polish language.

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Looks like there is a typo, also this should be targeting the `dev` branch instead of `master`

**Comment by MilosKozak** [comment]
do you know how to fix it?

**Comment by jasoncalabrese** [comment]
The build failure here was the same we saw with other branches. I was going to make a new PR from your szpaku80-patch-1 branch to dev, but there are conflicts.

**Comment by MilosKozak** [comment]
merged to dev-0.9 by https://github.com/nightscout/cgm-remote-monitor/pull/1287

**Pull request closed without merging**
