### PR TITLE
Notification plugins, unify pushover/websocket alarm, everything is becoming a plugin

### PR DESCRIPTION
**Pull request by jasoncalabrese**

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Still need to more clean up and add some tests

**Comment by stavlor** [comment]
Looks good, after deploying though not sure if i messed something up in my deploy but i lost raw, it still shows raw but anything uploaded after the deployment shows rawbg as 0

**Comment by stavlor** [comment]
ah never mind uploader restarted and all looks good now could of just been the it playing catch up from when i took my heroku instance down to deploy it but

**Comment by jasoncalabrese** [comment]
@stavlor are you using mqtt?  Saw an issue similar to what you described, and was probably a result of the merge thats done when the mqtt download is received.

**Comment by stavlor** [comment]
@jasoncalabrese  yeah, I'm using mqtt after restarting my uploader raw data has comeback, not sure if that just a coincidence or not but if you look at http://ns.stavlor.net 9:17am - about 10:17am raw was showing as 0 but all seems good now

**Comment by stavlor** [comment]
Nice

**Pull request merged**
