### PR TITLE
Wip/bewest/daytoday redo 03

### PR DESCRIPTION
**Pull request by bewest**
* https://github.com/nightscout/cgm-remote-monitor/pull/7836
* https://github.com/nightscout/cgm-remote-monitor/pull/7849

### CODE REVIEW

**Comment by bewest** [comment]
@marionbarker This is worth testing.  I locally tested with some imported data. I can now use chrome > more tools > sensors to change location from Tokyo to Honolulu and view the same graphs, although the name of day and date has an interesting relationship, the data seems correct.  Can you confirm this accomplishes what we were after?

**Comment by marionbarker** [comment]
I will work on this now. Thanks for keeping at it.

**Comment by marionbarker** [comment]
This is closer but not right. Top graphic shows plot for Thursday with 3 time zones.
* The same timezone plots correctly.
* The plus 3 hour timezone plots Thursday incorrectly, what is shown is yesterday's data (Wed).
* The minus 2 hour timezone plots Thursday 2023-01-26 correctly but includes an empty plot of tomorrow (2nd graphic).

All of these Day-to-Day plots are using dev plus PR #7857 up through commit b376239.

nightscout-time-zone-pr-7857-b376239

This next plot shows the newest 2 days plotted when time-zone is minus 2 hours. Today is actually Thursday and that plot is correct, but an empty plot for Friday is included in the output.

nightscout-multi-day-minus-2hr-timezone-15 0 0-pr7857-b376239

**Comment by Nightfoxy** [comment]
Fixing this will be a big help! Hopefully, I'll have some time to try this out tonight or tomorrow.

**Comment by Nightfoxy** [comment]
we may need to try testing what happens after a time change with Loop data.

**Comment by bewest** [comment]
Thanks @marionbarker sounds like things are actually working, but the definition of "working" is going to be a little odd.  When the viewer is east compared to the profile, it is correct in the sense that the label showing "Thursday in UTC" is in fact Wednesday's data relative to the profile.  The problem there is that "Friday in UTC"  (with Thursday's profile data westward) is not *also* showing up.
I'm able to select the next day in the UI to get this data.  This fixes the previous problems where the data is incorrectly shifted.  All data is now correctly shifted to midnight.

Now, the search window for data includes all data to the end of the day in UTC; when this wraps around the international dateline, an extra day can appear.  This is the empty extra Friday.  In the case where this wraps the international dateline, this can produce in a missing chart for 12 hours of the day, during which the full chart can be found by advancing the search query by one day.  (Eg search to the 27th of January fixes the issue.)
While admittedly a little quirky, it does fix the earlier issues where the data is shifted.

**Comment by bewest** [comment]
@marionbarker in terms of separating the issues out, it would be good to confirm that these patches solve the issue where people from different timezones have no hope of reading the chart correctly due to the shifting that occurs.

There are notable caveats, including a special relationship with the name and format of the date across timezones, including an extra empty day that can result when crossing timezones.

It seems like there are additional fixes/issues for that, but this seems like an overall improvement.

**Comment by marionbarker** [comment]
Thanks again Ben. I will test this and let you know.

**Comment by marionbarker** [comment]
This is an improvement, but please don't stop. 

Graphics below summary.

**Summary:**

Computer in same time zone as looper phone
* plots show looper's time-of-day and **date**
* the requested dates match what is shown

Computer is plus 3 hours wrt looper, e.g., computer is EST vs PST for Looper
* plots show looper's time-of-day but **date label is one day in future**
* must request one day in future to see data from current day (wrong date label)

Computer is minus 2 hours wrt Looper
* plots show looper's time-of-day and **date**
* the requested dates provide one blank plot with tomorrow's date before showing today and yesterday

**Screen Shots in same order as Summary:**

ns-same-timezone-15 0 0-pr7857-a805939

ns-plus-3hr-timezone-15 0 0-pr7857-a805939

ns-minus-2hr-timezone-15 0 0-pr7857-a805939

**Comment by bewest** [comment]
It would be beneficial to include this as-is into Nightscout because of the improvement it represents.   There are new issues with dates crossing zones and the prime meridian that can result in the label being incorrect, but the issue with shifting the data is solved.  These issues are getting added to the a substantial amount of rework Sulka and I have been divvying up.

**Comment by marionbarker** [comment]
I understand. Yes. I support merging this improvement. I’ll be happy to test a future PR. 

Thanks to @bewest and @sulkaharo for working on this.

**Pull request merged**
