### PR TITLE
Ice Cream

### PR DESCRIPTION
**Pull request by kmiller1021**
IceCreamUpdate

### CODE REVIEW

**Comment by unsoluble** [comment]
(Make sure you're logged into your GitHub account *before* you go to the update-checking page for Nightscout.)

**Comment by kmiller1021** [comment]
> (Make sure you're logged into your GitHub account _before_ you go to the update-checking page for Nightscout.)

I am logged in, but it is not pulling or updating.  Not sure what is going on.

**Comment by unsoluble** [comment]
The trick is that you need to be logged in before clicking the check for updates button — otherwise the pull request can’t be created automatically in the right way.

Now that you’re logged in here, go back and go through the update-checking process, it should create a new PR that is correct. (And you can close this one.)

**Comment by sulkaharo** [comment]
Hi! It seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Please try again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings.

**Pull request closed without merging**
