### PR TITLE
bugfix, if we stick to the original logic it seems to work as expected

### PR DESCRIPTION
**Pull request by jweismann**
cf. https://github.com/nightscout/cgm-remote-monitor/pull/4044.

### CODE REVIEW

**Comment by PieterGit** [comment]
@jweismann I improved the fix and PR'ed it with https://github.com/nightscout/cgm-remote-monitor/pull/4253

Can please see if that PR works for you. That's a better fix than this PR.

**Comment by PieterGit** [comment]
Clsoing. Fixed with https://github.com/nightscout/cgm-remote-monitor/pull/4253

**Comment by jweismann** [comment]
Just tested this option and both cases works like a charm and default is to redirect as we agreed so all good now - thanks, PieterGit!

**Comment by PieterGit** [comment]
@jweismann thanks for confirming that my fixes work. Thank you for initiating this PR.

**Pull request closed without merging**
