### PR TITLE
Test new dev version of minimed-connect-to-nightscout

### PR DESCRIPTION
**Pull request by bewest**
Try out plugin with recent fixes, thanks to @fredmk.  If this tests well we will promote minimed-connect-to-nightscout changes to master and do full release cycle there and update this thread after.

### CODE REVIEW

**Comment by bewest** [comment]
https://github.com/nightscout/minimed-connect-to-nightscout/pull/17

@sulka, and @fredmk here is a patch to test Nightscout against Frigyes' recent changes.
There may be some ongoing sensitivities with what happens when cloud native plugins need to handle error recovery scenarios.
One scenario is when plugin determines that the failure is permanent: the collected credentials or network access path is not functional and never will be.
Another scenario is when the plugin experiences a transient failure, perhaps related to lockout (eg when Dexcom password changes) or security measures involved with rate limiting (eg we hypothesize Medtronic and Dexcom limits number of concurrent active token) backing off for a while result in a more stable performance. 

Been thinking a lot about the kind of observability needed to verify the rate limiting in features like this and am hopeful to have some ideas to help solve this kind of thing across plugins.

**Comment by bewest** [comment]
@psonnera, @ffernandezro, if this tests ok, I will prep the mmconnect plugin and cgm-remote-monitor for release.

**Comment by sulkaharo** [comment]
Right - @bewest I'd love to get the admin messages feature out for release after next, so maybe we should think of extending the plugin API to 1) include a clean method of triggering data loads using the event bus and a defined API for storing new CGM entries and treatments, and 2) method for reporting the integration status, so we'd have a channel to expose issues to users. Would mean additional work for mmconnect but this would clean the system a lot

**Comment by AlejandroPaula** [comment]
@Sulka and @bewest I would like to know if this thread would be to be able to connect Ns to the Medtronic MINIMED Mobile and Carelink Connect apps to track 780g in Ns, or if they are working on it, thanks

**Comment by tudorfarcas2002** [comment]
I need help for testing because i cannot find a way to manage with Carelink connection

MiniMed Connect   error: Error: Request failed with status code 403
--
stack: Error: Request failed with status   code 403
at   createError   (/app/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/createError.js:16:15)
at   settle   (/app/node_modules/minimed-connect-to-nightscout/node_modules/axios/lib/core/settle.js:17:12)
at   /app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:79:25
at   new Promise (<anonymous>)
at   responseInterceptor   (/app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/interceptors/response.js:78:9)
at   /app/node_modules/minimed-connect-to-nightscout/node_modules/axios-cookiejar-support/lib/index.js:130:67
at   runMicrotasks (<anonymous>)
at   processTicksAndRejections (internal/process/task_queues.js:97:5)
at   async doLoginEu1   (/app/node_modules/minimed-connect-to-nightscout/carelink.js:147:16)
at   async checkLogin   (/app/node_modules/minimed-connect-to-nightscout/carelink.js:247:32)
Load Complete:
sgvs:547, treatments:1, profiles:1,   devicestatus:132, sensorTreatments:1

**Comment by mrinnetmaki** [comment]
> I need help for testing because i cannot find a way to manage with Carelink connection
> 
> ## MiniMed Connect error: Error: Request failed with status code 403

@tudorfarcas2002 I believe this problem is discussed in at least https://github.com/nightscout/cgm-remote-monitor/issues/6616#issuecomment-739929178 (point 4). https://github.com/nightscout/minimed-connect-to-nightscout/issues/15 might also be relevant.

**Comment by bewest** [comment]
Thank you for testing, @tudorfarcas2002.  Which country are you in?  I have found that sometimes setting country code makes a difference, eg `MMCONNECT_COUNTRYCODE=us` vs `MMCONNECT_COUNTRYCODE=gb` can make a big difference.  Can you share the relevant environment variables used, but without username and password?
Thanks again!

**Comment by bewest** [comment]
For anyone using this plugin, if it's not working for you currently, please remove `mmconnect` from the `ENABLE` list of feature until we can obtain more data

**Comment by tudorfarcas2002** [comment]
> For anyone using this plugin, if it's not working for you currently, please remove `mmconnect` from the `ENABLE` list of feature until we can obtain more data

Hello. 
I'm from Romania but in web page i don't select Romania. I leave default selection while the country is from Europe. It work web base, even i select another country from Europe.
Where i can add MMCONNECT_COUNTRYCODE=RO or GB to test again

**Comment by benceszasz** [comment]
I have deployed the new dev version in Heroku, but I am still receiving HTTP 403 (EU):

at async doLoginEu1 (/app/node_modules/minimed-connect-to-nightscout/carelink.js:147:16)

MMConnect as a standalon node.js app is working fine for many users, but when I try to run it in Heroku it receives HTTP 403. Are you sure, that Medtronic didn't blacklisted Heroku?

**Comment by psonnera** [comment]
Same here. Tried both with an US based and Europe based app. Same issue. Using latest cgm-remote-monitor dev version

**Comment by bewest** [comment]
Great, thanks for testing!  If it's not working in heroku, please ensure `mmconnect` is absent from the `ENABLE` list.  Getting unblocked will involve the entire community flushing through with zero "bad" attempts from Heroku.

**Comment by trucris** [comment]
Nightscout it's working within Carelink. Thanks Ben and all developers

**Comment by ClifClimber** [comment]
Hi all ... I've read this post and I can't undestands if it apply also to Minimed 780G or no yet ??.

Thanks all !!!

**Pull request merged**
