### PR TITLE
update Icecream2

### PR DESCRIPTION
**Pull request by NSEmily2004**
update to Icecream

### CODE REVIEW

**Comment by PieterGit** [comment]
@NSEmily2004 you're merging the wrong way. Your proposing changes to the Nightscout software. I believe this is a mistake. Ask for help at https://gitter.im/nightscout/public if you need it. Closing PR

**Comment by NSEmily2004** [comment]
I am so sorry. I hope I did not cause a problem. You already do so much for the community and causing you additional work fixing my mistakes was not my intent. Again I am terribly sorry.

**Comment by PieterGit** [comment]
@NSEmily2004 No problem. It happens more. We should make the update process more easy.

**Comment by NSEmily2004** [comment]
Thank you for being so gracious. Your kindness is appreciated. 💕

**Pull request closed without merging**
