### PR TITLE
Merge pull request #6905 from nightscout/dev

### PR DESCRIPTION
**Pull request by Goloshyk**
Release 14.2.2

* Merge latest translations from Crowdin
* Clean project root
* Re-introduce a wrapper server.js in the project root

### CODE REVIEW

**Comment by Goloshyk** [comment]
Здравствуйте, я являюсь пользователем, спасибо большое

вс, 21 мар. 2021 г., 01:05 Milos Kozak ***@***.***>:

**Comment by sheerlearner** [comment]
update

**Comment by sheerlearner** [comment]
merge pull request for interchanging base repository to head repository

**Comment by HenrikAntin** [comment]
Update

**Comment by Vitaly37** [comment]
update

**Comment by blood17sher** [comment]
Update Nightscout

**Comment by blood17sher** [comment]
Update

**Pull request closed without merging**
