### PR TITLE
Merge pull request #1 from nightscout/dev

### PR DESCRIPTION
**Pull request by dlhayes57**
Dev

### CODE REVIEW

**Comment by unsoluble** [comment]
Gotta double-check the direction your PRs are flowing there. :)

**Comment by dlhayes57** [comment]
Are you the reason my nightscout magically worked this morning? As you can tell, I have no clue what I am doing. 

Deb

**Comment by unsoluble** [comment]
I'll take credit for that, sure. :)
(No, I didn't do anything on this end. Were you trying to update your dev branch? I guess you got it sorted eventually?)

**Comment by dlhayes57** [comment]
I was. I updated to the JoJo branch and I guess I didn’t follow the directions close enough :)

Deb

**Pull request closed without merging**
