### PR TITLE
Initial style guide and dev tips in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Some initial ideas, open to any other ideas.  Just want to get something basic in place.

### CODE REVIEW

**Comment by bewest** [comment]
:+1:

**Comment by Fokko** [comment]
Perfect, I prefer the tab's instead of two spaces. But this is a matter of taste, I will configure my IDE. 

Any idea's on the single line statements:
``` js
if(err)
  throw new Error("MongoDB connection string is missing");
// or
if(err) {
  throw new Error("MongoDB connection string is missing");
}
```
I don't mind, the second is more verbose than the first one.

**Comment by jasoncalabrese** [comment]
I prefer `if (` vs `if(`, but wrapping seems dependent on the length of the line.  With languages like Scala I avoid the extra `{}`s, but trend to add them with js.  Don't think it's a big deal either way.

**Comment by sulkaharo** [comment]
However we do this, I'd love simple instructions how to set IntelliJ to auto-format using the conventions. Ideally an importable settings file... ;)

**Comment by jasoncalabrese** [comment]
I looked at JSCS a littlehttps://github.com/jscs-dev/node-jscs 

I don't want to have to worry about every detail, so if there a button or script that can make everything look nice that would be nice.


More about jscs here:

https://medium.com/@addyosmani/auto-formatting-javascript-code-style-fe0f98a923b8

**Comment by jasoncalabrese** [comment]
Opened #648 to get JSCS configured, there's a plugin for intellij and many other editors that could be used

**Pull request merged**
