### PR TITLE
update my site

### PR DESCRIPTION
**Pull request by wagnerpe**

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Need any help updating your site?

**Comment by wagnerpe** [comment]
My deployment has repeatedly failed and has fallen back on an April 2015 deployment.  It says “running deployment command” until it times out.  I’m trying again.  I believe it worked until about 11:00pm last night.  At that time my uploader was receiving current data, but it was not reflecting on my webpage, so I started troubleshooting and saw the failed deployment.

**Comment by wagnerpe** [comment]
FYI – the deployment was successful this morning.  THanks for all you do!

 

Patty

**Comment by jasoncalabrese** [comment]
great :)

**Pull request closed without merging**
