### PR TITLE
Update

### PR DESCRIPTION
**Pull request by pampopcorn**

### CODE REVIEW

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by pampopcorn** [comment]
My nightscout has not been working since I upgraded to G6 in July.  Was
hoping this might fix it, but alas, no luck.  Now not only do I have no BG,
but it stopped uploaded stuff from loop as well.

http://nightscout.github.io/pages/update-fork/?fbclid=IwAR0nKNM7cqGHpUr1TPP4gOM9htizNOZMEEPlZnqS7VUtUWArEpMLGiz4tF0
[image: Screen Shot 2019-02-14 at 1.59.18 PM.png]

**Comment by unsoluble** [comment]
Interesting, thanks. In the future, just do a quick double-check of the direction the PR is facing — you want to have your own repository on the left (the "base"), and the nightscout repo on the right (the "head"). The [update tool](http://nightscout.github.io/pages/update-fork/) should do this automatically, but it seems to be failing in some cases.

If you want a hand troubleshooting your setup, I'm happy to walk through it with you here or over in the Gitter channel or something.

**Comment by pampopcorn** [comment]
That would be great!!!!

I am about to head out to teach, but maybe I can ping you on glitter
later?  I only have the openaps and loop glitter conversations as of now.
Could you remind me of the link, or title of the nightscout channel?

**Comment by unsoluble** [comment]
The cgm-remote-monitor channel is here: https://gitter.im/nightscout/cgm-remote-monitor
Can also DM me there, am under the same name.

**Comment by sulkaharo** [comment]
Hi! This PR was made to the "wrong direction", as in "to Nightscout from your fork", instead the wanted "from Nightscout to your fork". Closing this so the team can see the development-related PRs easier (but please come and comment to the question above).

**Pull request closed without merging**
