### PR TITLE
Merge pull request #1 from nightscout/master

### PR DESCRIPTION
**Pull request by vicolalex**
update

### CODE REVIEW

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by vicolalex** [comment]
Sorry , don't remember how I managed to make this request.
Did manager to update with success.

**Comment by unsoluble** [comment]
Interesting, thanks. In the future, just do a quick double-check of the direction the PR is facing — you want to have your own repository on the left (the "base"), and the nightscout repo on the right (the "head"). The [update tool](http://nightscout.github.io/pages/update-fork/) should do this automatically, but it seems to be failing in some cases.

**Comment by sulkaharo** [comment]
Hi! This PR was made to the "wrong direction", as in "to Nightscout from your fork", instead the wanted "from Nightscout to your fork". Closing this so the team can see the development-related PRs easier (but please come and comment to the question above).

**Pull request closed without merging**
