### PR TITLE
Added a specific rendering for BG Check events on the Day to Day report.

### PR DESCRIPTION
**Pull request by yodax**
We are using the android uploader to upload our sons Medtronic 670g to nightscout. This works really well. There are a lot of treatments generated during a day that hinder analysis on the day to day report:

firefox_tljnv9LIAI

What I've done is added a specific rendering for BG Checks and made that optional and enabled by default:

firefox_RRtH08r9Wk

I've made the "other" treatments render optionally and disabled by default:

firefox_xj6OsgvG3X

firefox_eqDyPSJr4e

One thing we could consider adding is rendering the BG value at an angle next to the BG Check circle. 

I hope you consider this PR for inclusion. I'm open to changes and no hard feelings if it doesn't fit in the project.

### CODE REVIEW

**Comment by sulkaharo** [comment]
Hi! Sorry for the long pause here - I was looking at the graphs and wondered if the text label is actually needed in all the checks? If we just plotted the BG check dots, the graph would still have the same info, but be much more readable. (Same applies to a lot of the other events, too.)

**Comment by sulkaharo** [comment]
Ping @yodax - see comments above?

**Comment by yodax** [comment]
>Hi! Sorry for the long pause here
No worries :)

> if the text label is actually needed in all the checks?
The events that don't have a specific rendering do need their labels I think. It's hard to distinguish between site and sensor changes for instance. We could give them different colors, but then you'd need a legend of some sorts.

**Comment by sulkaharo** [comment]
Hi! We just gained a new feature where the report options are now persisted. Can you merge latest DEV into the branch and do the small change to add the option saving and I'll merge this in. :)

**Comment by yodax** [comment]
Will do!

**Comment by yodax** [comment]
I rebased this locally, but I can't seem to get the latest dev branch working on my environment. These issues don't seem to be related to my changes. (famous last words ofcourse) I don't have time at the moment to look at these issues. Hopefully later today or this week.

For now here are the log entries:

```
WARNING in ./lib/settings.js
Module Warning (from ./node_modules/eslint-loader/index.js):

/usr/home/nightscout/cgm-remote-monitor/lib/settings.js
  115:21  warning  Variable Assigned to Object Injection Sink  security/detect-object-injection
  117:22  warning  Generic Object Injection Sink               security/detect-object-injection
  119:26  warning  Variable Assigned to Object Injection Sink  security/detect-object-injection
  192:26  warning  Variable Assigned to Object Injection Sink  security/detect-object-injection
  194:13  warning  Generic Object Injection Sink               security/detect-object-injection

~\~V 5 problems (0 errors, 5 warnings)

 @ ./lib/client/browser-settings.js 16:17-39
 @ ./lib/client/clock-client.js
 @ ./bundle/bundle.clocks.source.js
 @ multi webpack-hot-middleware/client?port=1337 ./bundle/bundle.clocks.source.js^[[39m^[[22m

^[[1m^[[33mWARNING in ./lib/times.js
Module Warning (from ./node_modules/eslint-loader/index.js):

/usr/home/nightscout/cgm-remote-monitor/lib/times.js
  38:12  warning  Function Call Object Injection Sink  security/detect-object-injection

~\~V 1 problem (0 errors, 1 warning)
```

There are many more of these. I'm not sure that these are the problem or that they are being caused by an underlying issue. 

It started with ```Error: Cannot find module 'owasp-password-strength-test'``` That was solved by npm update. 

This is from the start once it was updated:

```Parsing config URL from IMPORT_CONFIG failed
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at lib/api/treatments/index.js:16:17
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated undefined extended: provide extended option at node_modules/body-parser/index.js:105:29
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at lib/api/treatments/index.js:151:36
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at lib/api/activity/index.js:15:19
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at lib/api/activity/index.js:96:38
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at app.js:250:19
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at app.js:254:22
Mon, 01 Feb 2021 09:00:40 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at app.js:258:22
^[[33m~Z^[[39m ^[[90m｢wdm｣^[[39m: Hash: ^[[1mb6a3efea247585426de2^[[39m^[[22m
Version: webpack ^[[1m4.44.1^[[39m^[[22m
Time: ^[[1m21637^[[39m^[[22mms
Built at: 02/01/2021 ^[[1m10:01:02 AM^[[39m^[[22m
                  ^[[1mAsset^[[39m^[[22m      ^[[1mSize^[[39m^[[22m  ^[[1mChunks^[[39m^[[22m  ^[[1m^[[39m^[[22m                 ^[[1m^[[39m^[[22m^[[1mChunk Names^[[39m^[[22m
       ^[[1m^[[32mjs/bundle.app.js^[[39m^[[22m  5.05 MiB     ^[[1mapp^[[39m^[[22m  ^[[1m^[[32m[emitted]^[[39m^[[22m        app
   ^[[1m^[[32mjs/bundle.app.js.map^[[39m^[[22m  9.04 MiB     ^[[1mapp^[[39m^[[22m  ^[[1m^[[32m[emitted] [dev]^[[39m^[[22m  app
     ^[[1m^[[32mjs/bundle.clock.js^[[39m^[[22m   926 KiB   ^[[1mclock^[[39m^[[22m  ^[[1m^[[32m[emitted]^[[39m^[[22m        clock
 ^[[1m^[[32mjs/bundle.clock.js.map^[[39m^[[22m   1.2 MiB   ^[[1mclock^[[39m^[[22m  ^[[1m^[[32m[emitted] [dev]^[[39m^[[22m  clock
    ^[[1m^[[32mjs/bundle.report.js^[[39m^[[22m  5.37 MiB  ^[[1mreport^[[39m^[[22m  ^[[1m^[[32m[emitted]^[[39m^[[22m        report
^[[1m^[[32mjs/bundle.report.js.map^[[39m^[[22m  9.69 MiB  ^[[1mreport^[[39m^[[22m  ^[[1m^[[32m[emitted] [dev]^[[39m^[[22m  report
Entrypoint ^[[1mapp^[[39m^[[22m = ^[[1m^[[32mjs/bundle.app.js^[[39m^[[22m ^[[1m^[[32mjs/bundle.app.js.map^[[39m^[[22m
Entrypoint ^[[1mclock^[[39m^[[22m = ^[[1m^[[32mjs/bundle.clock.js^[[39m^[[22m ^[[1m^[[32mjs/bundle.clock.js.map^[[39m^[[22m
Entrypoint ^[[1mreport^[[39m^[[22m = ^[[1m^[[32mjs/bundle.report.js^[[39m^[[22m ^[[1m^[[32mjs/bundle.report.js.map^[[39m^[[22m
 [0] ^[[1mmulti webpack-hot-middleware/client?port=1337 ./bundle/bundle.source.js^[[39m^[[22m 40 bytes {^[[1m^[[33mapp^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
[16] ^[[1mmulti webpack-hot-middleware/client?port=1337 ./bundle/bundle.clocks.source.js^[[39m^[[22m 40 bytes {^[[1m^[[33mclock^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
[17] ^[[1mmulti webpack-hot-middleware/client?port=1337 ./bundle/bundle.reports.source.js^[[39m^[[22m 40 bytes {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
 [^[[1m./bundle/bundle.clocks.source.js^[[39m^[[22m] 178 bytes {^[[1m^[[33mclock^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
 [^[[1m./bundle/bundle.reports.source.js^[[39m^[[22m] 580 bytes {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
 [^[[1m./bundle/bundle.source.js^[[39m^[[22m] 845 bytes {^[[1m^[[33mapp^[[39m^[[22m} {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
 [^[[1m./lib/admin_plugins/index.js^[[39m^[[22m] 2.31 KiB {^[[1m^[[33mapp^[[39m^[[22m} {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m^[[1m^[[33m [1 warning]^[[39m^[[22m
 [^[[1m./lib/client/clock-client.js^[[39m^[[22m] 6.25 KiB {^[[1m^[[33mclock^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m^[[1m^[[33m [1 warning]^[[39m^[[22m
 [^[[1m./lib/client/index.js^[[39m^[[22m] 42.7 KiB {^[[1m^[[33mapp^[[39m^[[22m} {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m^[[1m^[[33m [1 warning]^[[39m^[[22m
 [^[[1m./lib/food/food.js^[[39m^[[22m] 25 KiB {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m^[[1m^[[33m [1 warning]^[[39m^[[22m
 [^[[1m./lib/profile/profileeditor.js^[[39m^[[22m] 30.1 KiB {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m^[[1m^[[33m [1 warning]^[[39m^[[22m
 [^[[1m./lib/report/predictions.js^[[39m^[[22m] 765 bytes {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
 [^[[1m./lib/report/reportclient.js^[[39m^[[22m] 34.6 KiB {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m^[[1m^[[33m [1 warning]^[[39m^[[22m
 [^[[1m./lib/report_plugins/index.js^[[39m^[[22m] 2.02 KiB {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [built]^[[39m^[[22m
 [./node_modules/webpack-hot-middleware/client.js?port=1337] ^[[1m(webpack)-hot-middleware/client.js?port=1337^[[39m^[[22m 7.58 KiB {^[[1m^[[33mapp^[[39m^[[22m} {^[[1m^[[33mclock^[[39m^[[22m} {^[[1m^[[33mreport^[[39m^[[22m}^[[1m^[[32m [bu    + 1002 hidden modules

^[[1m^[[33mWARNING in ./lib/admin_plugins/futureitems.js
Module Warning (from ./node_modules/eslint-loader/index.js):

/usr/home/nightscout/cgm-remote-monitor/lib/admin_plugins/futureitems.js
   60:24  warning  Function Call Object Injection Sink  security/detect-object-injection
  109:22  warning  Generic Object Injection Sink        security/detect-object-injection
  164:24  warning  Generic Object Injection Sink        security/detect-object-injection

~\~V 3 problems (0 errors, 3 warnings)```

**Comment by sulkaharo** [comment]
The messages you posted are just warnings - did you get actual errors that prevent running the software?

**Comment by yodax** [comment]
Nothing in the logs, but the server didn’t start. It tried to emit notifications via maker and pushover. Nothing else.

**Comment by sulkaharo** [comment]
Did you run `npm install` after pulling to ensure you got all the dependencies?

**Comment by yodax** [comment]
Something in my infrastructure caused this I think. After trying again, the same problem happened. I restarted HAProxy and the browser. Now it works :)

**Pull request merged**
