### PR TITLE
0.9.0 (Grilled Cheese)

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Nightscout Grilled Cheese - 0.9

  Over 1,000 commits from 39 contributors

  * Support for multiple active cgm uploaders (incuding battery level with alerts)
  * Token/Role based authorization
  * Bolus Calc
  * SAGE (Sensor Age)
  * IAGE (Insulin Cartridge Age)
  * Combo Bolus rendering (similar to Temp Basal rendering)
  * Insulin Pump monitoring
  * AP monitoring for OpenAPS and Loop
  * Alarm / Notification groups
  * Basal/Bolus/Carb stats added to day-by-day report
  * Extended Websocket API
  * Edit Mode
  * IOB from device status (MMConnect, OpenAPS, Loop, etc)
  * Deploy to Azure button
  * Performance and Bug fixes
  * Updated translations
  * new compare report see https://YOUR_SITE/report/compare.html
  
  For a complete list of closed issues and pull requests see:
  https://github.com/nightscout/cgm-remote-monitor/issues?q=milestone%3A0.9+is%3Aclosed

### CODE REVIEW

**Comment by connorscrew** [comment]
+1

**Comment by oamyoamy** [comment]
+1

**Comment by amazaheri** [comment]
👍

**Comment by ELUTE** [comment]
+1

**Comment by sulkaharo** [comment]
+1 LGTM

**Comment by MilosKozak** [comment]
👍

**Comment by loudestnoise** [comment]
👍🏻 for Grilled Cheese.

**Pull request merged**
