### PR TITLE
Raw data part 2

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Follow up to #386 that got merged before review/discussion was complete

The main issue remaining on #386 was if raw should always be display or only when there is noise.  To experiment with that I created a 3-way option

screen shot 2015-02-01 at 1 10 52 pm

After we get a chance to play with this in different situations it should be easier to come to a consensus on what we think is best for the community.

## A - Show Raw Always
a

## B - Show Raw when there is noise
b

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
@jimsiff, @YYGIRL, @ELUTE, @hackingtype1 continuing from #386 ...

**Comment by jasoncalabrese** [comment]
1 bonus of only showing raw when there is noise is the chart should paint faster since there will be much fewer dots.

I'm going to try to find a situation where raw would be useful and there and the noise level is clean.  If we can't find an example we can simplify things.

**Comment by hackingtype1** [comment]
By Dexcom's methods: Clean noise = Raw based EGV (displayed on receiver). 
The only time I'd show a raw value with a clean noise classification is if I was applying an entirely separate calibration algorithm to the raw value. 
Otherwise, the "raw" value being shown, while the noise is clean, is an incomplete (but derived from Dexcom's method) EGV calculation... 

-John

**Comment by jasoncalabrese** [comment]
Added Noise level to the tooltip to help understand when the raw data is displayed or not

screen shot 2015-02-04 at 5 02 15 pm

screen shot 2015-02-04 at 5 02 50 pm

**Comment by jasoncalabrese** [comment]
@jimsiff I noticed last night that sensor data isn't getting uploaded when Gap Sync is used, not sure if that explains anything you're seeing now

**Comment by jimsiff** [comment]
@trhodeos @jasoncalabrese Turns out the lack of noise was a layer 8 issue, solved when I upgraded the uploader feeding my raw site.  Noise is there with 0.1.12 via REST, and I like the tooltip update.  More real testing to follow now that I've debugged myself.

**Comment by trhodeos** [comment]
@jimsiff ok, cool. Glad to hear you got it working.

@jasoncalabrese could you open a PR or issue for the gapsync issue?

**Pull request merged**
