### PR TITLE
UPDATE

### PR DESCRIPTION
**Pull request by slakosko01**

### CODE REVIEW

**Comment by slakosko01** [comment]
Ok

**Comment by slakosko01** [comment]
Ok

**Comment by slakosko01** [comment]
Pull is ok

**Comment by unsoluble** [comment]
You've got the PR going in the wrong direction — make sure you've got your own repo on the left (as the base) when doing updates.

**Comment by sulkaharo** [comment]
Hi! It seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Please try again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings.

**Pull request closed without merging**
