### PR TITLE
Move app caching to a service worker

### PR DESCRIPTION
**Pull request by sulkaharo**
Remove the deprecated appcache & add new service worker to cache files

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 19
           

Coverage increased per file
===========================
+ lib/server/bootevent.js  1
         

Complexity increasing per file
==============================
- views/service-worker.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4937774&bid=16327407)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 14
           

Complexity increasing per file
==============================
- views/service-worker.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4937774&bid=16327407)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 9
           

Complexity increasing per file
==============================
- views/service-worker.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4937774&bid=16327407)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 4
           

Complexity increasing per file
==============================
- views/service-worker.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4937774&bid=16327407)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity increasing per file
==============================
- views/service-worker.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4937774&bid=16327407)

**Comment by sulkaharo** [comment]
Got LGTM from testers, merging

**Pull request merged**
