### PR TITLE
feat: display '50+ U', when there's no reservoir value for an Eros pod

### PR DESCRIPTION
**Pull request by jasoncalabrese**
image

depends on https://github.com/LoopKit/Loop/pull/947 and https://github.com/ps2/rileylink_ios/pull/522

### CODE REVIEW

**Comment by francescaneri** [comment]
great !

**Comment by PieterGit** [comment]
@jasoncalabrese @francescaneri What's the use of saying it's `50+ U` when it's unknown for this pump? Would `??? U` not be more appropriate? Nightscout should avoid to report false information to users.

**Comment by jasoncalabrese** [comment]
50+ U is the value that’s displayed in Loop and I’m pretty sure the Omnipod PDM.  The pods don’t provide a reservoir value until they are below 50, this aligns the display, and will hopefully limit confusion.

I’m still waiting on feedback for the other PRs that this depends on.

**Comment by francescaneri** [comment]
@PieterGit would be a great solution @ps2 @Kdisimone what do you think?

**Comment by sulkaharo** [comment]
Whichever UI is consistent with the PDM and Loop should obviously be mirrored here

**Comment by jasoncalabrese** [comment]
I just checked with the Zulip group:

> Joe Moran
> The "50+ U" format is used by the PDM & so we decided to do the same for Loop.

So I think that is the format we should display in NS too

**Comment by t1dloop** [comment]
Thanks @jasoncalabrese

**Comment by Kdisimone** [comment]
Working great for us, thank you!

**Comment by PieterGit** [comment]
@jasoncalabrese Can you confirm that this ready to merge? 
@Kdisimone Thanks for testing. 

Should we completely mimic the behaviour (that is: round at 1 unit; don't show exact number if `< 5`). I wouldn't have mind rounding to complete units as default behavior for all pumps. Thoughts?

**Comment by jasoncalabrese** [comment]
I'm going to merge, we're pretty confident the `manufacturer` and `model` fields will get into the Loop mainline after some additional testing that will be easier after this gets to `dev`

**Comment by francescaneri** [comment]
@jasoncalabrese should it be activated automatically?

**Comment by muttech** [comment]
@jasoncalabrese Not sure if this should be opened as an issue or can be tracked here, but there is a case where the reservoir value is sent, and then not sent in a subsequent upload.  

Here are 3 entries - the first has the reservoir value, the second doesn't, the third does.  These are in time sequence (although not one after another).

` "pump": {
        "manufacturer": "Insulet",
        "pumpID": "1F0513A7",
        "reservoir": 45.65,
        "suspended": false,
        "model": "Eros",
        "secondsFromGMT": -18000,
        "clock": "2019-05-09T23:56:46Z",
        "bolusing": true
    },
  "pump": {
        "suspended": false,
        "manufacturer": "Insulet",
        "model": "Eros",
        "pumpID": "1F0513A7",
        "clock": "2019-05-10T00:21:35Z",
        "bolusing": true,
        "secondsFromGMT": -18000
    },
   "pump": {
        "manufacturer": "Insulet",
        "clock": "2019-05-10T00:36:36Z",
        "suspended": false,
        "reservoir": 44.8,
        "model": "Eros",
        "bolusing": true,
        "pumpID": "1F0513A7",
        "secondsFromGMT": -18000
    },`

This caused Nightscout to revert back to 50+ U as pump.reservoir isn't set:
image

**Comment by jasoncalabrese** [comment]
gaps in the pump timestamps, nothing between them?

“clock": "2019-05-09T23:56:46Z"
"clock": "2019-05-10T00:21:35Z"
"clock": "2019-05-10T00:36:36Z"

I was hoping that the pump clock in the device status was the time the info was read, but it’s the time of upload.  Each upload from loop, it looks for a reservoir value within the last 15m.

Some more info https://github.com/LoopKit/Loop/pull/947

**Comment by muttech** [comment]
> gaps in the pump timestamps, nothing between them?
> 
> “clock": "2019-05-09T23:56:46Z"
> "clock": "2019-05-10T00:21:35Z"
> "clock": "2019-05-10T00:36:36Z"
> 
> I was hoping that the pump clock in the device status was the time the info was read, but it’s the time of upload. Each upload from loop, it looks for a reservoir value within the last 15m.
> 
> Some more info [LoopKit/Loop#947](https://github.com/LoopKit/Loop/pull/947)

There are other values between them - I omitted them (partly due to manually pulling them from the mLab web interface) and partly for readability:

 `"pump": {
        "pumpID": "1F0513A7",
        "bolusing": true,
        "model": "Eros",
        "secondsFromGMT": -18000,
        "clock": "2019-05-10T00:01:42Z",
        "manufacturer": "Insulet",
        "suspended": false
    },`

`  "pump": {
        "suspended": false,
        "clock": "2019-05-10T00:06:45Z",
        "secondsFromGMT": -18000,
        "bolusing": true,
        "manufacturer": "Insulet",
        "model": "Eros",
        "pumpID": "1F0513A7"
    },`

`    "pump": {
        "suspended": false,
        "bolusing": true,
        "clock": "2019-05-10T00:11:44Z",
        "manufacturer": "Insulet",
        "model": "Eros",
        "secondsFromGMT": -18000,
        "pumpID": "1F0513A7"
    },`

`  "pump": {
        "bolusing": true,
        "secondsFromGMT": -18000,
        "pumpID": "1F0513A7",
        "model": "Eros",
        "clock": "2019-05-10T00:16:49Z",
        "suspended": false,
        "manufacturer": "Insulet"
    },`

`"pump": {
        "suspended": false,
        "manufacturer": "Insulet",
        "model": "Eros",
        "pumpID": "1F0513A7",
        "clock": "2019-05-10T00:21:35Z",
        "bolusing": true,
        "secondsFromGMT": -18000
    },`

`   "pump": {
        "clock": "2019-05-10T00:26:43Z",
        "manufacturer": "Insulet",
        "bolusing": true,
        "suspended": false,
        "model": "Eros",
        "secondsFromGMT": -18000,
        "pumpID": "1F0513A7"
    },`

`  "pump": {
        "clock": "2019-05-10T00:31:31Z",
        "model": "Eros",
        "manufacturer": "Insulet",
        "pumpID": "1F0513A7",
        "secondsFromGMT": -18000,
        "suspended": false,
        "bolusing": true
    },`

`"pump": {
        "manufacturer": "Insulet",
        "clock": "2019-05-10T00:36:36Z",
        "suspended": false,
        "reservoir": 44.8,
        "model": "Eros",
        "bolusing": true,
        "pumpID": "1F0513A7",
        "secondsFromGMT": -18000
    },`

**Pull request merged**
