### PR TITLE
Add more Hebrew localizations

### PR DESCRIPTION
**Pull request by kretch**
Changed a few numbers to words in the Hebrew translation

### CODE REVIEW

**Comment by sulkaharo** [comment]
Hebrew is still missing a huge amount of localizations with this PR, would you have the time to look at the rest of the missing text as well?

**Comment by kretch** [comment]
Yes, I plan to comlpete the rest. I just wanted to try out the process
first since it's my first PR

**Comment by PieterGit** [comment]
@kretch , ok, please do. Make sure you look at the spacing and use the same syntax as the other lines. If you add your changes quickly they will be part of the 0.10.3 release.  If you need help, ask around at https://gitter.im/nightscout/public

**Comment by sulkaharo** [comment]
@kretch we're very close to making the release - it'd be awesome to get more Hebrew translations in, so please if you have the time, push some more things in :)

**Comment by kretch** [comment]
@sulkaharo I'll be spending the day filling in as many entries as I can in the hebrew translation. 
I have a newbie question though:
- In order to focus on just those entries that are missing the hebrew translation, I vi-hacked the file and extracted the entries missing hebrew translations. Would it be possible for me to provide just the missing entries, and have somebody who knows js merge it with the existing array of translations? If this is easy to do, great. If not, I'll just fill in the missing parts manually.

**Comment by PieterGit** [comment]
Clsoing. Fixed with https://github.com/nightscout/cgm-remote-monitor/pull/3754

**Pull request merged**
