### PR TITLE
Always return the last Cal entry (don't worry about how old it might be)

### PR DESCRIPTION
**Pull request by jasoncalabrese**
Also some refactoring by using async.parallel to make multiple ongo requests at once.

Bonus fix: also check `env.DISPLAY_UNITS` if the `units` query string param isn't set

@bewest @ELUTE @jimsiff

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
@jimsiff, @ELUTE, I talked to @YYGIRL about some users are burning through data partially due to the extra `cal` data returned from `/pebble`.  We merged in a fix (6357212222eb0a6080f71c34bd76d6e4262dd83d) that selectively chooses the fields that are needed. The plan is to have some of those users that are most concerned about data usage to start using `dev` after this PR is merged.  Then they can also help test before we release Enchilada to master.

**Comment by jimsiff** [comment]
JSON payload is reduced about 40% but TCP and HTTP protocol overhead drops the net savings to 20%.  Gzip encoding may help some more.

**Comment by jasoncalabrese** [comment]
thanks for testing @jimsiff did you also take a look at the main web monitor page, in addition to `/pebble`?

**Comment by jasoncalabrese** [comment]
I just added gzip compression to everything, with that we're down to 255 bytes (455 with http overhead)

**Pull request merged**
