### PR TITLE
Prevent NPE

### PR DESCRIPTION
**Pull request by MilosKozak**

### CODE REVIEW

**Review by bewest — APPROVED** [review]
Thanks; how are there null values in this array?  I guess the early return helps performance.
Style-wise, is there a different indentation, and perhaps adding braces inline: `if (object) { return false; }`.

LGTM.

**Comment by MilosKozak** [comment]
no idea how is possible to have null there but it's happening to me regularly

**Comment by dlvoy** [comment]
I experienced the same issue few times already, @sulkaharo it is the exact same spot i got in December

**Comment by sulkaharo** [comment]
I read through all the code paths that make changes to the array and can't find what could cause the invalid object there. I don't think adding the null check is the right fix, as it just patches over the issue and from what I can see, Nightscout must be in some very inconsistent state if this error is triggered, at which point it should be restarted. Hiding the error like here is likely to just cause the site to start returning wrong data over the API and potentially be dangerous if this causes mispresenation of data.

**Comment by justmara** [comment]
this bug is really annoying. since moving from aaps 2.8 to 3.0 my ns were crashing every minute until I applied this fix.
BUT also need to mention, that version 14.2.2 were working fine without any crashes.
and my log shown that crash ocurred in DEDUPE function, but the main problem is that it were checking OLD data:
```
2022-06-17T15:27:13.756568+00:00 app[web.1]: got data-received event, requesting reload
2022-06-17T15:27:13.782749+00:00 app[web.1]: [35mDEDUPE: [0mExact match
2022-06-17T15:27:13.807252+00:00 app[web.1]: Got results {
2022-06-17T15:27:13.807254+00:00 app[web.1]:   _id: 62ab6103f917fb0004c39e93,
2022-06-17T15:27:13.807255+00:00 app[web.1]:   eventType: 'Carb Correction',
2022-06-17T15:27:13.807255+00:00 app[web.1]:   carbs: 3,
2022-06-17T15:27:13.807256+00:00 app[web.1]:   created_at: '2022-06-16T16:57:28.000Z',
2022-06-17T15:27:13.807256+00:00 app[web.1]:   date: 1655398648000,
2022-06-17T15:27:13.807256+00:00 app[web.1]:   isSMB: false,
2022-06-17T15:27:13.807257+00:00 app[web.1]:   notes: 'конфета',
2022-06-17T15:27:13.807257+00:00 app[web.1]:   NSCLIENT_ID: '1655398659021',
2022-06-17T15:27:13.807257+00:00 app[web.1]:   isValid: true
2022-06-17T15:27:13.807258+00:00 app[web.1]: }
2022-06-17T15:27:13.810877+00:00 app[web.1]: Got results null
2022-06-17T15:27:13.812974+00:00 app[web.1]: /app/node_modules/mongodb/lib/utils.js:106
2022-06-17T15:27:13.812976+00:00 app[web.1]:       throw err;
2022-06-17T15:27:13.812976+00:00 app[web.1]:       ^
2022-06-17T15:27:13.812977+00:00 app[web.1]: 
2022-06-17T15:27:13.812977+00:00 app[web.1]: TypeError: Cannot read property '_id' of null
2022-06-17T15:27:13.812977+00:00 app[web.1]:     at hasId (/app/lib/server/cache.js:47:41)
2022-06-17T15:27:13.812978+00:00 app[web.1]:     at arrayFilter (/app/node_modules/lodash/lodash.js:582:11)
2022-06-17T15:27:13.812978+00:00 app[web.1]:     at Function.filter (/app/node_modules/lodash/lodash.js:9199:14)
2022-06-17T15:27:13.812979+00:00 app[web.1]:     at filterForAge (/app/lib/server/cache.js:46:16)
2022-06-17T15:27:13.812979+00:00 app[web.1]:     at mergeCacheArrays (/app/lib/server/cache.js:37:23)
2022-06-17T15:27:13.812979+00:00 app[web.1]:     at Stream.dataChanged (/app/lib/server/cache.js:83:30)
2022-06-17T15:27:13.812980+00:00 app[web.1]:     at Stream.emit (events.js:314:20)
2022-06-17T15:27:13.812980+00:00 app[web.1]:     at /app/lib/server/websocket.js:223:29
2022-06-17T15:27:13.812981+00:00 app[web.1]:     at executeCallback (/app/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
2022-06-17T15:27:13.812982+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:102:55)
2022-06-17T15:27:13.955196+00:00 heroku[web.1]: Process exited with status 1
2022-06-17T15:27:14.034843+00:00 heroku[web.1]: State changed from up to crashed
```
look at event and message's dates: `2022-06-17T15:27:13.807256+00:00 app[web.1]:   created_at: '2022-06-16T16:57:28.000Z',`

**Comment by bewest** [comment]
This update looks relevant: https://github.com/nightscout/cgm-remote-monitor/pull/7468

**Comment by sulkaharo** [comment]
Closing given this was fixed in another PR

**Pull request closed without merging**
