### PR TITLE
Update pebble.js

### PR DESCRIPTION
**Pull request by eksugars**

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Looks like you're using an old version of master with a manually edited version of `pebble.js`  Battery is handled a different way than that now.

Are you trying to update to the current version or test out the beta?

**Comment by eksugars** [comment]
yes, that what is what I have been told Jason.  And It was so hard for me the first time, I never touched it.  I never needed the latest and greatest.  Just a blood sugar number on the computer and on my pebble.  then I got to a point where the android screen would get funky lines  (FB post)  They told me my uploader was out of date.  Nervous but the uploader app was doable.  Now I am told that the version i am using is STILL old and that is why my pebble won't work.  I was up way too late trying to figure this out.  We need a watch working by teacher meetings on Wednesday so nurse and teacher see what they need to see.  IT was such a mess last year that one of the main contributors from Dallas had to take over remotely and figure it all out for me.  Maybe that is why there is manually edited stuff.  Any help is appreciated.

**Comment by jasoncalabrese** [comment]
Look like you updated your fork and your master branch is now current, were you able to get that deployed?

**Comment by ELUTE** [comment]
I walked her through getting it done so she is good now :)

**Comment by jasoncalabrese** [comment]
:+1:

**Pull request closed without merging**
