### PR TITLE
Resolve object injection sink issues reported in Codacy

### PR DESCRIPTION
**Pull request by jakobsandberg**
According to Codacy we have many instances of object injection sink issues. This is caused by loose use of bracket notation when accessing items of objects (or arrays). You can read more here: https://github.com/nodesecurity/eslint-plugin-security/blob/master/docs/the-dangers-of-square-bracket-notation.md

This PR resolves those issues with explicit type conversions.

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 167
- Added 13
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4814068&bid=16010437)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 181
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4814068&bid=16010437)

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 169
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4814068&bid=16010437)

**Comment by sulkaharo** [comment]
Based on the Codacy description of why the [] notation is problematic, wrapping the inputs to String() etc doesn't actually resolve the underlying problem (of inputs being able to overwrite undesired properties), just hides the error due to ESLint seeing the data going through a wrapper function. Or am I missing something?

**Comment by sulkaharo** [comment]
Closing, please reopen if you think my comment above wasn't correct.

**Pull request closed without merging**
