### PR TITLE
Padding on hamburger button

### PR DESCRIPTION
**Pull request by rkresha**
On hover, scroll bars appear. Adjust from 10px to 15px on padding-right

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Did you still get the scrollbars on dev without this?  If so what browser.  I do remember seeing that bug but thought it was fixed along with some other changes.

**Comment by rkresha** [comment]
Yes with chrome (multiple versions). Forked from dev two days ago so I was working off a current version of the branch. Didn't try any other browsers. Still got it with 13px, so decided to round up to 15 and seems fine now.

**Comment by rkresha** [comment]
The treatment bubbles causes the scrollbars to come up as well, so my adjustment is only half of the battle. Fix will need to address bubble pop ups

**Comment by MilosKozak** [comment]
send screenshot what it does

**Comment by rkresha** [comment]
image

**Comment by rkresha** [comment]
Hovering on another comment a little older shows as expected, no scroll bars
image

**Comment by rkresha** [comment]
Hovering over the hamburger button yields similar results. Perhaps this PR closes and we open it as an issue because this is a work around for the settings button not freaking out not for the treatment bubble issue

**Comment by rkresha** [comment]
Closing this PR in favor of adding it as an issue. #1788

**Pull request closed without merging**
