### PR TITLE
Add serverTimeEpoch, needed for wifi uploader

### PR DESCRIPTION
**Pull request by skjelland**

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Not able to parse the iso date string?

**Comment by skjelland** [comment]
Possibly, but when doing upload in arduino code it would be nice to get
both since it has to fetch the current time anyway...
24. des. 2015 05.20 skrev "Jason Calabrese" <notifications@github.com>:

**Comment by bewest** [comment]
How would you feel about naming it `serverTimeEpoch` instead of `serverTimeNum`?

**Comment by skjelland** [comment]
Perfect, @bewest :)

**Comment by skjelland** [comment]
change commited

**Comment by bewest** [comment]
Great, thanks.

**Pull request merged**
