### PR TITLE
allow API to search things better

### PR DESCRIPTION
**Pull request by bewest**
This allows a query such as this to search for events of hypoglycemia for
example:
```
curl -g localhost:3434 \
     /api/v1/entries   \
     '?find[sgv][$lte]=70&find[sgv][$gte]=20&count=1000
```
It's possible to construct most mongo queries by url encoding the query string.
In this instance, mongo performs poorly when searching for lte/gte for strings.
In order for ranged queries to perform properly, the query parameters must be
set to integer type.  There is a quick and ugly helper to ensure that some sgv
queries will be respected as integer searches.

### CODE REVIEW

**Comment by bewest** [comment]
```bash

$ curl -g localhost:3434/api/v1/entries'?find[dateString][$lte]=2015-01-32&find[dateString][$gte]=2015-01-00&count=10000'  | wc -l && echo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  559k    0  559k    0     0   187k      0 --:--:--  0:00:02 --:--:--  187k
9813

```

**Comment by jasoncalabrese** [comment]
Cool, very useful

**Comment by jasoncalabrese** [comment]
Looks like lots of data is getting filtered out, missing `cal` and `sensor` entries and filed like `unfiltered`, `filtered`, `slope`, `mbg`, `type`, etc, etc

**Comment by jasoncalabrese** [comment]
and would be nice if `http://localhost:1337/api/v1/entries.json?find[mbg]&count=100` or `http://localhost:1337/api/v1/entries.json?find[type][mbg]&count=100` would work

**Comment by bewest** [comment]
`?find[type]=mbg` will now search exclusively for `mbg` records.  Also json responses will include `mbg` and other data elements, so long as they have a `type` property.

I strongly encourage using iso8601 date encoding to make the date filtering features work with ease.

**Comment by jasoncalabrese** [comment]
I agree on date format, I don't think the api really used yet so it's a good fine to change.  Maybe add a param to return UTC timestamps?

**Comment by jasoncalabrese** [comment]
Works good should we do something with the date format here (export only) or wait till we do something bigger?

**Comment by jasoncalabrese** [comment]
Lets look at date formatting outside of this, going to merge now

**Pull request merged**
