### PR TITLE
Retro at specific time

### PR DESCRIPTION
**Pull request by alimhassam**
Very early preview, still WIP. 

Allow jumping to the retro view at a specific time. This is very useful for reviewing openaps decisions.

 - Double clicking on a point on the chart will move the retro view at the time of that point. 
 - Clicking on the current time also allows to enter a time and move the retro view at that time. 

This is very crude right now. TODO:
 -  I want to make the time selection better. It's just a javascript time string at the moment. Maybe some kind of date picker widget?? Looking for suggestions, please.
 - I also want to add +5min and -5 min buttons. 

I'm just raising the pr for discussion on whether this is a good feature and the approach is okay.

### CODE REVIEW

**Comment by alimhassam** [comment]
need to test on mobile

**Comment by alimhassam** [comment]
ah oops i merged the autotune branch here by error.

**Comment by PieterGit** [comment]
@alimhassam can you give an update on this PR? It seems quite for almost half a year. Should I close it, or do you need help?

I think that if we are able to go back to a retro time, it should be possible to stop updates on the browser somehow. Otherwise it will move to the current cgm or pump basal info if it appears. On the other hand, if you're going low or have a hypo it should somehow be clear to the user, because acting on a hypo or a downward cgm now is more important than looking at retro cgm values.

**Comment by alimhassam** [comment]
@PieterGit i just saw your message, and remembered this pull request. We are already able to go back in time by clicking on the mini 2 day chart at the bottom. 

Thispr just allows to do this more precisely, either by double clicking on a point in the graph, or by entering a time manually by clicking on the clock. It fits my needs so i've been using it this way for 7 months, but ideally the interface to pick the time should be better.

If this is useful to others then we can keep the functionality available, if not i'm okay to just close the pull request and only keep this on my local branch.

Unfortunately i'll be quite busy until ~september so i won't have time to polish this up unless only small changes are needed.

**Comment by PieterGit** [comment]
@alimhassam i'm putting it for the next 0.11 release. I don't have a problem with this PR until september and I just put the `help wanted` tag on this. If there is no activity in september I will close this PR.

**Comment by sulkaharo** [comment]
Closing as this needs reimplementation with the new renderer code. Love the idea, please refactor and complete this! :)

**Pull request closed without merging**
