### PR TITLE
Clock colors and trends

### PR DESCRIPTION
**Pull request by unsoluble**
Adds /clock-color.html, an alternative to /clock.html. This one changes background color to reflect the current BG range, and adds a trend arrow. Page scales nicely to fit most browser views.

Now properly grabs BG thresholds from the user profile.

uxqenu8g

### CODE REVIEW

**Comment by MilosKozak** [comment]
/api/v1/status.json

and please keep the backgroud black

**Comment by unsoluble** [comment]
Ahh, thanks for that — I'm new to APIs, wasn't sure where to look. Will play around with that soon.

Note that I've moved this code to a new page, at clock-color.html, so that the original black-background view is untouched.

**Comment by tomas69** [comment]
background black colored numbers

**Comment by unsoluble** [comment]
That'd be another way of doing it, sure; I prefer using the bg as color indicator, for better visibility from across the room.

**Comment by jasoncalabrese** [comment]
Why was `static/images/favicon.ico` removed seems to still be used in some places

**Comment by unsoluble** [comment]
Ohhh you know why, I had replaced it with my own local version (just to maintain a separate aesthetic for our family site), and then when cleaning up for the PR I think it got cleared out accidentally with all my other little non-public tweaks. I'll put the original back and re-commit. :)

**Comment by jasoncalabrese** [comment]
Thanks, you should be able to just add the back to your branch

**Comment by jasoncalabrese** [comment]
I like the svg arrows, the unicode arrows we use for the main view have problems on some devices, it would be great to replace them with the sgvs.

**Pull request merged**
