### PR TITLE
Fix bg units in updated Loop pill

### PR DESCRIPTION
**Pull request by dm61**

### CODE REVIEW

**Comment by francescaneri** [comment]
@dm61 sensitivity can also be added? Thanks Matteo

**Comment by dm61** [comment]
@francescaneri Loop currently does not upload ISF to NS, so we are not able to add that to the pill. I've added min-max and eventual predicted bg, with units correctly matching user preference. That's about as much as we can show in the pill with the current version of Loop.

**Comment by sulkaharo** [comment]
@dm61 has this been tested / is this ready for merge?

**Comment by dm61** [comment]
@sulkaharo yes, this one is ready to merge - thanks

**Pull request merged**
