### PR TITLE
Fix #5188 - move predictions to bundle and don't render chart on predictions offset change

### LINKED ISSUE #5188: Unchecking "Predictions" in /report triggers rendering
**Describe the bug**

"Predictions" checkbox behaves like "Show" button.

**To Reproduce**
1. Open Reports page.
2. Click on "Predictions" checkbox. (The other "Display" options are OK.)
3. See error: "Rendering..." shows up.

**Expected behavior**
Only the "Show" button should trigger rendering.

**Your setup information**
- What version of Nightscout? - 0.12.6-dev (git 9c42fed)
- What type of CGM, and how do you get your data there? - N/A
- Is your issue specific to a browser (Firefox/Safari/Chrome?) or a device (Android phone, etc.)? - No, seen with Safari, Firefox, derivatives on MacOSX, Linux, Android.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
This fixes #5188 issue and also predictions are moved to bundle

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/report/predictions.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4752180&bid=15851853)

**Comment by sulkaharo** [comment]
Great changes, but breaks predictions reporting :D Check https://github.com/nightscout/cgm-remote-monitor/blob/master/lib/report_plugins/daytoday.js#L366 which depended on the earlier method of loading the javascript, which set predictedOffset in global scope. Would love if all the code moved to bundles, though. You can repro the issue by enabling predictions in the Day to Day report.

**Comment by Bartlomiejsz** [comment]
Whoa, I have no idea why I didn't thought about places where this is used, not only set :D will fix that

**Comment by jasoncalabrese** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/report/predictions.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Nightscout/cgm-remote-monitor/pullRequest?prid=4752180&bid=15851853)

**Comment by Bartlomiejsz** [comment]
@sulkaharo done :)

**Pull request merged**
