### PR TITLE
Loopalyzer - The Loop visualizer

### PR DESCRIPTION
**Pull request by lixgbg**
Hello

This is a new report to help visualise how Loop works to make it easier to adjust the ratios that affect its performance. Loopalyzer adds an additional tab to Nightscout reports. It does work with some other setups as well (closed and open loop and non loop, your mileage may vary depending on uploader) but is intended for Loop users.

To explain its purpose and how to use it please see this short introduction -> https://youtu.be/4-yXkzNqTE0

This feature was submitted to master branch a couple of weeks ago. I cancelled it and this is an improved version, and submitted to dev branch.

### CODE REVIEW

**Comment by MilosKozak** [comment]
niceeeee

**Comment by PieterGit** [comment]
@lixgbg Nice PR. My npm update created a conflict. Is this ready to merge? 

I don't know if Loopalyzer is a good name because I thought it was specific for Loop.
Perhaps "Analyze APS" or something else is better.

**Comment by PieterGit** [comment]
@lixgbg Thinking about a better functional name. I would like to have the names of the tabs to be clear for people. Isn't your loopalyzer more of a `Daily (detailed)`  view of the Nightscout data? 

@MilosKozak or @sulkaharo or @jasoncalabrese : what do you think about the right name for this view?

**Comment by lixgbg** [comment]
@PieterGit I did an npm update in an attempt to resolve the conflicts. But there is still a number of them, apparently because I based my code on 0.10.3-dev from 2018-03-04 and the latest is 2018-06-24. How do you resolve these conflicts in the most efficient way?

**Comment by lixgbg** [comment]
@PieterGit @MilosKozak @sulkaharo @jasoncalabrese 
Initially I developed this view to enable a better visualization of the data that Loop uploads to NS and makes its decisions on, hence the name Loopalyzer. I then improved it and tested with other uploaders and attempted to make it as tolerant as possible to various data, and to missing data. So now it's more versatile than its original purpose. Still it's most useful if data such as carbs (and COB) and insulin (and IOB) is uploaded to NS, which is not the case if using a plain NS setup, e.g. using only Dexcom.

Feel free to be creative with naming, given this background info.

**Comment by lixgbg** [comment]
@PieterGit did you have a chance to look at and resolve the conflict for this PR and the 3179?

**Comment by PieterGit** [comment]
@lixgbg No not yet. We first need to get 0.10.3 out of the door and I think this PR needs extra work/thought before implementing it.  We also need to have consensus on the view and the name we present to the users. My best guess for now is that this is a "Daily (detailed)" view which is a bit more clear to novice users than Loopalyzer. But I'm very open for better names and discussion on that subject.

So I'm hoping other core committers like @MilosKozak @sulkaharo @jasoncalabrese can join this discussion.  They are all very busy these days.

**Comment by lixgbg** [comment]
@PieterGit Yes it should be ready (unless there are some criteria for merging I’m not aware of).

**Comment by PieterGit** [comment]
@lixgbg I resolved the conflicts and merged it to https://github.com/nightscout/cgm-remote-monitor/tree/wip/loopalyzer 

I noticed that both the Loopalyzer view and the Day to Day header showed up:
image

I will test further later this week. Please PR new commits to `wip/loopalyzer`.

**Comment by lixgbg** [comment]
@PieterGit Thanks for the merge. Interesting that both headers showed up. I have been running Loopalyzer for many weeks now and have never seen that. Do you know if anything fundamental has changed in the Reports in 0.11 (I have been on 0.10.3 dev)?

**Comment by PieterGit** [comment]
@jasoncalabrese @MilosKozak @sulkaharo @jpcunningh Can you please review this PR of @lixgbg and tell me if you think we can merge this for the 0.11 release?

**Comment by jpcunningh** [comment]
@PieterGit, I've played with it for about 45minutes this evening it looks and feels solid to me.  We are using OpenAPS, and the plugin appears to be pulling the data in correctly.

I also tested as many boundary conditions as I could think of such as using the buttons to go to days before the From / To settings, going past the current day, etc.  Also saw no errors on the console.

@lixgbg, very nice addition! Thank you!

**Comment by bewest** [comment]
Very cool report.

**Comment by PieterGit** [comment]
This PR has been integrated with the https://github.com/nightscout/cgm-remote-monitor/tree/needs_testing 
branch. Please test that branch and report at this issue or at nightscout/cgm-remote-monitor#4169

**Comment by PieterGit** [comment]
@lixgbg thanks for your hard work on this PR.

This PR has been tested as part of the `need_testing` branch of https://github.com/nightscout/cgm-remote-monitor/pull/4169
@blocklist_twitter @balshor @sulkaharo @jpcunningh @unsoluble @veryfancy @balshor @tynbendad have run this PR for a week.
Several users reported succes with this new report and really like it! No negative stuff popped up. Gitter link: https://gitter.im/nightscout/public?at=5c2f33d12863d8612bd78eb0

If you encounter success or failure with this PR, please reopen the issue and share your findings.

Closing PR, will be merged with https://github.com/nightscout/cgm-remote-monitor/pull/4169

**Comment by lixgbg** [comment]
Thanks, sounds good! Where is a good place to add some documentation on it? I made a Youtube video a few months ago (at the top of this PR) but it would make sense to also have something in text. I haven't found any documentation for any of the Reports so far. Is there a place for that?

**Pull request closed without merging**
