### PR TITLE
Update language.js

### PR DESCRIPTION
**Pull request by martijnmcb**
Almost completed basic dutch translation.  fine tuning and spell checking needed.

### CODE REVIEW

**Comment by MilosKozak** [comment]
error on line 5118 .... extra colon

**Comment by martijnmcb** [comment]
Hi, MilosKozak, i corrected the type. What do i do now?

**Comment by MilosKozak** [comment]
another error line 5353

**Comment by MilosKozak** [comment]
line 6057

**Comment by MilosKozak** [comment]
one more 6135

**Comment by MilosKozak** [comment]
:+1:

**Comment by martijnmcb** [comment]
Thanks

**Pull request merged**
