### PR TITLE
Fix Database Insert Error Handling

### PR DESCRIPTION
**Pull request by jpcunningh**
This is an update to #3751 to provide an error back to the client when database inserts fail.

### CODE REVIEW

**Comment by jpcunningh** [comment]
I'm testing the error code and will post here when complete.

**Comment by PieterGit** [comment]
@jpcunningh LGTM. I assume the trace with linenumbers will be visible in the console log, so that you can identify the exact exception.  Most of the error lines have the exact same text. Let's see if @sulkaharo or @jasoncalabrese have time to review it. If people report mongo errors at https://gitter.im/nightscout/publicpossible we can ask them to test the new code. I'll merge to dev if no response within a week, because it's a small fix that looks ok. Did you test with a full mongodb?

**Comment by jpcunningh** [comment]
@PieterGit, good catch. I modified to have unique error log messages.

Rather than fill up my production mongodb, I made a test branch that programmatically forced an "error" so it flowed through the rest of the data flow to the client.

I'm not sure how long it will be before my database naturally fills up again. It's probably in the range of 2-3 weeks.

**Comment by PieterGit** [comment]
Merged to dev. If there is somebody on https://gitter.im/nightscout/public with a full MongoDB we'll ask to test this new feature.

**Comment by PieterGit** [comment]
The user documentation for this feature can be improved. I logged issue nightscout/documentation#2 for that.

**Pull request merged**
