### PR TITLE
remove python and python-software-properties from setup.sh

### PR DESCRIPTION
**Pull request by PieterGit**
As far as I see in the current codebase there are no references to python. 

Should be tested with reinstall on clean pi3 install.

Fixes https://github.com/nightscout/cgm-remote-monitor/issues/3577

### CODE REVIEW

**Comment by viq** [comment]
Do you want specifically tests on pi/raspian/debian, or any environment without python would work for you?

**Comment by PieterGit** [comment]
@viq The issue was with RPI3, see https://github.com/nightscout/cgm-remote-monitor/issues/3577  .  I can't find any python dependencies, except for one Travis script, but that won't harm normal install by users. Because I remove python scripts I think any debian/ubuntu based install without python install should be able to test this.

**Comment by PieterGit** [comment]
This PR has been integrated with the https://github.com/nightscout/cgm-remote-monitor/tree/needs_testing 
branch. Please test that branch and report at this issue or at nightscout/cgm-remote-monitor#4169

**Comment by PieterGit** [comment]
This PR has been tested as part of the `need_testing` branch of https://github.com/nightscout/cgm-remote-monitor/pull/4169
@blocklist_twitter @balshor @sulkaharo @jpcunningh @unsoluble @veryfancy @balshor @tynbendad have run this PR for a week.
No negative stuff popped up. Gitter link: https://gitter.im/nightscout/public?at=5c2f33d12863d8612bd78eb0

Unfortuately probably nobody tested this PR exactly, but from a code perspective this should work. Needs to be test on a raspberry pi installation but there is currently no volunteer to do so.
If you encounter success or failure with this PR, please reopen the issue and share your findings.

Closing PR, will be merged with https://github.com/nightscout/cgm-remote-monitor/pull/4169

**Pull request closed without merging**
