### PR TITLE
update readme to include all the env var's that are used to configure the server

### PR DESCRIPTION
**Pull request by jasoncalabrese**

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
good catch @jjmason

**Comment by bewest** [comment]
Here is preview link: https://github.com/nightscout/cgm-remote-monitor/blob/wip/readme-env-update/README.md

I added some links to the update-fork, mongostring, and configure tools.
I also created two tables with the things people might be interested in up front and center, clearly marked the one REQUIRED thing, and the rest of the optional things.

**Comment by jasoncalabrese** [comment]
nice, some of the env's are `code` other just CAPS
Core should probably be first too

**Comment by jasoncalabrese** [comment]
I'm going to update now

**Comment by bewest** [comment]
Looks ok, I think the labs/features table should be first, based on how often it's likely to be used.
The only one required environment variable is covered in detail in other places, so I'm guessing people are going to want the labs/features table most often.

**Comment by jasoncalabrese** [comment]
My thinking is that it would help someone get started it they saw the required/core vars first, but you have a good point too.  Either way works for me.

**Comment by bewest** [comment]
Looks like the `code fences` make the thing do awful things with the scrollbars.

**Pull request merged**
