### PR TITLE
Alexa multilingual changes: Blutzucker und blutzucker

### PR DESCRIPTION
**Pull request by mrksmaurer**
Blutzucker und blutzucker hinzugefügt

### CODE REVIEW

**Comment by PieterGit** [comment]
@mrksmaurer Please target changes at the dev branch instead of the master branch. Are you sure this is the way multilingual changes to Nightscout should be implemented? 

@veryfancy  or other Alexa users, can you please take ownership of the Alexa issues/PR's?

Targeting this change to 0.12 for now. If the discussion is done and this is the way it should be implemented it can be merged to 0.11.

**Comment by PieterGit** [comment]
@mrksmaurer or @veryfancy . Can you give an update. If no clear update or concensus I will close this PR.

**Comment by tanja3981** [comment]
I think this use case (translatable metrics) are better solved otherwise than adding those metric hardcoded to the code. With other language we would have to add "blood glucose" accordingly. 
I think a better way would be do use the alexa skill synonyms for it, but I'm biased due to my PR (#4040 ) for that. ;-)

**Comment by PieterGit** [comment]
@mrksmaurer @veryfancy @tanja3981 Is this PR still relevant?

@inventor96 Is there a generic way this can be implemented for several languages?

If relevant, please reopen, rebase on the dev branch, and resolve the merge conflicts.

Closing PR for now.

**Comment by inventor96** [comment]
@mrksmaurer @veryfancy @tanja3981 @PieterGit Per the changes made in #4980, the best way to add support for another language is in the virtual assistant configuration in the respective console (Alexa or Google Home/DialogFlow). As @tanja3981 said, synonyms are helpful, but one *really should* setup the additional language in the respective console first, and then use the synonyms. I've added a section in both the Alexa and Google Home documentation called "Adding support for additional languages" that outlines the process.

**Pull request closed without merging**
