### PR TITLE
auto ack alarms when going back into range or when the a cgm error corrects

### PR DESCRIPTION
**Pull request by jasoncalabrese**
This should remove some of the annoyance of alarms, no more returning home to alarms for a condition that was already corrected (but not ack'd)

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
I'd like to get this into the release since I think it's a big source of alarm annoyment, would like a review by @bewest and @rnpenguin

**Comment by bewest** [comment]
Looks like some useful clean up here! Thanks.

Is there a new feature that should be `ENABLE`'d here or is this a bug fix?
(This is to help establish design controls, code review, etc...).

**Comment by jasoncalabrese** [comment]
I see this as a bug fix.  Without this fix alarms will continue until ack'd even when the condition changes.

For example when a user is away from home they use the notifications on the dexcom receiver or the pebble to make corrections.  In that case alarms from the `cgm-remote-monitor` are not ack'd or even seen.  When they return home any devices running `cgm-remote-monitor` will still be alarming for a condition that has long since been corrected.  This leads to distrust of the system and false panic.

**Comment by bewest** [comment]
:+1: please :shipit:

**Pull request merged**
