### PR TITLE
Scroll bar hover issue

### PR DESCRIPTION
**Pull request by rkresha**
For issue #1788

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
I tried this out, but it assumes the hamburger menu is last, but careportal and bolus wizard are after if enabled

screenshot 2016-10-11 17 44 16

With dev I don't see the scrollbar in chrome when hovering:
screenshot 2016-10-11 17 48 26

**Comment by rkresha** [comment]
What if you disable careportal and bolus wizard in dev. Then do you
experience the issue?

**Comment by jasoncalabrese** [comment]
Yeah, no scrollbar even with careportal and boluswizard disabled, using the current Chrome 53.0.2785.143 (64-bit) on a mac

screenshot 2016-10-12 09 39 15

**Comment by rkresha** [comment]
I'm on windows 10 64bit (chrome 53.0.2785.143 m) and have a vanilla branch that is a up-to-date clone of nightscout/dev and I still see the issue. I've also tried Firefox/Edge/IE 11 with the same behavior

image

**Comment by rkresha** [comment]
My workaround, which was terrible, was to offset the icon so the underlying balloon text would be more offset to the left. I think the fix is to just move the balloon text to the left and leave the icon alone, but I'd need some guidance on where to adjust it.

**Comment by rkresha** [comment]
You can leave this open, but I'll continue to look into the tipsy side of the house.

**Pull request closed without merging**
