### PR TITLE
Fix devicestatus and treatments id delete

### PR DESCRIPTION
**Pull request by jpcunningh**
Fix for https://github.com/nightscout/cgm-remote-monitor/issues/4080

### CODE REVIEW

**Comment by PieterGit** [comment]
@jpcunningh Do you understand why you need to create a new variable and refer to that in the JSON 
part of the code.
image

From reading the code I would assume that the new code is equivalent (but introduces a new temporary variable). Am I missing something?

**Comment by candreassen** [comment]
Omg stop sending these threads. I hetbloke 50 emails a day.  Stop stop stop please

**Comment by sulkaharo** [comment]
@candreassen if you get emails from changes in Nigthscout, it means your account is actively "watching" the Nightscout repository and thus will get an email from every change. If you want the email to stop, go to the Github Nightscout page (for example, click the "view in Github" link in the email with this message) and find a button on top of the page that says "Unwatch" and either choose "Not Watching" or "Ignore" from the menu.

**Comment by sulkaharo** [comment]
@PieterGit looks like calling the remove() method call with `new ObjectID()` results in the remove() call being called with a function pointer that returns the ObjectID, not the new ObjectID(), which causes the call to fail. Using the temporary variable fixes this as the remove() function is then called with ObjectID, as expected.

**Comment by jpcunningh** [comment]
Thank you for the explanation, @sulkaharo! I didn't know why one way worked vs. the other.

**Comment by PieterGit** [comment]
@sulkaharo thanks for the explanation. I hate merging stuff I don't understand.
@jpcunningh thanks for the fix

**Comment by PieterGit** [comment]
The user documentation for this feature can be improved. I logged issue https://github.com/nightscout/documentation/issues/2 for that.

**Comment by staceyc2578** [comment]
How do I stop getting email notifications

**Pull request merged**
