### PR TITLE
OOOPS

### PR DESCRIPTION
**Pull request by denvergail**

### CODE REVIEW

**Comment by sulkaharo** [comment]
Hi! It seems this pull request was made the wrong way round - you're trying to pull changes from your copy of Nightscout into the master version, when the correct direction is from master into your copy. Please try again and pay special attention to the source (Nightscout master) and target (your copy) merge direction settings.

**Comment by denvergail** [comment]
Thanks. It was a mistake, obviously. 

I’m unable to merge the update into my master. Error is with the jason pkg. Can’t find instructions for dealing with errors so I finally gave up.

**Comment by sulkaharo** [comment]
Hi! If you haven't done any actual development, the easiest way to get rid of the merge error is to just delete your Nightscout fork entirely in Github and create a new fork, then connect to Github again in Heroku and deploy the master from the new fork.

**Comment by denvergail** [comment]
I’ll try to tackle it again tonight. I could not figure out how to delete the original fork but am sure I’ll find a solution. 

Thanks for your help!

**Pull request closed without merging**
