### PR TITLE
bulgarian language - 17.Sept.2015

### PR DESCRIPTION
**Pull request by xpucuto**

### CODE REVIEW

**Comment by MilosKozak** [comment]
missing comma before 
bg: 'Ред'
edit language.js in branch patch-6 again

**Comment by xpucuto** [comment]
Oh, sorry, i will merge a new one . 

Thanks

**Comment by MilosKozak** [comment]
just edit the file. the rest will be done automaticaly

**Comment by MilosKozak** [comment]
https://github.com/xpucuto/cgm-remote-monitor/edit/patch-6/lib/language.js

**Comment by xpucuto** [comment]
done

**Comment by MilosKozak** [comment]
:+1: perfect

**Pull request merged**
