### PR TITLE
Alexa metric synonyms

### PR DESCRIPTION
**Pull request by tanja3981**
Currently the list of metrics could only be asked in english. As you can now defined synonyms in the amazon developer portal, this can be used for translated/costumized terms.

### CODE REVIEW

**Comment by PieterGit** [comment]
@tanja3981 Can you check the CI build errrors?
@francesc0-cgm (or other Alexa users) Can you help test this PR?

**Comment by francesc0-cgm** [comment]
I am doing @pietergit 
All utterances in italian works now. I still have problems with metrics but i am trying with the help of @tanja3981 to get them working

**Comment by tanja3981** [comment]
@PieterGit Honestly I have no clue why the build failed, as I rebased on dev directly before adding that pull request and my branch was built without that problem. 
Also the error doesn't explain anything to me. Could you have a look and check what certifcate problem could be caused by? Thanks in advance.

**Comment by tanja3981** [comment]
@winni67 If you have the time, it would be great if you could test. Please note that I updated the Readme regarding how to setup the skill (-> synonyms) in amazons developer portal.

**Comment by francesc0-cgm** [comment]
As i reported in my other pull request PR of @tanja3981 is fully working. Only loop status is still in english

**Comment by tanja3981** [comment]
@PieterGit Will this be pulled into upcoming release? 
The build errors are gone since travis rebuilt.

**Comment by PieterGit** [comment]
@tanja3981 The Alexa plugin is not separated well enough from other core files and other plugins. This is the reason why we postponed the Google Home plugin integration to Nightscout 0.12 release, see 
https://github.com/nightscout/cgm-remote-monitor/pull/4035 

Problem with the Alexa is, that it has been merged with Nightscout 0.10.x .

@jasoncalabrese @sulkaharo Can you please join this discussion and I propose to set a minimum of improvements to the Alexa plugin in order to merge this PR with 0.11. Thoughts?

@tanja3981 Minor issue. Please correct the conflicting  `lib/plugins/alexa-plugin.md`

**Comment by PieterGit** [comment]
@tanja3981 @francesc0-cgm Alexa support will not be improved in 0.11 because the Alexa code really needs to be re-organized to be maintainable. See https://github.com/nightscout/cgm-remote-monitor/issues/4168#issuecomment-451701994 for some more details.

**Comment by tanja3981** [comment]
@PieterGit Regarding your comment from Jan 6, I volunteer for the maintenance of the current version of the alexa plugin.
However, I still don't really understand the plan how the alexa plugin will be refactored, so I would leave the question about wether I'm able to develop it further and maintain it open. ;-)

**Comment by PieterGit** [comment]
@tanja3981 Is this PR still relevant?

Please have a look at @inventor96 work on https://github.com/nightscout/cgm-remote-monitor/pull/4980

Closing PR. Please reopen if this can be implemented in a generic and maintainable way.

**Comment by inventor96** [comment]
@tanja3981 @PieterGit I didn't look much at this PR before I started working on #4980, but it looks like @tanja3981 and I had similar ideas on how to improve the Alexa plugin configuration! There are still a few things that could be applicable if @tanja3981 wants to add to #4980 or create a new PR.

**Comment by tanja3981** [comment]
@inventor96 @PieterGit I will have a look at this during the next few days and will also do some testing!

**Pull request closed without merging**
