### PR TITLE
Wip/libre reporting fixes

### PR DESCRIPTION
**Pull request by rob-andy**
Fixes to nightscout reporting module to handle libre/miaomiao data that is captured at a 1 minute per sgv rate.  This fix also corrects two issues in the GVI calculation

glucosedistribution.js
  * Data cleaning pass 1; Off by one error in for loop.  Additionally, last value in array should be retained.  Original code was losing 2 values
  * Data cleaning pass 2; Off by one error in for loop.  Additionally, last value in array should be retained.  Original code was losing 2 values
  * GVI calculation loop;  
    - Off by one error in for loop.
    - Calculate the true delta between each record
    - Calculate current rate of rise per 5min for each record
    - Calculate distance travelled based on rise and time elapsed for each record
  * Fix error in GVIDelta.  GVI Delta is the difference between last and first value

report.js
  * Allow sgvs that are exactly 1 minute from the last sgv value

### CODE REVIEW

**Comment by rob-andy** [comment]
Adding all the issues I think this addresses;
#3688 #4490 #4496

**Comment by PieterGit** [comment]
@rob-andy thanks for having a look at this. Can you:
- decrease the complexity and make Codacy happy?
- add a unit test for the edge cases we missed?

Is it possible another  libre/miaomiao user can confirm this works?

**Comment by rob-andy** [comment]
Can you be more specific on decrease the complexity?  I haven't actually changed any of the existing algorithms, so would need a little more guidance on what you are expecting?

Can you also point me to the existing unit tests for these two files?

**Comment by GrantGam** [comment]
...

**Comment by PieterGit** [comment]
@rob-andy Some quick remarks. Didn't have a close look at the changes and because of the reformat it's hard to spot the differences:

- please change the base of the PR to `dev` instead of `master`. Please let me know if you don't have the permission to do so
- please add tests to https://github.com/nightscout/cgm-remote-monitor/blob/dev/tests/reports.test.js (we might also split the test to a test per report)
- please confirm that you've tested after these changes
- after that I think @sulkaharo or me will check if it does not have regressions for non-libre users and merge it.

**Comment by josziglimp** [comment]
I would be happy to test the reports generated with this version. I'm currently using nightscout
version 0.11.1 on Heroku.
How can I merge this into my NS? Should there be any problems, is it possible to undo the merge?
Thanks

**Comment by josziglimp** [comment]
I merged this and seems to be working well. Thank you!!

**Comment by rob-andy** [comment]
@PieterGit adding tests for the glucose distribution report is a whole different problem.  If you are going to test it reliably, I think all the data calculation/ processing needs to be broken out so they can be tested individually (and separately to the report page UI) and then you can write a test that verifies the rUI eport page works (as per the other tests in report.test.js).

Currently nothing like this exists for any of the other reports.

**Comment by rob-andy** [comment]
Additionally, the reformatting is broken out as a seperate commit. So you can easily see the logic changes, and then the formatting as per project guidelines applied to the file.  If you don't like the reformat, we can easily drop that

**Comment by sulkaharo** [comment]
LGTM & tested, merging

**Pull request merged**
