### PR TITLE
Move toolbar and authentication status to partial and include on each page

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
This PR creates reusable authentication-status and toolbar partials that is included on each page and styled in consistent way.

Preview of changes:
image
image

Header and authentication status is consistent on each page

### CODE REVIEW

**Comment by sulkaharo** [comment]
This changes the index page layout on mobile - the menus switch from the right to left side

IMG_1020

**Comment by sulkaharo** [comment]
(Looks really good, other than that change)

**Comment by Bartlomiejsz** [comment]
@sulkaharo oh, didn't notice that, I'll fix that then :)

**Comment by Bartlomiejsz** [comment]
@sulkaharo could you please let me know on what device is that? And are you sure those are not old styled cached?
image

**Comment by sulkaharo** [comment]
🤔 Yup can't repro now. I did clear the cache for the previous test, but guess something went wrong with that. This would be an iPhone 11.

**Pull request merged**
