### PR TITLE
Allow to use proxy with nightscout

### PR DESCRIPTION
**Pull request by GermanBluefox**
My change allows to use nightscout behind proxy and to use nightscout in form http://ip:port/nightscout/....

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Next time I will create PR for dev. But now is too late.

**Comment by sulkaharo** [comment]
Might want to close this and submit a new PR toward DEV? Have you tested this with the other views (reporting, settings, admin..)?

**Comment by MilosKozak** [comment]
close this pr and create new targeting dev

**Comment by GermanBluefox** [comment]
Thank you.

19 Фев 2017 г. 23:54 пользователь "Milos Kozak" <notifications@github.com>
написал:

**Comment by sulkaharo** [comment]
Implemented in #2780

**Pull request closed without merging**
