### PR TITLE
Prevent Pushover server error from crashing Nigthscout

### PR DESCRIPTION
**Pull request by sulkaharo**
Add try/catch blocks around Pushover requests

### CODE REVIEW

**Comment by terrbear** [comment]
I just wrote this same changeset and was about to submit a PR :)

**Comment by terrbear** [comment]
For context, this happens if pushover is being DDOS'd and replies with html instead of json:

> Oct 26 01:55:42 mayabetes app/web.1: WS: emitted clear_alarm to all clients 
> Oct 26 01:55:42 mayabetes app/web.1: 2019-10-26T08:55:42.633Z	EMITTING ALL CLEAR: 
> Oct 26 01:55:42 mayabetes app/web.1:   {"level":"Unknown","title":"All Clear","message":"Auto ack'd alarm(s)","group":"default","plugin":"<none>"} 
> Oct 26 01:55:42 mayabetes app/web.1: WS: running websocket.update 
> Oct 26 01:55:42 mayabetes app/web.1: delta calculation indicates no new data is present 
> Oct 26 01:55:45 mayabetes app/web.1: undefined:1 
> Oct 26 01:55:45 mayabetes app/web.1: <!DOCTYPE html> 
> Oct 26 01:55:45 mayabetes app/web.1: ^ 
> Oct 26 01:55:45 mayabetes app/web.1:  
> Oct 26 01:55:45 mayabetes app/web.1: SyntaxError: Unexpected token < in JSON at position 0 
> Oct 26 01:55:45 mayabetes app/web.1:     at JSON.parse (<anonymous>) 
> Oct 26 01:55:45 mayabetes app/web.1:     at Pushover.errors (/app/node_modules/pushover-notifications/lib/pushover.js:134:14) 
> Oct 26 01:55:45 mayabetes app/web.1:     at IncomingMessage.<anonymous> (/app/node_modules/pushover-notifications/lib/pushover.js:241:12) 
> Oct 26 01:55:45 mayabetes app/web.1:     at IncomingMessage.emit (events.js:203:15) 
> Oct 26 01:55:45 mayabetes app/web.1:     at endReadableNT (_stream_readable.js:1145:12) 
> Oct 26 01:55:45 mayabetes app/web.1:     at process._tickCallback (internal/process/next_tick.js:63:19)
> 

Then the app crashes and it doesn't come back up until something makes a request to it (on Heroku).

**Comment by sulkaharo** [comment]
@terrbear looks like the error needs catching in the module so I made a fork with the catch, let's see if this helps. Or did you manage to mitigate this inside Nigthscout?

**Comment by terrbear** [comment]
It might have been lucky timing but after deploying to my instance w/ a catch just here:

>   pushover.sendAPIRequest = function sendAPIRequest (msg, callback) {
>     try {
>       pushoverAPI.send(msg, function response (err, result) {
>         if (err) {
>           console.error('unable to send pushover notification', msg, err);
>         } else {
>           console.info('sent pushover notification: ', msg, 'result: ', result);
>         }
>         callback(err, result);
>       });
>     } catch (err) {
>       console.error('unable to send pushover notification', err);
>     }
>   };

Errors stop:
Screen Shot 2019-10-27 at 7 57 53 AM

Did you still have problems after your patch was up? I'm happy to set something up to reproduce that scenario :)

**Comment by sulkaharo** [comment]
@terrbear Yup I had a crash after I added the try/catch blocks to Nightscout, thus the PR to add the catch into the JSON parsing in the node module itself. If you look at the stack trace for the crash, at least for me the crash is triggered in Node stack when the response is received and we can't catch the error in Nightscout

**Comment by terrbear** [comment]
Lemme try to recreate locally - I'm hoping I can just fake pushover interactions to return bunk html and see what happens.

**Comment by terrbear** [comment]
I couldn't repro, then realized I had the newer version of pushover-notifications already pulled down. Is this needed now?

**Comment by terrbear** [comment]
oh well the shrinkwrap'll need to get updated since it's locking at .0

**Pull request closed without merging**
