### PR TITLE
update logos and favicons

### PR DESCRIPTION
**Pull request by jasoncalabrese**
large

cgm ns enchilada icon

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
screen shot 2015-04-18 at 3 36 11 pm

**Comment by francescaneri** [comment]
:+1:

**Comment by francescaneri** [comment]
apple-touch-icon-180x180

**Comment by jasoncalabrese** [comment]
I think the orange is too much, I'm planning to go with the images at the top

**Pull request merged**
