### PR TITLE
Something linemen

### PR DESCRIPTION
**Pull request by linemen**

### CODE REVIEW

**Comment by unsoluble** [comment]
Can you please share a link to the guide you followed to attempt this update? Trying to track down the source of these backwards PRs.

**Comment by linemen** [comment]
Hi John,

I followed this link:

http://nightscout.github.io/pages/update-fork/?fbclid=IwAR2_0XJDz30e63UqGgt45FLrM1GVQ6SPehz_PnwHKw7yIKIRC9y3n3doudE

It showed me, that my Nightscout was not up to date. So I followed the prompts to update.

I wasn’t logged into Github though, so I didn’t get the Create Pull Request button.

After logging in, I was able to create the pull request, but then merging was blocked.

A while later I started over, and everything worked. It might be a useful hint, to include in the instructions, that one has to be logged into Github. The guide was a java script popup window.

I hope this helps, and thanks for all the work you do for the community,

Roxana

**Comment by unsoluble** [comment]
Thanks so much for the detailed info — that helps a lot!

I’ll tweak the update guide to make it clear that you need to be logged in _first_.

You can go ahead and close this pull request (when you’re viewing it on GitHub, there’s a Close button down at the bottom).

**Comment by linemen** [comment]
Found it. Thanks again.

**Pull request closed without merging**
