### PR TITLE
Add triple-arrow SVGs

### PR DESCRIPTION
**Pull request by unsoluble**
PRing this separately from the clock-refactoring branch, so that these images can get into 0.11.2 alongside the rest of the triple-arrow support.

### CODE REVIEW

**Comment by unsoluble** [comment]
(Sorry about the lack of commit-squashing in my PRs — I know it can be done, just not familiar enough with the process to be able to do it safely yet.)

**Comment by jasoncalabrese** [comment]
what device are the triple arrows used for?  this looks safe, but I'm not sure where these are used

**Comment by unsoluble** [comment]
Medtronic CGMs. Until recently they’ve been re-mapped to the Dexcom-style of arrow progression, but we’re now aiming to support the native Medtronic style as well.

**Comment by jasoncalabrese** [comment]
I squashed this while merging, looks nice and clean now https://github.com/nightscout/cgm-remote-monitor/commit/0bac2b5d5fb0b9200d3f6ecf025adc19a0b2657b

**Comment by unsoluble** [comment]
Thanks! Any tips for safe & easy squashing before PRing? Always feel a little bad about including all my sync commits.

**Comment by jasoncalabrese** [comment]
what I do is rebase locally and then force push to the branch that I want to merge

to do that I add a remote to the NS repo, and disable pushes to it so I don't make a mistake
`git remote add nightscout https://github.com/nightscout/cgm-remote-monitor.git`
`git remote set-url --push nightscout no_push`

then I fetch the nightscout remote with `git fetch nightscout`

then you can do `git rebase nightscout/dev` or if you make a mess reset your local branch with (git reset --hard nightscout/dev) and cherry-pick the commit or commits 1 at a time with `git cherry-pick <commit-hash>`

`git rebase -i` (interactive) is really powerful, it takes some practice to get used to it, but lets you merge/reorder/delete/edit commits

when I force push after a rebase I use `git push --force-with-lease` to make sure the remote hasn't changed out from under me, we have force pushes disable for the dev and master since it would confuse anyone that pulled/merged before, but it's fine for feature branches that aren't used by others before a merge

**Comment by unsoluble** [comment]
Awesome, thanks very much for the notes — will give that a shot on the next PR. :)

**Pull request merged**
