### PR TITLE
funnel cake

### PR DESCRIPTION
**Pull request by shawarbeh**
pull request

### CODE REVIEW

**Comment by jasoncalabrese** [comment]
This pull request is going in the wrong direction, sent https://github.com/shawarbeh/cgm-remote-monitor/pull/2

**Comment by shawarbeh** [comment]
what should I do, how can I fix it.

**Comment by jasoncalabrese** [comment]
just click https://github.com/shawarbeh/cgm-remote-monitor/pull/2, review the note I left there, and when you are ready scroll all the way to the bottom and press big merge button

**Comment by shawarbeh** [comment]
Deployment failed, that's what it says in azure, any thoughts?

**Comment by jasoncalabrese** [comment]
That happens with Azure sometimes, there's a redeploy button that has worked for most people.  For some people the only fix seems to be creating a new Azure site.

**Pull request closed without merging**
